/* ─────────────────────────────────────────────────────────────────────────
 * EXERCISE NAMING RULES
 * Format:  [Main Variant] [Domain] | [Other modifier] [(equipment/surface)]
 *
 *   • Domain        — the movement family: Push-Up, Pull-Up, Front Lever, …
 *   • Main Variant  — qualifiers like "One Arm"; always filled FIRST and
 *                     placed BEFORE the domain (never after a "|").
 *   • Other modifier— only added when an exercise has TWO modifiers; goes
 *                     AFTER the "|".
 *   • (equipment)   — always AFTER the "|" and in brackets.
 *
 * Examples:
 *   Push-Up | One Arm           → NEVER
 *   One Arm Push-Up             → YES
 *   Push-Up | Negative          → NEVER
 *   Negative Push-Up            → YES
 *   One Arm Push-Up | Negative  → YES
 *
 * The standard Push-Up is the anchor at diff 3.0. For difficulty or kcal
 * calibration, check pushup-data.js or ask.
 *
 * ADDING AN EXERCISE — log it here: ID · NAME · DIFF. IDs must be unique
 * within this file; check existing ids before assigning a new one.
 * ───────────────────────────────────────────────────────────────────────── */

const combos = [

  /* ── ORIGINALS ──────────────────────────────────────────────────────────── */

  {
    id: 1,
    name: "Muscle-Up | Flow (Bar / Rings)",
    alt: "Bar muscle-up combination",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:false}
    ],
    tags: ["pull", "push", "core", "bar", "dynamic"],
    diff: 8,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 4,
    joints: {wrist:3, elbow:3, shoulder:4, neck:1, lowerBack:2, hip:1, knee:1, ankle:0, fingers:2, thoracic:2, si:1, groin:0, foot:0},
    technique: 4,
    mobility: 3,
    strength: 5,
    kcalPerRep: [0.6, 1.0],
    desc: "A muscle-up centric flow that links the pull, transition, and press into a continuous bar combination. It trains timing, body tension and explosive conversion between pulling and pushing.",
    cues: "Stay compact through the turnover, keep the chest high at the top, and avoid losing the hollow-body pull into the catch.",
    equipment: "Pull-up bar / rings",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 2,
    name: "L-Sit Muscle-Up | Combo (Bar / Rings)",
    alt: "Hold-to-pull muscle-up",
    muscles: [
      {n:"Core", p:true},
      {n:"Back", p:true},
      {n:"Triceps", p:false},
      {n:"Shoulders", p:false}
    ],
    tags: ["pull", "core", "bar", "static", "dynamic"],
    diff: 9,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:3, elbow:3, shoulder:4, neck:1, lowerBack:3, hip:3, knee:1, ankle:0, fingers:2, thoracic:2, si:1, groin:0, foot:0},
    technique: 5,
    mobility: 4,
    strength: 5,
    kcalPerRep: [0.7, 1.1],
    desc: "A muscle-up performed from an L-sit entry and finished with L-sit control on the top. This combo demands strong core compression and precise hip position throughout the pull and transition.",
    cues: "Keep the legs straight and out in front, pull the chest up, and maintain a firm hollow position as you complete the transition.",
    equipment: "Pull-up bar / rings",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 3,
    name: "Muscle-Up | Dip Combo (Rings)",
    alt: "Ring muscle-up dip combo",
    muscles: [
      {n:"Shoulders", p:true},
      {n:"Triceps", p:true},
      {n:"Back", p:true},
      {n:"Core", p:false}
    ],
    tags: ["rings", "push", "pull", "dynamic", "stability"],
    diff: 10,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:4, elbow:4, shoulder:5, neck:1, lowerBack:3, hip:2, knee:0, ankle:0, fingers:3, thoracic:2, si:1, groin:0, foot:0},
    technique: 5,
    mobility: 4,
    strength: 5,
    kcalPerRep: [0.8, 1.2],
    desc: "A ring muscle-up that flows into a strict ring dip at the top. The unstable ring path makes the transition and press much harder than a standard muscle-up, and it also builds elite ring stability.",
    cues: "Control the rings through the transition, keep the shoulders packed, and only press once the rings are stable overhead.",
    equipment: "Gymnastic rings",
    position: "Rings",
    youtube: "LINK_TODO"
  },
  {
    id: 4,
    name: "Muscle-Up | Archer Combo (Bar)",
    alt: "Explosive pull-up combo",
    muscles: [
      {n:"Back", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:false},
      {n:"Arms", p:false}
    ],
    tags: ["pull", "power", "bar", "complex"],
    diff: 9,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 4,
    joints: {wrist:3, elbow:4, shoulder:4, neck:1, lowerBack:2, hip:1, knee:0, ankle:0, fingers:3, thoracic:2, si:1, groin:0, foot:0},
    technique: 5,
    mobility: 3,
    strength: 5,
    kcalPerRep: [0.8, 1.25],
    desc: "A powerful bar sequence where a muscle-up is immediately followed by a controlled archer pull-up to each side. It blends high-skill transition strength and unilateral upper-body tension.",
    cues: "Complete the muscle-up efficiently, then keep the body long and use the hips only for balance while shifting to the archer pull-up.",
    equipment: "Pull-up bar",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 5,
    name: "Muscle-Up | Planche Lean (Bar / Parallettes)",
    alt: "Transition to planche press",
    muscles: [
      {n:"Core", p:true},
      {n:"Shoulders", p:true},
      {n:"Chest", p:true},
      {n:"Back", p:false}
    ],
    tags: ["planche", "push", "core", "advanced"],
    diff: 10,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:5, elbow:4, shoulder:5, neck:1, lowerBack:3, hip:2, knee:0, ankle:0, fingers:3, thoracic:2, si:1, groin:0, foot:0},
    technique: 5,
    mobility: 4,
    strength: 5,
    kcalPerRep: [0.7, 1.1],
    desc: "A skill combo starting from a bar muscle-up and continuing into a forward-lean planche position. It links the upper-body pulling motion to a high-demand static press lean.",
    cues: "After the muscle-up, lean the shoulders forward steadily while keeping the arms straight and the core braced.",
    equipment: "Pull-up bar / parallettes",
    position: "Vertical / Elevated",
    youtube: "LINK_TODO"
  },

  /* ── GRIP VARIANTS ──────────────────────────────────────────────────────── */

  {
    id: 6,
    name: "Supinated Muscle-Up | (Bar)",
    alt: "Supinated / underhand muscle-up",
    muscles: [
      {n:"Biceps", p:true},
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Triceps", p:false}
    ],
    tags: ["pull", "push", "bar", "dynamic", "supinated", "grip"],
    diff: 7,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 3,
    joints: {wrist:3, elbow:4, shoulder:3, neck:1, lowerBack:2, hip:1, knee:0, ankle:0, fingers:2, thoracic:2, si:1, groin:0, foot:0},
    technique: 4,
    mobility: 3,
    strength: 5,
    kcalPerRep: [0.6, 1.0],
    desc: "A muscle-up executed with a supinated (chin-up, palms-facing-you) grip. The underhand position recruits more biceps during the pull phase and can make the transition slightly more accessible for athletes whose pulling strength is chin-up dominant. The wrist still rotates through the transition, but the path feels more natural for many beginners.",
    cues: "Lead with the elbows tracking inward, actively rotate the wrists through the turnover, and keep the chest tall at full lockout.",
    equipment: "Pull-up bar",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 7,
    name: "Close-Grip Muscle-Up | (Bar)",
    alt: "Narrow / diamond grip muscle-up",
    muscles: [
      {n:"Triceps", p:true},
      {n:"Chest", p:true},
      {n:"Back", p:true},
      {n:"Core", p:false}
    ],
    tags: ["pull", "push", "bar", "narrow", "dynamic", "grip"],
    diff: 8,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 4,
    joints: {wrist:4, elbow:5, shoulder:3, neck:1, lowerBack:2, hip:1, knee:0, ankle:0, fingers:3, thoracic:2, si:1, groin:0, foot:0},
    technique: 4,
    mobility: 3,
    strength: 5,
    kcalPerRep: [0.6, 1.0],
    desc: "Hands placed 6–10 cm apart on the bar. The narrow grip shifts more demand onto the triceps through the press phase and demands tighter elbow tracking throughout the pull. The transition feels more compact but requires greater wrist and elbow mobility. Elbow stress is notably elevated — build up gradually.",
    cues: "Pin the elbows together throughout the pull, drive the bar close to the sternum on the way up, and press to lockout with elbows pointing backward, not flaring.",
    equipment: "Pull-up bar",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 8,
    name: "Wide-Grip Muscle-Up | (Wide Bar)",
    alt: "Snatch-width / broad-grip muscle-up",
    muscles: [
      {n:"Back", p:true},
      {n:"Shoulders", p:true},
      {n:"Chest", p:true},
      {n:"Core", p:false}
    ],
    tags: ["pull", "push", "bar", "wide", "advanced", "grip"],
    diff: 9,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:3, elbow:3, shoulder:5, neck:1, lowerBack:2, hip:1, knee:0, ankle:0, fingers:2, thoracic:3, si:1, groin:0, foot:0},
    technique: 5,
    mobility: 5,
    strength: 5,
    kcalPerRep: [0.7, 1.1],
    desc: "Hands placed much wider than shoulder-width — often approaching snatch grip — making both the pull and the transition considerably harder. The wide path dramatically increases shoulder internal rotation demand at the catch and loads the posterior shoulder and lats differently than any standard variant. Full shoulder mobility is mandatory, not optional.",
    cues: "Pull with maximum lat engagement, keep the scapulae actively depressed throughout, and do not force the transition if shoulder mobility limits the range — this one earns injuries quickly.",
    equipment: "Pull-up bar (wide)",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 9,
    name: "Neutral-Grip Muscle-Up | (Parallel Bars / Neutral Handles)",
    alt: "Hammer / parallel-grip muscle-up",
    muscles: [
      {n:"Back", p:true},
      {n:"Shoulders", p:true},
      {n:"Triceps", p:true},
      {n:"Core", p:false}
    ],
    tags: ["pull", "push", "parallel", "neutral", "dynamic", "grip"],
    diff: 7,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 3,
    joints: {wrist:2, elbow:3, shoulder:3, neck:1, lowerBack:2, hip:1, knee:0, ankle:0, fingers:2, thoracic:2, si:1, groin:0, foot:0},
    technique: 4,
    mobility: 3,
    strength: 5,
    kcalPerRep: [0.6, 0.9],
    desc: "Performed on parallel bars or neutral-grip handles with palms facing inward. The neutral wrist alignment eliminates forearm rotation stress and places the shoulder in a more biomechanically efficient path through all three phases. Often the most wrist- and elbow-friendly muscle-up variant and a good choice for athletes managing upper-limb irritation.",
    cues: "Use a firm hollow-body pull, drive the hips up and through the bars, and press to full lockout keeping the elbows close to the body.",
    equipment: "Parallel bars / neutral-grip pull-up handles",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 10,
    name: "False-Grip Muscle-Up | (Bar)",
    alt: "Wrist-over-bar muscle-up",
    muscles: [
      {n:"Back", p:true},
      {n:"Forearms", p:true},
      {n:"Chest", p:true},
      {n:"Core", p:false}
    ],
    tags: ["pull", "push", "bar", "false grip", "wrist", "grip"],
    diff: 7,
    str: {suit:true, eff:4},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 4,
    joints: {wrist:5, elbow:3, shoulder:4, neck:1, lowerBack:2, hip:1, knee:0, ankle:0, fingers:3, thoracic:2, si:1, groin:0, foot:0},
    technique: 4,
    mobility: 4,
    strength: 4,
    kcalPerRep: [0.5, 0.9],
    desc: "The wrist is placed over — rather than around — the bar so the pad of the hand and the proximal wrist ride on top. This pre-positions the forearm for the transition and largely removes the wrist-flip requirement. A useful technical bridge toward ring false-grip work. Wrist conditioning must be built progressively — the compression on the joint is substantial.",
    cues: "Maintain firm false-grip contact throughout the entire pull without rolling off, do not lose the grip at the transition peak, and dedicate wrist-prep work before training this variant.",
    equipment: "Pull-up bar",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 11,
    name: "Mixed-Grip Muscle-Up | (Bar)",
    alt: "One-over one-under muscle-up",
    muscles: [
      {n:"Back", p:true},
      {n:"Biceps", p:true},
      {n:"Chest", p:true},
      {n:"Core", p:false}
    ],
    tags: ["pull", "push", "bar", "mixed grip", "unilateral", "grip"],
    diff: 8,
    str: {suit:true, eff:4},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 4,
    joints: {wrist:4, elbow:4, shoulder:4, neck:1, lowerBack:2, hip:1, knee:0, ankle:0, fingers:3, thoracic:2, si:1, groin:0, foot:0},
    technique: 4,
    mobility: 3,
    strength: 5,
    kcalPerRep: [0.6, 1.0],
    desc: "One hand grips overhand (pronated) and the other grips underhand (supinated). The asymmetric setup creates different bicep and forearm activation on each side and introduces a subtle rotational pull through the transition — the body wants to spin toward the supinated side. A useful diagnostic tool for identifying bilateral pulling imbalances.",
    cues: "Alternate which hand is supinated in each working set to develop both sides evenly, stay deliberate about countering the rotational drift, and keep the pull path vertical.",
    equipment: "Pull-up bar",
    position: "Vertical",
    youtube: "LINK_TODO"
  },

  /* ── STYLE / TECHNIQUE VARIANTS ─────────────────────────────────────────── */

  {
    id: 12,
    name: "Strict Muscle-Up | (Bar)",
    alt: "No-kip / zero-swing muscle-up",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:true}
    ],
    tags: ["pull", "push", "bar", "strict", "strength", "no-kip"],
    diff: 9,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 4,
    joints: {wrist:3, elbow:3, shoulder:4, neck:1, lowerBack:2, hip:1, knee:0, ankle:0, fingers:2, thoracic:2, si:1, groin:0, foot:0},
    technique: 5,
    mobility: 3,
    strength: 5,
    kcalPerRep: [0.7, 1.1],
    desc: "Started from a dead hang with zero body swing, zero hip drive. The entire movement is powered purely by upper-body pulling and pressing strength. Considered the gold standard for bar muscle-up quality and the prerequisite for most advanced variants. If this is impossible, all other muscle-up variations should wait.",
    cues: "Start completely still, initiate with a strong scapular depression, maintain hollow body throughout, and do not allow the hips to rise before the chest passes the bar.",
    equipment: "Pull-up bar",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 13,
    name: "Kipping Muscle-Up | (Bar)",
    alt: "CrossFit / hip-drive muscle-up",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Hips", p:true},
      {n:"Core", p:false}
    ],
    tags: ["pull", "push", "bar", "kipping", "crossfit", "volume"],
    diff: 6,
    str: {suit:false, eff:3},
    vol: {suit:true, eff:4},
    end: {suit:true, eff:5},
    risk: 4,
    joints: {wrist:2, elbow:3, shoulder:4, neck:1, lowerBack:3, hip:2, knee:1, ankle:0, fingers:2, thoracic:2, si:1, groin:0, foot:0},
    technique: 3,
    mobility: 2,
    strength: 3,
    kcalPerRep: [0.5, 0.8],
    desc: "A hip-driven muscle-up that uses a forward-and-back kip swing to build upward momentum before the transition. The kip lowers the upper-body strength requirement significantly but still creates high shoulder fatigue under repeated reps. Common in timed conditioning workouts where rep volume matters more than force production.",
    cues: "Build a consistent kip swing first, redirect the energy vertically at the front-swing peak, and keep the chest high through the transition — do not let the elbows flare wide.",
    equipment: "Pull-up bar",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 14,
    name: "Chest-to-Bar Kipping Muscle-Up | (Bar)",
    alt: "CTB muscle-up / contact-pull muscle-up",
    muscles: [
      {n:"Back", p:true},
      {n:"Hips", p:true},
      {n:"Chest", p:true},
      {n:"Core", p:false}
    ],
    tags: ["pull", "push", "bar", "kipping", "chest-to-bar", "crossfit"],
    diff: 7,
    str: {suit:false, eff:3},
    vol: {suit:true, eff:4},
    end: {suit:true, eff:5},
    risk: 4,
    joints: {wrist:2, elbow:3, shoulder:4, neck:1, lowerBack:3, hip:3, knee:1, ankle:0, fingers:2, thoracic:2, si:2, groin:0, foot:0},
    technique: 4,
    mobility: 2,
    strength: 3,
    kcalPerRep: [0.5, 0.9],
    desc: "A kipping muscle-up variant where the chest physically makes contact with the bar at the peak of the pull before the body transitions above. The physical touch ensures full pull range of motion and creates a consistent angle for the transition. Common in high-volume workouts as a quality cue to avoid short-rep muscle-ups.",
    cues: "Drive the hips aggressively forward as the chest hits the bar — not before — so the contact becomes the trigger for the transition, not a mid-rep collision.",
    equipment: "Pull-up bar",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 15,
    name: "Muscle-Up | Slow Negative (Bar / Rings)",
    alt: "Eccentric descent / 5-second lowering",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:false}
    ],
    tags: ["eccentric", "bar", "slow", "strength", "control", "negative"],
    diff: 8,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 3,
    joints: {wrist:2, elbow:3, shoulder:3, neck:1, lowerBack:2, hip:1, knee:0, ankle:0, fingers:2, thoracic:2, si:1, groin:0, foot:0},
    technique: 4,
    mobility: 3,
    strength: 5,
    kcalPerRep: [0.6, 1.0],
    desc: "Start at the top of the muscle-up position (jump or be lifted there if needed) and descend slowly — 5 to 10 seconds — through the transition all the way back to a dead hang. Controlled eccentrics overload the same muscles with greater time under tension at a lower injury risk than the concentric version, and expose exactly where pulling strength breaks down.",
    cues: "Resist gravity through every centimetre — own the transition on the way down, do not drop free into the hang, and treat the dead hang arrival as the end of the rep.",
    equipment: "Pull-up bar / rings",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 16,
    name: "Muscle-Up | Paused (Bar / Rings)",
    alt: "Isometric-hold / sticking-point pause",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:true}
    ],
    tags: ["pull", "push", "bar", "isometric", "pause", "strength"],
    diff: 9,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 4,
    joints: {wrist:3, elbow:4, shoulder:4, neck:1, lowerBack:2, hip:1, knee:0, ankle:0, fingers:2, thoracic:2, si:1, groin:0, foot:0},
    technique: 5,
    mobility: 3,
    strength: 5,
    kcalPerRep: [0.6, 1.0],
    desc: "A strict muscle-up with a deliberate 2–3 second pause held at the most challenging point of the movement — typically when the elbows are at bar-height and the body is mid-transition. The pause eliminates stored elastic energy and forces the pressing muscles to restart from a dead stop. Dramatically harder than a fluid rep and excellent for exposing weak transition mechanics.",
    cues: "Know your sticking point before starting, hold there absolutely still, and do not use any bounce or momentum to escape the pause — patience through the hold is the entire training stimulus.",
    equipment: "Pull-up bar / rings",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 17,
    name: "Typewriter Muscle-Up | (Wide Bar)",
    alt: "Side-to-side lateral muscle-up",
    muscles: [
      {n:"Back", p:true},
      {n:"Shoulders", p:true},
      {n:"Chest", p:true},
      {n:"Core", p:true}
    ],
    tags: ["pull", "push", "bar", "lateral", "unilateral", "advanced"],
    diff: 9,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 4,
    joints: {wrist:3, elbow:4, shoulder:4, neck:1, lowerBack:3, hip:2, knee:0, ankle:0, fingers:3, thoracic:3, si:1, groin:0, foot:0},
    technique: 5,
    mobility: 4,
    strength: 5,
    kcalPerRep: [0.8, 1.2],
    desc: "After the muscle-up transition, the athlete slides laterally across the bar — one arm pressing while the body travels to that side, then back to centre, then to the opposite side — mimicking a typewriter carriage. Builds significant unilateral pressing strength and lateral core control while dramatically increasing time under tension per rep.",
    cues: "Extend the reaching arm fully as the body slides across, keep the support arm with a slight bend and a strong shoulder, and maintain chest height above the bar throughout the lateral phase.",
    equipment: "Pull-up bar (minimum 1.5 m wide)",
    position: "Vertical",
    youtube: "LINK_TODO"
  },

  {
    id: 36,
    name: "Muscle-Up | Tempo (Bar / Rings)",
    alt: "Counted-cadence muscle-up (e.g. 3-1-2)",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:true}
    ],
    tags: ["pull", "push", "bar", "tempo", "time under tension", "technique"],
    diff: 8,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 3,
    joints: {wrist:3, elbow:3, shoulder:4, neck:1, lowerBack:2, hip:1, knee:0, ankle:0, fingers:2, thoracic:2, si:1, groin:0, foot:0},
    technique: 5,
    mobility: 3,
    strength: 5,
    kcalPerRep: [0.6, 1.0],
    desc: "A strict muscle-up performed with a prescribed tempo across every phase — for example 3 seconds concentric, 1 second hold at the top, 2 seconds eccentric. Unlike the Slow Negative , which only applies time control to the descent, or the Paused variant , which targets a single sticking point, tempo training governs all three phases simultaneously. It is the most precise method for accumulating controlled time under tension across the full range of motion and removes any reliance on elastic energy or momentum at any point in the rep.",
    cues: "Count out loud or use a metronome. A 3-1-2 cadence is a strong general-purpose starting point — adjust only after the full rep count is consistently hitting every number. If any single phase collapses under the count, reduce reps before reducing the cadence.",
    equipment: "Pull-up bar / rings",
    position: "Vertical",
    youtube: "LINK_TODO"
  },

  /* ── EXPLOSIVE / PLYOMETRIC VARIANTS ────────────────────────────────────── */

  {
    id: 18,
    name: "High-Pull Muscle-Up | (Bar)",
    alt: "Hip-height pull / floating muscle-up",
    muscles: [
      {n:"Back", p:true},
      {n:"Biceps", p:true},
      {n:"Chest", p:true},
      {n:"Core", p:false}
    ],
    tags: ["pull", "explosive", "bar", "power", "dynamic"],
    diff: 8,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 4,
    joints: {wrist:3, elbow:3, shoulder:4, neck:1, lowerBack:2, hip:1, knee:0, ankle:0, fingers:3, thoracic:2, si:1, groin:0, foot:0},
    technique: 4,
    mobility: 3,
    strength: 5,
    kcalPerRep: [0.7, 1.1],
    desc: "The pull phase is executed so explosively that the bar reaches waist or hip level before the body transitions above it — creating a brief moment of weightlessness where the transition requires almost no effort. The goal is developing maximum pulling power and rate of force development, not the transition itself. This is how you train the pulling prerequisite for clapping and 360 work.",
    cues: "Think 'pull the bar to the hips' rather than 'pull the chest to the bar', keep the legs together and feet slightly behind the centre, and let the float carry you — do not yank the transition.",
    equipment: "Pull-up bar",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 19,
    name: "Clapping Muscle-Up | (Bar)",
    alt: "Bar-release / plyometric press muscle-up",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:false}
    ],
    tags: ["pull", "push", "explosive", "bar", "plyometric", "release", "advanced"],
    diff: 10,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:4, elbow:4, shoulder:5, neck:1, lowerBack:3, hip:1, knee:0, ankle:0, fingers:4, thoracic:2, si:1, groin:0, foot:0},
    technique: 5,
    mobility: 3,
    strength: 5,
    kcalPerRep: [0.8, 1.3],
    desc: "At the top of the dip press, the athlete releases the bar entirely, claps the hands in front, and catches the bar again before descending. Requires maximum pressing speed and substantial vertical clearance above the bar. The catch is the most dangerous phase — mistimed re-grip or insufficient height are injury scenarios. Only train this once the explosive high-pull muscle-up is completely consistent.",
    cues: "Press as fast and vertically as possible — height is non-negotiable, re-grip with soft elbows to absorb the landing, and only clap when you are completely confident of clearance.",
    equipment: "Pull-up bar (sturdy, fixed mounting)",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 20,
    name: "360 Muscle-Up | (Bar)",
    alt: "Spinning / full-rotation bar muscle-up",
    muscles: [
      {n:"Back", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:true},
      {n:"Arms", p:false}
    ],
    tags: ["pull", "push", "explosive", "bar", "spin", "dynamic", "360", "freestyle"],
    diff: 10,
    str: {suit:true, eff:4},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:4, elbow:3, shoulder:5, neck:2, lowerBack:3, hip:2, knee:0, ankle:0, fingers:4, thoracic:3, si:1, groin:0, foot:0},
    technique: 5,
    mobility: 4,
    strength: 5,
    kcalPerRep: [0.9, 1.4],
    desc: "The athlete performs a muscle-up, releases at the top, completes a full 360-degree rotation around the bar axis, and re-grasps to continue. A freestyle and calisthenics tricking skill as much as a pure strength movement — timing the release angle and rotation speed correctly is the entire challenge. The press must generate vertical clearance for the spin.",
    cues: "Drive the hips up explosively before releasing, tuck the knees tight to accelerate the rotation, and spot the bar early on the way around to time the re-grip.",
    equipment: "Pull-up bar (sturdy, fixed mounting, clear surroundings)",
    position: "Vertical",
    youtube: "LINK_TODO"
  },

  /* ── LOADED / DIFFICULTY VARIANTS ──────────────────────────────────────── */

  {
    id: 21,
    name: "Weighted Muscle-Up | (Bar)",
    alt: "Loaded muscle-up — vest or dip belt",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:true}
    ],
    tags: ["pull", "push", "bar", "weighted", "advanced", "strength"],
    diff: 9,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:4, elbow:4, shoulder:5, neck:2, lowerBack:3, hip:1, knee:0, ankle:0, fingers:3, thoracic:3, si:2, groin:0, foot:0},
    technique: 5,
    mobility: 3,
    strength: 5,
    kcalPerRep: [0.9, 1.5],
    desc: "A strict muscle-up performed with additional external load via a weight vest, dip belt, or ankle weights. Adding mass amplifies every demand simultaneously — pulling strength, pressing strength, and joint stress — with a compounding effect specifically at the transition point. A prerequisite of 5 clean, strict bodyweight muscle-ups is the minimum standard before adding any load.",
    cues: "Start conservatively at 5–10 kg, ensure perfect technique before progressing load, and treat any loss of transition smoothness as a sign you have exceeded your current load ceiling.",
    equipment: "Pull-up bar + weight vest / dip belt",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 22,
    name: "Archer Muscle-Up | (Wide Bar)",
    alt: "Offset-dominant arm muscle-up",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:true}
    ],
    tags: ["pull", "push", "bar", "unilateral", "archer", "advanced", "one-arm progression"],
    diff: 10,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:4, elbow:4, shoulder:5, neck:1, lowerBack:3, hip:2, knee:0, ankle:0, fingers:3, thoracic:3, si:2, groin:0, foot:0},
    technique: 5,
    mobility: 4,
    strength: 5,
    kcalPerRep: [0.9, 1.4],
    desc: "The pull phase loads one arm heavily while the opposite arm stays nearly fully extended — like a bow-and-arrow draw. The dominant arm drives the transition and the full press while the extended arm acts only as a guide and counterbalance. The single most effective stepping stone between standard muscle-ups and true one-arm work. Progress by reducing the assist arm bend by ~5 degrees per training cycle.",
    cues: "Load the dominant arm from the very first centimetre, keep the assist arm locked and long throughout, and do not allow the body to tip or rotate toward the dominant side.",
    equipment: "Pull-up bar (wide enough for offset grip)",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 23,
    name: "One-Arm Muscle-Up | (Bar)",
    alt: "Single-arm bar muscle-up",
    muscles: [
      {n:"Back", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:true},
      {n:"Chest", p:true}
    ],
    tags: ["pull", "push", "bar", "one-arm", "elite", "unilateral"],
    diff: 10,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:4, elbow:5, shoulder:5, neck:2, lowerBack:4, hip:2, knee:0, ankle:0, fingers:4, thoracic:3, si:2, groin:0, foot:0},
    technique: 5,
    mobility: 4,
    strength: 5,
    kcalPerRep: [1.0, 1.6],
    desc: "The complete muscle-up cycle — pull, transition, press — performed with one arm. The non-working hand may touch the wrist for balance or hang free entirely. Considered one of the highest-level bar skills in calisthenics. Total mastery of bilateral strict muscle-ups, weighted muscle-ups, and archer muscle-ups across many training cycles is the minimum realistic prerequisite.",
    cues: "Brace the entire body as a rigid unit before initiating, keep the pull path directly under the centre of mass, and do not sacrifice form for the sake of completing a rep — poor technique on a one-arm MU is an injury, not a training win.",
    equipment: "Pull-up bar",
    position: "Vertical",
    youtube: "LINK_TODO"
  },

  /* ── RING VARIANTS ──────────────────────────────────────────────────────── */

  {
    id: 24,
    name: "Tuck Muscle-Up | (Rings)",
    alt: "Knee-tuck ring muscle-up",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Core", p:true},
      {n:"Shoulders", p:false}
    ],
    tags: ["rings", "pull", "push", "tuck", "dynamic"],
    diff: 8,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 4,
    joints: {wrist:4, elbow:3, shoulder:5, neck:1, lowerBack:2, hip:2, knee:1, ankle:0, fingers:3, thoracic:2, si:1, groin:0, foot:0},
    technique: 4,
    mobility: 3,
    strength: 5,
    kcalPerRep: [0.7, 1.1],
    desc: "A ring muscle-up with knees tucked tightly toward the chest throughout the movement. The tuck shortens the leg moment arm, reducing the strength requirement compared to an L-sit variant while still placing the full instability load of the ring surface through every phase. A practical first ring muscle-up goal before opening to a full straight-body or L-sit version.",
    cues: "Hold the tuck consistently — do not let the legs drop mid-transition — and control the ring path by keeping them shoulder-width apart through the entire press.",
    equipment: "Gymnastic rings",
    position: "Rings",
    youtube: "LINK_TODO"
  },
  {
    id: 25,
    name: "Strict Muscle-Up | (Rings)",
    alt: "Dead-hang false-grip ring muscle-up",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:true}
    ],
    tags: ["rings", "strict", "false grip", "pull", "push", "elite"],
    diff: 10,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:5, elbow:4, shoulder:5, neck:1, lowerBack:3, hip:2, knee:0, ankle:0, fingers:4, thoracic:3, si:1, groin:0, foot:0},
    technique: 5,
    mobility: 5,
    strength: 5,
    kcalPerRep: [0.9, 1.4],
    desc: "A dead-hang ring muscle-up with a full false grip and zero kipping or momentum. The rings introduce constant three-dimensional stabilisation demand through every phase — pull, transition, press — and the false grip eliminates the wrist-roll requirement of a standard ring muscle-up. The benchmark of ring upper-body mastery in gymnastics strength training.",
    cues: "Establish a solid false grip before leaving the hang position, keep the rings tracking close to the body during the pull, and finish in a stable support with rings turned out at full lockout.",
    equipment: "Gymnastic rings",
    position: "Rings",
    youtube: "LINK_TODO"
  },
  {
    id: 26,
    name: "L-Sit Muscle-Up | (Rings)",
    alt: "L-sit entry / exit ring muscle-up",
    muscles: [
      {n:"Core", p:true},
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Hip Flexors", p:true}
    ],
    tags: ["rings", "core", "l-sit", "pull", "push", "elite"],
    diff: 10,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:5, elbow:4, shoulder:5, neck:1, lowerBack:4, hip:4, knee:1, ankle:0, fingers:4, thoracic:3, si:2, groin:1, foot:0},
    technique: 5,
    mobility: 5,
    strength: 5,
    kcalPerRep: [0.9, 1.5],
    desc: "A ring muscle-up performed while maintaining a strict L-sit — legs horizontal and parallel to the floor — from dead hang through the transition and into the support position at the top. Combines the highest demands of ring instability, core compression, hip flexor strength, and shoulder stability simultaneously. One of the most difficult accessible bodyweight movements.",
    cues: "Establish the L-sit before initiating the pull, do not let the legs drop through the transition, and finish with the body fully upright and legs still extended at the top.",
    equipment: "Gymnastic rings (set high enough to accommodate L-sit clearance)",
    position: "Rings",
    youtube: "LINK_TODO"
  },

  {
    id: 38,
    name: "Kipping Muscle-Up | (Rings)",
    alt: "Hip-driven ring muscle-up",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Hips", p:true},
      {n:"Core", p:false}
    ],
    tags: ["rings", "kipping", "dynamic", "conditioning", "crossfit", "volume"],
    diff: 8,
    str: {suit:false, eff:3},
    vol: {suit:true, eff:4},
    end: {suit:true, eff:5},
    risk: 5,
    joints: {wrist:4, elbow:3, shoulder:5, neck:1, lowerBack:3, hip:3, knee:1, ankle:0, fingers:3, thoracic:2, si:2, groin:0, foot:0},
    technique: 5,
    mobility: 3,
    strength: 4,
    kcalPerRep: [0.6, 1.0],
    desc: "A kipping muscle-up performed on gymnastic rings instead of a fixed bar. The hip-driven swing that powers the bar version  now occurs on a surface that rotates freely in three dimensions — the rings want to separate, twist, and drift unpredictably throughout the kip cycle. Ring path control, grip strength, and wrist stability are all heavily loaded even before the transition begins. Shoulder fatigue accumulates significantly faster than on bar, and the false grip must be maintained through a moving surface. A conditioning standard in CrossFit ring programming.",
    cues: "Establish a controlled, symmetrical kip swing first — both rings must travel together before the hip redirect. Maintain the false grip firmly throughout, and do not allow the rings to drift wide during the transition or the press.",
    equipment: "Gymnastic rings",
    position: "Rings",
    youtube: "LINK_TODO"
  },
  {
    id: 39,
    name: "Weighted Muscle-Up | (Rings)",
    alt: "Loaded ring muscle-up — vest or belt",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:true}
    ],
    tags: ["rings", "weighted", "advanced", "loaded", "elite", "strength"],
    diff: 10,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:5, elbow:4, shoulder:5, neck:2, lowerBack:3, hip:1, knee:0, ankle:0, fingers:4, thoracic:3, si:2, groin:0, foot:0},
    technique: 5,
    mobility: 5,
    strength: 5,
    kcalPerRep: [1.0, 1.6],
    desc: "A strict ring muscle-up performed with additional external load via a weight vest or dip belt. The three-dimensional instability of the rings does not diminish with added mass — it compounds it. Shoulder stabiliser demand under load on a moving surface far exceeds what weighted bar work produces at equivalent kilogram increments, and the wrist and finger load from false-gripping under weight is substantial. A genuinely elite strength marker. Prerequisites: consistent strict ring muscle-up  and competent weighted bar muscle-up  at moderate loads before attempting any ring loading.",
    cues: "Start at 5 kg maximum. Prioritise ring path control over load progression, and treat any deviation in ring tracking as a hard cap on weight — form breakdown on weighted rings causes injuries at a fundamentally different rate than bar work.",
    equipment: "Gymnastic rings + weight vest / dip belt",
    position: "Rings",
    youtube: "LINK_TODO"
  },

  /* ── MOBILITY / POSITION VARIANTS ──────────────────────────────────────── */

  {
    id: 27,
    name: "Behind-the-Neck Muscle-Up | (Bar)",
    alt: "BTN muscle-up",
    muscles: [
      {n:"Back", p:true},
      {n:"Rear Deltoids", p:true},
      {n:"Chest", p:true},
      {n:"Core", p:false}
    ],
    tags: ["pull", "push", "bar", "mobility", "advanced", "BTN"],
    diff: 9,
    str: {suit:true, eff:4},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:3, elbow:3, shoulder:5, neck:4, lowerBack:2, hip:1, knee:0, ankle:0, fingers:2, thoracic:4, si:1, groin:0, foot:0},
    technique: 5,
    mobility: 5,
    strength: 4,
    kcalPerRep: [0.6, 1.0],
    desc: "The transition takes place behind the head rather than in front of the chest, finishing with the bar resting at the back of the neck at the top. Demands exceptional thoracic mobility, shoulder external rotation range, and cervical spine stability. Contraindicated for most athletes — only appropriate for individuals with verified full overhead shoulder mobility and no neck pathology.",
    cues: "Only attempt after a full shoulder mobility pre-screening, keep the neck completely neutral and do not jam the head forward, and progress through partial BTN pull-ups before attempting the full transition.",
    equipment: "Pull-up bar",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 28,
    name: "Pseudo-Planche Muscle-Up | (Bar / Parallettes)",
    alt: "Forward-lean rotated-wrist muscle-up",
    muscles: [
      {n:"Chest", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:true},
      {n:"Back", p:false}
    ],
    tags: ["planche", "push", "bar", "advanced", "wrist", "lean"],
    diff: 10,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:5, elbow:4, shoulder:5, neck:1, lowerBack:3, hip:2, knee:0, ankle:0, fingers:4, thoracic:3, si:1, groin:0, foot:0},
    technique: 5,
    mobility: 5,
    strength: 5,
    kcalPerRep: [0.7, 1.1],
    desc: "The muscle-up is performed with hands rotated outward (fingers pointing backward) in a pseudo-planche position, shifting the pressing load forward into a planche-like angle. Demands exceptional wrist conditioning, shoulder protraction strength, and anterior deltoid loading far beyond any standard muscle-up variant. Wrist health must be deliberately built over months before attempting.",
    cues: "Complete at least 3 months of progressive wrist push-up prep work before attempting. Keep the scapulae protracted throughout and maintain a slight elbow bend — full lockout with this wrist angle increases torque sharply.",
    equipment: "Pull-up bar / parallettes",
    position: "Vertical",
    youtube: "LINK_TODO"
  },

  /* ── EQUIPMENT VARIANTS ─────────────────────────────────────────────────── */

  {
    id: 29,
    name: "Parallel Bar Muscle-Up | (Parallel Bars)",
    alt: "Between-bars / dip-bar muscle-up",
    muscles: [
      {n:"Chest", p:true},
      {n:"Triceps", p:true},
      {n:"Back", p:true},
      {n:"Core", p:false}
    ],
    tags: ["push", "pull", "parallel bars", "dynamic", "neutral"],
    diff: 7,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 3,
    joints: {wrist:2, elbow:3, shoulder:3, neck:1, lowerBack:2, hip:1, knee:0, ankle:0, fingers:2, thoracic:2, si:1, groin:0, foot:0},
    technique: 4,
    mobility: 3,
    strength: 5,
    kcalPerRep: [0.6, 0.9],
    desc: "Performed between parallel dip bars where the body rises from a hanging support position up through the transition into a full dip-support. The fixed neutral grip and stable bar structure reduce wrist rotation demand and make the transition path more predictable compared to an overhead bar. A very practical variant for athletes with wrist limitations.",
    cues: "Drive the hips up between the bars, keep the elbows close to the torso throughout, and lock out completely at the top of the dip press.",
    equipment: "Parallel bars",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 30,
    name: "Low Bar Muscle-Up | (Low Bar / Rack / Smith)",
    alt: "Australian muscle-up / inclined low bar",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Core", p:true},
      {n:"Shoulders", p:false}
    ],
    tags: ["pull", "push", "bar", "horizontal", "bodyweight", "progression"],
    diff: 5,
    str: {suit:true, eff:4},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 2,
    joints: {wrist:2, elbow:3, shoulder:3, neck:1, lowerBack:3, hip:2, knee:1, ankle:0, fingers:2, thoracic:2, si:1, groin:0, foot:0},
    technique: 3,
    mobility: 2,
    strength: 3,
    kcalPerRep: [0.4, 0.7],
    desc: "Performed on a low bar with the body at an inclined angle, feet on the floor for support — similar to a bodyweight row starting position. The body angle substantially lowers the strength threshold, making this a realistic entry-point progression. It trains the transition pattern and the pressing mechanic without the full bodyweight demand of the overhead version.",
    cues: "Keep the body rigid from heel to head throughout, pull the chest all the way to the bar, and complete the press without letting the hips drop or pike.",
    equipment: "Low pull-up bar / barbell in rack / Smith machine bar",
    position: "Horizontal",
    youtube: "LINK_TODO"
  },

  {
    id: 37,
    name: "Band-Assisted Muscle-Up | (Bar)",
    alt: "Elastic band / resistance band muscle-up",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:false}
    ],
    tags: ["assisted", "band", "progression", "bar", "beginner", "learning"],
    diff: 4,
    str: {suit:true, eff:3},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 2,
    joints: {wrist:2, elbow:2, shoulder:3, neck:1, lowerBack:2, hip:1, knee:1, ankle:0, fingers:2, thoracic:2, si:1, groin:0, foot:0},
    technique: 3,
    mobility: 2,
    strength: 3,
    kcalPerRep: [0.3, 0.6],
    desc: "A resistance band is looped over the bar and placed under the feet or hips, reducing effective load across the full range of motion. Assistance is greatest at the bottom of the pull — where the muscle-up is hardest — and tapers as the body rises, giving the band profile a reasonable match to the movement's strength curve. The most widely used real-world tool for learning the muscle-up pattern before achieving bodyweight standard. Sits between the Low Horizontal Bar  and strict bodyweight work as a progression step. Reduce band thickness progressively — thicker → thinner → no band — as strength improves.",
    cues: "Choose the lightest band that still allows complete, well-formed reps — too much assistance eliminates the training stimulus. Track band thickness like a load and reduce it every 2–3 weeks. Do not use a band to chase higher rep counts; use it to access the correct movement pattern under manageable load.",
    equipment: "Pull-up bar + resistance band (loop)",
    position: "Vertical",
    youtube: "LINK_TODO"
  },

  /* ── BONUS COMBOS BUILT ON MUSCLE-UPS ──────────────────────────────────── */

  {
    id: 31,
    name: "Double Muscle-Up | (Bar / Rings)",
    alt: "Touch-and-go muscle-up × 2",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:false}
    ],
    tags: ["pull", "push", "bar", "repeat", "strength endurance"],
    diff: 9,
    str: {suit:true, eff:4},
    vol: {suit:false, eff:3},
    end: {suit:true, eff:4},
    risk: 4,
    joints: {wrist:3, elbow:4, shoulder:4, neck:1, lowerBack:2, hip:1, knee:0, ankle:0, fingers:2, thoracic:2, si:1, groin:0, foot:0},
    technique: 5,
    mobility: 3,
    strength: 5,
    kcalPerRep: [1.2, 1.9],
    desc: "Two full muscle-ups executed consecutively without releasing the bar. The controlled descent from the first rep feeds directly into the pull for the second. The challenge is controlling the negative phase quickly enough to preserve momentum while maintaining technical quality on the second rep. The second rep always reveals exactly where strength and technique are actually limited.",
    cues: "Lower quickly but with control — absorb the bottom position through the shoulder blades, and immediately redirect force upward rather than hanging at the dead hang.",
    equipment: "Pull-up bar / rings",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 32,
    name: "Muscle-Up | Front Lever (Bar)",
    alt: "MU to horizontal front lever hold",
    muscles: [
      {n:"Back", p:true},
      {n:"Core", p:true},
      {n:"Shoulders", p:true},
      {n:"Hip Flexors", p:false}
    ],
    tags: ["pull", "push", "front lever", "bar", "static", "advanced"],
    diff: 10,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:4, elbow:4, shoulder:5, neck:1, lowerBack:3, hip:2, knee:0, ankle:0, fingers:3, thoracic:3, si:2, groin:0, foot:0},
    technique: 5,
    mobility: 4,
    strength: 5,
    kcalPerRep: [0.8, 1.3],
    desc: "A muscle-up followed by a controlled transition into a front lever — body horizontal, arms extended, hanging below the bar. Links the full pulling and pressing demands of the muscle-up to a maximum-difficulty static pulling hold. The transition between the two positions requires precise lat engagement and full-body tension.",
    cues: "After the muscle-up, lower the legs forward and press the lats down hard as the body approaches horizontal — do not bend the elbows and do not let the hips drop.",
    equipment: "Pull-up bar",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 33,
    name: "Muscle-Up | Back Lever (Bar)",
    alt: "MU to back lever hold",
    muscles: [
      {n:"Shoulders", p:true},
      {n:"Chest", p:true},
      {n:"Core", p:true},
      {n:"Back", p:false}
    ],
    tags: ["push", "back lever", "bar", "static", "advanced"],
    diff: 10,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:4, elbow:4, shoulder:5, neck:2, lowerBack:4, hip:2, knee:0, ankle:0, fingers:3, thoracic:4, si:2, groin:0, foot:0},
    technique: 5,
    mobility: 5,
    strength: 5,
    kcalPerRep: [0.7, 1.2],
    desc: "A muscle-up followed by a controlled skin-the-cat transition into a back lever — body horizontal face-down, arms extended behind the torso. Combines the full pulling and pressing cycle with one of the highest-demand shoulder-extension static holds in calisthenics. Thoracic extension mobility is a hard prerequisite.",
    cues: "From the top of the muscle-up, lower the legs behind the bar in a controlled pike, keep the arms straight throughout the rotation, and squeeze every muscle to hold the horizontal position.",
    equipment: "Pull-up bar",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 34,
    name: "Muscle-Up | Handstand (Bar)",
    alt: "Bar MU to bar handstand",
    muscles: [
      {n:"Shoulders", p:true},
      {n:"Core", p:true},
      {n:"Chest", p:true},
      {n:"Back", p:false}
    ],
    tags: ["push", "handstand", "bar", "balance", "advanced"],
    diff: 10,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:5, elbow:3, shoulder:5, neck:2, lowerBack:3, hip:2, knee:0, ankle:0, fingers:4, thoracic:3, si:1, groin:0, foot:0},
    technique: 5,
    mobility: 5,
    strength: 5,
    kcalPerRep: [0.8, 1.3],
    desc: "From the top of the muscle-up, the athlete continues pressing and shifting the weight forward until they arrive in a straight handstand balanced on the bar. Combines explosive pulling and pressing with elite overhead balance and wrist strength. A foundational skill in bar freestyle routines. Requires proficient freestanding handstand ability before taking it to the bar.",
    cues: "Press and lean forward gradually after the muscle-up, keep the elbows locked, engage the core firmly, and use small finger pressure to balance — do not reach for the handstand too aggressively.",
    equipment: "Pull-up bar (ensure clearance above)",
    position: "Vertical / Inverted",
    youtube: "LINK_TODO"
  },
  {
    id: 35,
    name: "Muscle-Up | Negative + Kip (Bar)",
    alt: "Slow down, fast up — negative-kip cycle",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:false}
    ],
    tags: ["pull", "push", "bar", "eccentric", "kipping", "contrast", "volume"],
    diff: 7,
    str: {suit:true, eff:4},
    vol: {suit:false, eff:3},
    end: {suit:true, eff:4},
    risk: 3,
    joints: {wrist:3, elbow:3, shoulder:4, neck:1, lowerBack:2, hip:2, knee:0, ankle:0, fingers:2, thoracic:2, si:1, groin:0, foot:0},
    technique: 4,
    mobility: 3,
    strength: 4,
    kcalPerRep: [0.6, 1.0],
    desc: "A deliberate contrast-training sequence: one slow 5-second negative descent followed immediately by one explosive kipping rep. The eccentric phase loads the muscles under high tension and pre-fatigues the structural tissues; the following kip tests how well explosive power is preserved under fatigue. A highly effective hypertrophy and power-endurance pairing.",
    cues: "Control the negative down completely before setting up the kip — do not rush the transition between the two halves — and reset the swing cleanly before the kipping rep.",
    equipment: "Pull-up bar",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 40,
    name: "Muscle-Up | Skin-the-Cat (Bar)",
    alt: "MU to German hang rotation",
    muscles: [
      {n:"Shoulders", p:true},
      {n:"Back", p:true},
      {n:"Core", p:true},
      {n:"Chest", p:false}
    ],
    tags: ["push", "pull", "skin the cat", "bar", "mobility", "advanced", "rotation"],
    diff: 9,
    str: {suit:true, eff:4},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:4, elbow:4, shoulder:5, neck:2, lowerBack:4, hip:3, knee:1, ankle:0, fingers:3, thoracic:5, si:2, groin:1, foot:0},
    technique: 5,
    mobility: 5,
    strength: 5,
    kcalPerRep: [0.7, 1.2],
    desc: "From the top of a bar muscle-up, the athlete pikes the legs forward and rotates them through the arms until the body hangs below the bar in a German hang — arms fully extended behind the torso, shoulders in deep extension. The rotation is then reversed back to a support position. Unlike the Muscle-Up to Back Lever , which terminates at a horizontal static hold, the skin-the-cat continues through the full rotation arc and demands active control across the entire shoulder extension range without any positional target to absorb the load. Thoracic extension mobility is a hard prerequisite — attempting this with limited thoracic range forces the shoulder joint to compensate.",
    cues: "Rotate slowly with arms straight throughout the descent into the German hang — bending the elbows at this range places the elbow and shoulder in a highly vulnerable position. Reverse out under control. Never drop passively out of the hang at the bottom.",
    equipment: "Pull-up bar (sufficient overhead clearance)",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 41,
    name: "Muscle-Up | Top L-Sit (Bar)",
    alt: "MU to support L-sit",
    muscles: [
      {n:"Core", p:true},
      {n:"Hip Flexors", p:true},
      {n:"Shoulders", p:true},
      {n:"Triceps", p:false}
    ],
    tags: ["core", "l-sit", "bar", "static", "combo", "strength"],
    diff: 9,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 4,
    joints: {wrist:3, elbow:3, shoulder:4, neck:1, lowerBack:3, hip:4, knee:1, ankle:0, fingers:3, thoracic:2, si:2, groin:1, foot:0},
    technique: 5,
    mobility: 4,
    strength: 5,
    kcalPerRep: [0.7, 1.1],
    desc: "A standard muscle-up is completed first; then at the top support, the legs are raised into a strict L-sit — parallel to the floor — and held for 2–5 seconds before descending. Distinct from the L-Sit Muscle-Up , which enters and moves through the L-sit throughout the pull and transition. Here, the muscle-up is completed as a normal rep and the L-sit demand is isolated at the top support. This makes it an effective pairing drill for athletes who have the pull but lack top-end hip flexor control, and a natural progression step between a standard muscle-up and the full L-sit variant.",
    cues: "Complete the transition and press to full lockout before attempting to lift the legs — raising the legs during the press phase defeats the training purpose and usually causes the press to fail. Hold the legs parallel for a full breath before lowering.",
    equipment: "Pull-up bar",
    position: "Vertical",
    youtube: "LINK_TODO"
  },
  {
    id: 42,
    name: "Pull-Up → Muscle-Up → Dip | Chain (Bar)",
    alt: "Three-phase bar vertical chain",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Shoulders", p:true},
      {n:"Triceps", p:true}
    ],
    tags: ["pull", "push", "bar", "chain", "combo", "conditioning", "full-spectrum"],
    diff: 9,
    str: {suit:true, eff:4},
    vol: {suit:false, eff:3},
    end: {suit:true, eff:4},
    risk: 4,
    joints: {wrist:3, elbow:4, shoulder:4, neck:1, lowerBack:2, hip:1, knee:0, ankle:0, fingers:3, thoracic:2, si:1, groin:0, foot:0},
    technique: 5,
    mobility: 3,
    strength: 5,
    kcalPerRep: [1.1, 1.7],
    desc: "A three-movement bar sequence performed without releasing the bar: one strict pull-up → return to a dead hang → explosive muscle-up → one controlled dip at the top → return to dead hang. The chain tests the complete vertical pulling-to-pressing spectrum in a single continuous set, linking three fundamental bar movement patterns. The dead-hang reset between the pull-up and the muscle-up is intentional — it fully eliminates pull-up momentum and forces a fresh initiation for the harder movement, exposing whether the muscle-up is genuinely independent of the pull-up energy.",
    cues: "Dead hang fully after the pull-up before initiating the muscle-up — do not ride the momentum between movements. Keep the dip at the top controlled and deep before returning. Quality of each component matters more than the speed of the chain.",
    equipment: "Pull-up bar",
    position: "Vertical",
    youtube: "LINK_TODO"
  },

  /* ── GROUND-TO-BAR COMBOS ───────────────────────────────────────────────── */

  {
    id: 43,
    name: "Burpee Pull-Up | (Bar)",
    alt: "Floor-to-bar full-body chain",
    muscles: [
      {n:"Chest", p:true},
      {n:"Back", p:true},
      {n:"Legs", p:true},
      {n:"Shoulders", p:false}
    ],
    tags: ["full body", "ground-to-bar", "conditioning", "push", "pull", "plyometric"],
    diff: 5,
    str: {suit:false, eff:3},
    vol: {suit:true, eff:4},
    end: {suit:true, eff:5},
    risk: 3,
    joints: {wrist:2, elbow:2, shoulder:3, neck:1, lowerBack:3, hip:2, knee:3, ankle:2, fingers:1, thoracic:2, si:2, groin:1, foot:2},
    technique: 3,
    mobility: 2,
    strength: 3,
    kcalPerRep: [0.8, 1.3],
    desc: "From standing, drop into a squat, kick feet back, perform a push-up, jump feet forward, then explosively jump up to a pull-up bar and complete one pull-up before returning to the ground. The full cycle covers horizontal pressing, hip hinge, knee drive, explosive hip extension, vertical pulling, and deceleration in a single unbroken rep. One of the most metabolically demanding bodyweight combos per rep and a staple of military conditioning and functional fitness testing.",
    cues: "Pace the push-up — do not collapse to the floor. The jump to the bar should be high and controlled, not a scramble. Lower from the pull-up with straight arms before releasing to land softly.",
    equipment: "Pull-up bar (positioned above jump height)",
    position: "Vertical / Floor",
    youtube: "LINK_TODO"
  },

  /* ── HORIZONTAL PULL-PUSH CHAINS ────────────────────────────────────────── */

  {
    id: 44,
    name: "Inverted Row | Push-Up (Low Bar / Smith / Rings)",
    alt: "Australian row + push-up horizontal chain",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:false}
    ],
    tags: ["pull", "push", "horizontal", "row", "bodyweight", "accessible", "chain"],
    diff: 3,
    str: {suit:true, eff:3},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 2,
    joints: {wrist:2, elbow:2, shoulder:3, neck:1, lowerBack:2, hip:1, knee:0, ankle:0, fingers:1, thoracic:2, si:1, groin:0, foot:1},
    technique: 2,
    mobility: 2,
    strength: 3,
    kcalPerRep: [0.3, 0.6],
    desc: "Lying supine under a low fixed bar, perform an inverted row — pulling the chest to the bar with a rigid body — then lower and shift position to complete a push-up. The two movements cover the horizontal pulling and horizontal pushing patterns in sequence using the same setup. No specialist equipment is required beyond a low bar or Smith machine, making this one of the most accessible full upper-body chains available. Body angle adjusts difficulty for both movements independently.",
    cues: "Keep the body rigid as a plank through both movements. On the row, pull the elbows back — do not let them flare. On the push-up, reset shoulder position before pressing.",
    equipment: "Low bar / Smith machine / rings at chest height",
    position: "Horizontal",
    youtube: "LINK_TODO"
  },
  {
    id: 45,
    name: "Ring Row | Ring Push-Up (Rings)",
    alt: "Horizontal ring pull + ring press chain",
    muscles: [
      {n:"Back", p:true},
      {n:"Chest", p:true},
      {n:"Shoulders", p:true},
      {n:"Core", p:true}
    ],
    tags: ["rings", "pull", "push", "horizontal", "chain", "stability"],
    diff: 6,
    str: {suit:true, eff:4},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 3,
    joints: {wrist:3, elbow:3, shoulder:4, neck:1, lowerBack:2, hip:1, knee:0, ankle:0, fingers:2, thoracic:2, si:1, groin:0, foot:0},
    technique: 4,
    mobility: 2,
    strength: 4,
    kcalPerRep: [0.5, 0.9],
    desc: "Rings version of the horizontal pull-push chain: perform an inclined ring row with feet on the floor, then transition to a ring push-up position and complete a ring push-up. The ring surface adds three-dimensional instability to both the pulling and pressing phases simultaneously — demanding constant rotator cuff activation and grip stabilisation that fixed-bar or floor versions cannot replicate. Difficulty is adjusted via body angle, making this accessible at a wide range of strength levels.",
    cues: "Keep ring path consistent through both movements — they must stay at equal height and travel together. On the push-up, allow the rings to rotate naturally outward at the top to protect the shoulder.",
    equipment: "Gymnastic rings",
    position: "Horizontal / Rings",
    youtube: "LINK_TODO"
  },

  /* ── ISOMETRIC-TO-DYNAMIC COMBOS ────────────────────────────────────────── */

  {
    id: 46,
    name: "FL | Pull-Up (Bar)",
    alt: "Static front lever into vertical pull",
    muscles: [
      {n:"Back", p:true},
      {n:"Core", p:true},
      {n:"Shoulders", p:true},
      {n:"Hip Flexors", p:false}
    ],
    tags: ["front lever", "pull", "bar", "isometric", "dynamic", "advanced"],
    diff: 10,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 5,
    joints: {wrist:3, elbow:4, shoulder:5, neck:1, lowerBack:4, hip:3, knee:0, ankle:0, fingers:3, thoracic:3, si:2, groin:0, foot:0},
    technique: 5,
    mobility: 4,
    strength: 5,
    kcalPerRep: [0.8, 1.3],
    desc: "From a held full front lever — body horizontal, arms extended, core braced — the athlete transitions directly into a vertical pull-up rep without breaking body tension or releasing the bar. The lat and posterior chain engagement of the front lever pre-loads the muscles at peak recruitment before the pull begins, creating a uniquely demanding isometric-to-dynamic transition. A full, held front lever is a hard prerequisite — attempting this with a partial lever substitutes a form problem for a training stimulus.",
    cues: "Hold the front lever for at least 2 seconds before initiating the pull. Keep the hips from dropping during the transition and maintain body tension all the way to the top of the pull.",
    equipment: "Pull-up bar",
    position: "Vertical",
    youtube: "LINK_TODO"
  },

  /* ── HANGING CORE CHAINS ─────────────────────────────────────────────────── */

  {
    id: 47,
    name: "Toes-to-Bar | L-Sit Hold (Bar)",
    alt: "Dynamic TTB into static compression hold",
    muscles: [
      {n:"Core", p:true},
      {n:"Hip Flexors", p:true},
      {n:"Lats", p:true},
      {n:"Shoulders", p:false}
    ],
    tags: ["core", "hanging", "l-sit", "dynamic", "static", "chain", "bar"],
    diff: 7,
    str: {suit:true, eff:4},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:2},
    risk: 3,
    joints: {wrist:2, elbow:2, shoulder:3, neck:1, lowerBack:3, hip:4, knee:1, ankle:0, fingers:2, thoracic:2, si:2, groin:2, foot:0},
    technique: 4,
    mobility: 4,
    strength: 4,
    kcalPerRep: [0.4, 0.7],
    desc: "From a dead hang, an explosive toes-to-bar rep is immediately controlled on the descent into a held L-sit — legs parallel to the floor — and held for 2–5 seconds before lowering to the hang. The combination taxes both hip flexor power (the TTB) and hip flexor endurance under fatigue (the hold) in the same rep cycle, while the back swing control required to stabilise the L-sit without momentum is a significant core challenge in its own right. A practical companion drill to the L-Sit Muscle-Up.",
    cues: "Control the descent from the TTB — do not let the legs swing through. Intercept the legs at horizontal and squeeze hard to hold the L-sit before fatigue breaks the position.",
    equipment: "Pull-up bar",
    position: "Vertical",
    youtube: "LINK_TODO"
  },

  /* ── PARALLEL BAR FLOWS ──────────────────────────────────────────────────── */

  {
    id: 48,
    name: "L-Sit | Dip (Parallel Bars)",
    alt: "Bars L-sit static-to-press flow",
    muscles: [
      {n:"Core", p:true},
      {n:"Triceps", p:true},
      {n:"Chest", p:true},
      {n:"Hip Flexors", p:false}
    ],
    tags: ["parallel bars", "l-sit", "dip", "combo", "core", "static", "dynamic"],
    diff: 9,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 4,
    joints: {wrist:3, elbow:4, shoulder:4, neck:1, lowerBack:3, hip:4, knee:1, ankle:0, fingers:2, thoracic:2, si:2, groin:1, foot:0},
    technique: 5,
    mobility: 4,
    strength: 5,
    kcalPerRep: [0.6, 1.0],
    desc: "Hold a strict L-sit on parallel bars, then — without dropping the legs — perform a full dip and return to the L-sit position. The pre-loaded core compression makes the dip considerably harder than a standard rep: the hip flexors are actively fatiguing while the triceps and chest must still complete the full press. The legs dropping during the dip is the most common failure point and signals that either hip flexor endurance or dip strength is the limiting factor, making this an effective diagnostic pairing.",
    cues: "Establish a solid L-sit hold before beginning any dip. Keep the legs locked straight and parallel throughout the press — if they start to drop, terminate the rep rather than continuing with compromised position.",
    equipment: "Parallel bars",
    position: "Vertical",
    youtube: "LINK_TODO"
  },

  /* ── SKILL TRANSITION COMBOS ─────────────────────────────────────────────── */

  {
    id: 49,
    name: "L-Sit | Press to Handstand (Parallettes)",
    alt: "Compression press-up / L-press to HS",
    muscles: [
      {n:"Shoulders", p:true},
      {n:"Core", p:true},
      {n:"Hip Flexors", p:true},
      {n:"Triceps", p:false}
    ],
    tags: ["handstand", "l-sit", "press", "parallettes", "skill", "advanced", "gymnastics"],
    diff: 10,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:1},
    end: {suit:false, eff:1},
    risk: 4,
    joints: {wrist:5, elbow:3, shoulder:5, neck:2, lowerBack:3, hip:4, knee:0, ankle:0, fingers:4, thoracic:3, si:2, groin:1, foot:0},
    technique: 5,
    mobility: 5,
    strength: 5,
    kcalPerRep: [0.7, 1.1],
    desc: "From an L-sit on parallettes, the athlete presses the legs upward — through a tuck, straddle, or straight-body path — until the body arrives in a full freestanding handstand. Requires simultaneous hip flexor strength to maintain leg position, anterior core compression to redirect the body's centre of mass, shoulder pressing power to drive the inversion, and handstand balance to stabilise at the top. A benchmark skill in gymnastics strength training and one of the most technically demanding transitions in accessible bodyweight work.",
    cues: "Lean the shoulders slightly forward over the wrists before pressing — the press must go forward before it can go up. Open the hips progressively rather than kicking; the slower the press, the more skill it demonstrates. A freestanding handstand must be solid before attempting this.",
    equipment: "Parallettes",
    position: "Elevated / Inverted",
    youtube: "LINK_TODO"
  },
  {
    id: 50,
    name: "Handstand Push-Up | Pike Push-Up (Wall / Parallettes)",
    alt: "Handstand press to pike press chain",
    muscles: [
      {n:"Shoulders", p:true},
      {n:"Triceps", p:true},
      {n:"Core", p:true},
      {n:"Upper Chest", p:false}
    ],
    tags: ["push", "handstand", "pike", "overhead", "chain", "shoulders"],
    diff: 8,
    str: {suit:true, eff:5},
    vol: {suit:false, eff:2},
    end: {suit:false, eff:1},
    risk: 4,
    joints: {wrist:4, elbow:3, shoulder:5, neck:2, lowerBack:2, hip:2, knee:0, ankle:0, fingers:3, thoracic:3, si:1, groin:0, foot:0},
    technique: 5,
    mobility: 4,
    strength: 5,
    kcalPerRep: [0.5, 0.9],
    desc: "One handstand push-up (wall-supported or freestanding) is followed by a controlled descent out of the handstand into a pike push-up position, where one pike press rep is completed, before returning to the handstand. The chain links two overhead pressing angles — near-vertical in the HSPU, and approximately 45–60 degrees in the pike press — loading the shoulder through a continuously shifting arc in a single set. The controlled transition between the two positions is itself a significant shoulder stability challenge.",
    cues: "Lower out of the handstand into the pike slowly — the transition is not a fall. In the pike, keep the hips high and drive the crown of the head toward the floor. Return to handstand under control before attempting another rep.",
    equipment: "Wall / parallettes (for HSPU), floor (for pike)",
    position: "Inverted / Elevated",
    youtube: "LINK_TODO"
  },
  {
    id: 51,
    name: "Burpees | Combo (Floor)",
    alt: "Standard push-up + jump",
    muscles: [
      {n:"Chest", p:true},
      {n:"Legs", p:true},
      {n:"Core", p:true},
      {n:"Shoulders", p:false}
    ],
    tags: ["push", "core", "full-body", "cardio", "plyometric"],
    diff: 4.5,
    str: {suit:true, eff:3},
    vol: {suit:true, eff:4},
    end: {suit:true, eff:5},
    risk: 3,
    joints: {wrist:2, elbow:3, shoulder:3, neck:1, lowerBack:2, hip:3, knee:3, ankle:2, fingers:1, thoracic:1, si:1, groin:1, foot:1},
    technique: 3,
    mobility: 2,
    strength: 3,
    kcalPerRep: [0.4, 0.7],
    desc: "A fast bodyweight combination that pairs a standard push-up with an explosive jump. Burpees Combo builds conditioning, full-body power and muscular endurance while training the chest, legs, core and shoulders in a single rep.",
    cues: "Keep the plank position solid during the push-up, land softly on the jump, and reset the shoulders before the next rep. Breathe steadily and move with controlled rhythm.",
    equipment: "None",
    position: "Standing / Prone",
    youtube: "LINK_TODO"
  }

];
