/* ─────────────────────────────────────────────────────────────────────────
 * NAMING RULE
 * Format: [modifier] [family] | [extra modifier] (equipment)
 *
 * - Modifiers always go before the family name.
 * - Base variation: use "Standard" or "Strict".
 * - Omit equipment if it's the default (floor for push-ups, bar for pull-ups).
 *   Only include it when non-default.
 *
 * ✓ One Arm Push-Up | Fingertips (bar)
 * ✗ Push-Up | One Arm
 *
 * ─────────────────────────────────────────────────────────────────────────
 *
 * DIFFICULTY REFERENCE (scale 1–10)
 * 1. Standard Push-Up     — 3.0
 * 2. Archer Push-Up       — 6.3
 * 3. Tuck Planche         — 6.0
 * 4. Chin-Up              — 3.8
 * 5. Archer Pull-Up       — 6.5
 * 6. Straddle Planche     — 8.5
 *
 * ─────────────────────────────────────────────────────────────────────────
 *
 * HALL OF FAME (HoF)
 * Do not mark any move as HoF unless it is fully achieved.
 * If uncertain, ask before tagging.
 * ───────────────────────────────────────────────────────────────────────── */

/* pushup-knee.js — extends the global pushups[] declared in pushup-standard.js */

pushups.push(

{
  id: 27,
  name: "Knee Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: true },
    { n: "Shoulders", p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "triceps", "shoulders", "core"],
  diff: 1.0,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.20, 0.26],
  desc: "Standard push-up performed with the knees on the floor instead of the toes, shortening the lever arm and cutting the loaded fraction of bodyweight roughly in half. Same pressing pattern through chest, triceps, and anterior shoulder as the full Push-Up, making this the standard entry point for beginners building toward it.",
  cues: "Hands slightly wider than shoulder-width, knees down with hips in line with the shoulders — don't let the hips sag or pike up. Lower the chest toward the floor under control, then press back to full elbow extension. Keep a straight line from knees to head throughout.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 28,
  name: "Knee Push-Up | Wide",
  sidequestKey: "Knee Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: false },
    { n: "Triceps",   p: false },
  ],
  tags: ["chest", "shoulders", "triceps"],
  diff: 1.1,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.22, 0.29],
  desc: "Knee Push-Up with hands 1.5–2× shoulder-width apart. The wider placement increases the stretch on the sternal head of the pectoralis major and shifts the elbow path outward, reducing tricep contribution relative to the standard knee variation.",
  cues: "Set up as a standard Knee Push-Up but spread the hands wider than shoulder-width. Elbows flare outward as you lower — keep the descent controlled. Press back while keeping the hips stable and square.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 29,
  name: "Knee Push-Up | Narrow",
  sidequestKey: "Knee Push-Up",
  alt: null,
  muscles: [
    { n: "Triceps",   p: true },
    { n: "Chest",     p: false },
    { n: "Shoulders", p: false },
  ],
  tags: ["triceps", "chest", "shoulders"],
  diff: 1.2,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 2, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.22, 0.29],
  desc: "Knee Push-Up with hands close together beneath the chest, thumbs nearly touching. The narrowed grip shortens the moment arm at the shoulder and shifts the load toward triceps-dominant elbow extension rather than horizontal adduction.",
  cues: "Bring the hands in until thumbs are almost touching beneath the chest. Keep elbows tracking back along the ribs rather than flaring out. Lower under control and press to a full lockout.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 30,
  name: "Knee Push-Up | Diamond",
  sidequestKey: "Knee Push-Up",
  alt: null,
  muscles: [
    { n: "Triceps",   p: true },
    { n: "Chest",     p: true },
    { n: "Shoulders", p: false },
  ],
  tags: ["triceps", "chest", "shoulders"],
  diff: 1.4,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 2, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.25, 0.32],
  desc: "Knee Push-Up with the index fingers and thumbs touching to form a diamond beneath the sternum. The extreme grip narrowing pushes elbow extension demand and wrist loading past the standard narrow variation, concentrating the work almost entirely on the triceps.",
  cues: "Form a diamond shape with thumbs and index fingers under the chest. Keep elbows tucked close to the ribs as you lower — they should brush the sides, not flare. Press through the diamond back to full extension.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 31,
  name: "Knee Push-Up | Staggered",
  sidequestKey: "Knee Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 1.5,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.22, 0.29],
  desc: "Knee Push-Up with one hand at standard width and the other shifted 15–20 cm forward or back, creating an asymmetric pressing position. The offset hand takes a measurably greater share of the load each rep, adding a mild unilateral strength and anti-rotation demand on top of the base movement.",
  cues: "Set up as a standard Knee Push-Up, then slide one hand forward by a hand-length. Lower evenly — both elbows bend, but the rear hand drives most of the press. Switch which hand is forward each set.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 52,
  name: "Knee Push-Up | Straddle",
  sidequestKey: "Knee Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: true },
    { n: "Shoulders", p: false },
  ],
  tags: ["chest", "triceps", "shoulders"],
  diff: 0.9,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.19, 0.25],
  desc: "Knee Push-Up with the knees spread wide apart instead of together, widening the base of support. The broader stance lowers the anti-rotation demand on the core compared to the standard knees-together setup, making this the most stable and beginner-friendly stance in the family.",
  cues: "Knees down and spread wide apart, hands at standard shoulder-width. Lower the chest with control — the wide knee base should feel notably more stable than knees together. Press back to full extension.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 53,
  name: "Knee Push-Up | One Leg",
  sidequestKey: "Knee Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: false },
    { n: "Triceps",   p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 1.3,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 1, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.21, 0.27],
  desc: "Knee Push-Up performed with one knee lifted off the floor, leaving a single knee as the rear contact point. Removing a contact point forces the core and hip stabilisers to resist rotation and lateral tilt throughout the set, while the pressing mechanics stay unchanged from the standard knee variation.",
  cues: "Set up as a standard Knee Push-Up, then lift one knee a few inches off the floor. Brace the core and keep the hips level — don't let the pelvis rotate toward the lifted side. Switch the raised knee each set.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 32,
  name: "Knee Push-Up | T",
  sidequestKey: "Knee Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Biceps",    p: false },
  ],
  tags: ["chest", "shoulders", "biceps"],
  diff: 1.7,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.25, 0.32],
  desc: "Knee Push-Up with the arms extended out to the sides at shoulder height, forming a T with the torso. The wide, fly-style elbow path lengthens the pecs at the bottom and shifts a much greater share of the load onto the anterior deltoid than the standard hand placement, even with the reduced knee-based lever.",
  cues: "Hands wide, arms extended out to the sides at shoulder height — body forms a T. Bend the elbows outward as the chest lowers, mimicking a fly motion. Press back by squeezing the pecs together rather than driving the elbows inward.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},


{
  id: 44,
  name: "Knee Push-Up | Knuckle",
  sidequestKey: "Knee Push-Up",
  alt: null,
  pathTag: "knuckle",
  pathNode: true,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: true },
    { n: "Shoulders", p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "triceps", "shoulders", "core"],
  diff: 1.3,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 0, elbow: 1, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 2, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.20, 0.26],
  desc: "Knee push-up performed on the proximal knuckle row of a loosely closed fist, placing the wrist in a neutral position. Eliminating wrist extension makes this the standard rehabilitation and introductory alternative for people with wrist pain or limited dorsiflexion range — the pressing pattern and load are otherwise identical to the standard Knee Push-Up.",
  cues: "Make a loose fist and place the knuckle row on the floor, wrist straight. Knees down, hips level. Perform the rep exactly as a standard Knee Push-Up — the only change is the contact surface. Keep the fist consistently aligned; don't let the wrist roll inward.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 45,
  name: "Knee Push-Up | Fist",
  sidequestKey: "Knee Push-Up",
  alt: null,
  pathTag: "knuckle",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: true },
    { n: "Shoulders", p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "triceps", "shoulders", "core"],
  diff: 1.5,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 0, elbow: 1, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 2, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.20, 0.26],
  desc: "Knee push-up on a fully closed fist, contacting the floor with the flat of the knuckles and the side of the index finger metacarpal. The tightly closed grip demands sustained forearm tension to keep the fist stable throughout the rep, adding a low-level grip conditioning stimulus absent in the knuckle variant. Wrist remains fully neutral — this is the more stable of the two closed-hand variations.",
  cues: "Close the fist tightly and press the flat knuckle surface into the floor. Wrist absolutely straight — no bend in either direction. Knees down. Grip hard throughout the set; a loosening fist is the first sign of fatigue. Otherwise identical to the standard Knee Push-Up.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 48,
  name: "Knee Push-Up | Archer",
  sidequestKey: "Knee Push-Up",
  alt: null,
  pathTag: "one-arm",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 1.8,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.22, 0.29],
  desc: "Knee push-up with one arm bending to lower the chest toward that side while the other extends straight to the side as a guide with minimal load. The bending arm handles the substantial majority of the press, creating a pronounced unilateral stimulus. The knee position reduces total load enough that the technique — weight shift, elbow path, and lateral control — becomes the primary focus rather than raw strength.",
  cues: "Hands wide, knees down. Shift weight toward one side and bend that elbow to lower the chest. The straight arm stays extended but barely loaded — it guides, not drives. Press back through the bent arm and shift to the other side. Alternate each rep or each set.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 49,
  name: "Knee Push-Up | Typewriter",
  sidequestKey: null,
  alt: null,
  pathTag: "one-arm",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 2.2,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.22, 0.29],
  desc: "Knee push-up with hands wide; lower to one side, then slide the body laterally across the bottom position until the loaded and extended arms switch — both hands stay on the floor throughout. Each full pass approximates one-arm intensity at end range on the pressing side, while demanding continuous scapular and core control across the sweep. The knee lever makes the lateral slide mechanically accessible without the raw strength of the full floor version.",
  cues: "Start wide and lower to one side. Without coming back up, slide the body laterally in one fluid motion until the arms invert — what was bent is now extended and vice versa. Maintain floor contact with both hands throughout. Keep the hips level; don't let them rise or twist during the sweep.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 34,
  name: "Knee Push-Up | Fingertip",
  alt: null,
  pathTag: "fingertip",
  pathNode: true,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: true },
    { n: "Shoulders", p: true },
    { n: "Forearms",  p: false },
  ],
  tags: ["chest", "triceps", "shoulders", "forearms"],
  diff: 2.0,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 2, fingers: 2, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.22, 0.29],
  desc: "Knee push-up performed on all five fingertips rather than a flat palm. The shortened lever keeps absolute fingertip compressive load lower than the full floor equivalent, making this the standard entry point for building flexor tendon and lumbrical resilience in a horizontal pressing pattern. Wrist extension demand drops significantly compared to floor fingertip work.",
  cues: "Knees down, hips in line with shoulders. Spread all five fingertips and lift the palms clear of the floor — only fingertips contact the surface. Lower with full control; stop immediately if a joint produces sharp pain rather than the expected tendon tension.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 35,
  name: "Knee Push-Up | 4-Finger",
  sidequestKey: "Knee Push-Up | Fingertip",
  alt: null,
  pathTag: "fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: true },
    { n: "Shoulders", p: true },
    { n: "Forearms",  p: false },
  ],
  tags: ["chest", "triceps", "shoulders", "forearms"],
  diff: 2.2,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 2, fingers: 3, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.22, 0.29],
  desc: "Knee push-up on four fingertips with the pinky removed from contact. Concentrating load across one fewer digit meaningfully increases the per-finger tendon stress relative to the all-fingertip variant — the absolute pressing load remains modest, so this is primarily a tendon conditioning step.",
  cues: "Tuck the pinky away before placing hands. Four fingertips on the floor, palms clear. Lower deliberately — tendon tissue adapts more slowly than muscle, so rep speed should be controlled and volume conservative.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 36,
  name: "Knee Push-Up | 3-Finger",
  sidequestKey: "Knee Push-Up | Fingertip",
  alt: null,
  pathTag: "fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: true },
    { n: "Shoulders", p: true },
    { n: "Forearms",  p: false },
  ],
  tags: ["chest", "triceps", "shoulders", "forearms"],
  diff: 2.5,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: false, eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 2, fingers: 3, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.22, 0.29],
  desc: "Knee push-up on the index, middle, and ring fingers only. Reducing to three digits per hand increases per-finger flexor tendon load noticeably — this begins to genuinely stress the proximal interphalangeal joints even with the reduced knee-lever. Training frequency should be low and rest days between sessions mandatory.",
  cues: "Index, middle, and ring finger only — pinky and little finger tucked. Palms completely off the floor. Lower under full control. This is tendon work first; do not push through any finger joint discomfort.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 51,
  name: "Knee Push-Up | Deficit",
  sidequestKey: "Knee Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
  ],
  tags: ["chest", "shoulders", "triceps"],
  diff: 1.6,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 2,
  technique: 1,
  kcalPerRep: [0.23, 0.30],
  desc: "Knee Push-Up with the hands elevated on blocks or low parallettes, allowing the chest to drop below hand level. The deeper ROM increases the stretch loading on the pecs and anterior shoulder beyond the floor-level knee variation, while the knee-based lever keeps the added difficulty modest.",
  cues: "Set hands on two stable blocks or low parallettes, shoulder-width apart. Knees down, hips level. Lower the chest below hand height, feeling the deeper stretch, then press back to full extension without letting the elbows flare excessively.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 54,
  name: "Knee Push-Up | Explosive",
  sidequestKey: "Knee Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
  ],
  tags: ["chest", "shoulders", "triceps", "power"],
  diff: 1.5,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 2, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.30, 0.39],
  desc: "Standard Knee Push-Up performed with a maximal-speed concentric, hands briefly leaving the floor at the top of each rep. The shortened knee lever keeps landing forces low, making this the accessible entry point into plyometric pressing before progressing to full floor explosive variants.",
  cues: "Knees down, lower under control, then drive upward as explosively as possible so the hands clear the floor. Land with soft, slightly bent elbows to absorb impact before sinking into the next rep. Keep the hips from popping upward on the drive.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 55,
  name: "Knee Push-Up | Clap",
  sidequestKey: "Knee Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
  ],
  tags: ["chest", "shoulders", "triceps", "power"],
  diff: 1.7,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 2, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.32, 0.41],
  desc: "Explosive Knee Push-Up with enough airtime generated to clap the hands together before catching the floor again. Demands measurably more power output than the non-clap explosive version, since both hands must clear and the catch timing must stay controlled despite the reduced knee-tier load.",
  cues: "Knees down, drive off the floor with maximum force. Clap the hands together at chest height while airborne, then return them to the floor before contact. Catch with soft elbows, never locked, and reset hip position before the next rep.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 56,
  name: "Knee Push-Up | Negative",
  sidequestKey: "Knee Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: true },
    { n: "Shoulders", p: false },
  ],
  tags: ["chest", "triceps", "shoulders"],
  diff: 0.8,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.21, 0.27],
  desc: "Knee Push-Up performed with a 3–5 second eccentric only, no drive on the concentric — reset at the top between reps. Extending time under tension on the lowering phase builds control and eccentric strength ahead of the standard tempo, without adding any new joint demand versus the base movement.",
  cues: "Knees down, lower the chest over a full 3–5 second count, resisting the descent the entire way. Either press back up normally or reset from the top — the eccentric is the trained portion. Keep the tempo consistent rep to rep rather than rushing the final inches.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 57,
  name: "Knee Push-Up | Pause",
  sidequestKey: "Knee Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: false },
    { n: "Shoulders", p: false },
  ],
  tags: ["chest", "triceps", "shoulders"],
  diff: 1.3,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.20, 0.26],
  desc: "Knee Push-Up with a dead-stop pause at the bottom position before pressing back up, removing the elastic rebound of the standard tempo. The momentary hold makes the concentric noticeably harder to initiate despite the unchanged knee-tier load, building strength out of the weakest point in the range.",
  cues: "Lower under control and stop completely at the bottom, chest just off the floor — no bounce. Hold for one to two full seconds, staying tight through the core, then press back up from a dead stop. Reset fully on every rep.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 58,
  name: "Knee Push-Up | (Bar)",
  sidequestKey: "Knee Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
  ],
  tags: ["chest", "shoulders", "triceps"],
  diff: 1.1,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.21, 0.27],
  desc: "Knee Push-Up performed gripping a pair of low parallel bars or a push-up bar set, keeping the wrists in a neutral position instead of full extension. The neutral grip slightly reduces wrist stress versus the flat-floor version, with only a minor ROM increase and no real change to the pressing difficulty.",
  cues: "Set the bars at shoulder-width, knees down on the floor between or behind them. Grip neutrally and lower with control — the wrists stay straight throughout. Press back to full extension, keeping the same hip line as a standard Knee Push-Up.",
  equipment: "Push-Up Bars",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 59,
  name: "Knee Push-Up | (Parallettes)",
  sidequestKey: "Knee Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
  ],
  tags: ["chest", "shoulders", "triceps"],
  diff: 1.2,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 2,
  technique: 1,
  kcalPerRep: [0.23, 0.30],
  desc: "Knee Push-Up performed on parallettes, combining a neutral grip with the maximum ROM the knee-tier lever allows. As with the floor Push-Up, the deeper stretch on the pecs and shoulders outweighs the wrist-angle benefit, making this slightly harder than the plain Deficit version despite the more comfortable grip.",
  cues: "Set parallettes at shoulder-width, knees down on the floor between them. Lower the chest well below hand height, feeling the deep stretch through the pecs and front shoulder. Press back to full extension without letting the hips sag.",
  equipment: "Parallettes",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 60,
  name: "Knee Push-Up | (Rings)",
  sidequestKey: null,
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 2.3,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 2, shoulder: 2, neck: 0, lowerBack: 2,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 2,
  technique: 3,
  kcalPerRep: [0.24, 0.31],
  desc: "Knee Push-Up performed with hands gripping a pair of gymnastic rings, adding full three-dimensional rotational instability on top of the knee-tier load. The rings must be actively stabilized through the entire rep — turning out at the bottom and squeezing in at the top — which adds meaningful technical demand even though the raw pressing load stays low.",
  cues: "Set the rings at a height that lets the knees rest on the floor with arms extended. Knees down, grip the rings firmly and turn them out slightly as you lower. Press back to full extension while actively rolling the rings inward to stay stable — don't let them swing.",
  equipment: "Rings",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 61,
  name: "Knee Push-Up | (TRX)",
  sidequestKey: "Knee Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 1.8,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.22, 0.29],
  desc: "Knee Push-Up performed gripping a pair of suspension trainer handles, adding light instability on top of the knee-tier load. The straps drift more than a fixed surface but far less than rings, giving a mild stabilization demand suited as a stepping stone before progressing to ring-based knee work.",
  cues: "Set the straps to hover just above floor height with handles level. Knees down, grip the handles and lower with control, keeping them from swinging side to side. Press back to full extension while resisting any drift in the straps.",
  equipment: "TRX",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 46,
  name: "Knee Push-Up | One Arm, Knuckle",
  sidequestKey: null,
  alt: null,
  pathTag: "knuckle",
  pathNode: true,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 4.6,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 0, elbow: 2, shoulder: 2, neck: 0, lowerBack: 2,
            knee: 2, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.26, 0.33],
  desc: "One-arm knee push-up performed on the proximal knuckle row, keeping the wrist neutral under unilateral load. The reduced base of support from a single knuckle contact point adds a lateral balance demand on top of the anti-rotation requirement — the contact surface is meaningfully narrower than a flat palm, and any wrist deviation directly destabilises the press.",
  cues: "Loose fist, knuckle row on the floor, wrist straight. One arm only, other hand behind the back. The narrow contact makes lateral balance a real factor — brace the shoulder hard and keep the fist aligned before each rep. Do not let the wrist angle in or out under load.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 47,
  name: "Knee Push-Up | One Arm, Fist",
  sidequestKey: null,
  alt: null,
  pathTag: "knuckle",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 4.65,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 0, elbow: 2, shoulder: 2, neck: 0, lowerBack: 2,
            knee: 2, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.26, 0.33],
  desc: "One-arm knee push-up on a fully closed fist. The tight grip demands sustained forearm co-contraction to maintain fist rigidity while simultaneously managing anti-rotation under unilateral pressing load — two concurrent stabilisation tasks. Slightly harder than the knuckle variant because fist integrity must be actively maintained throughout every rep.",
  cues: "Close the fist tightly before taking the position — grip should be pre-set, not adjusted mid-rep. Wrist straight. One arm, other hand away. Brace the core against rotation and keep the fist rigid from start to finish. If the grip loosens, the set is over.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 50,
  name: "Knee Push-Up | One Arm",
  sidequestKey: null,
  alt: null,
  pathTag: "one-arm",
  pathNode: true,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 4.5,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 2, shoulder: 2, neck: 0, lowerBack: 2,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.26, 0.33],
  desc: "Push-up performed with one hand on the floor and the other held behind the back, knees down. The shortened knee lever cuts total load substantially, but the unilateral press still demands meaningful anti-rotation control through the shoulder girdle, lowerback, and core — the bilateral stability of the knee position is immediately offset by removing one arm. The standard stepping stone between Knee Push-Up and full One-Arm Push-Up.",
  cues: "Centre one hand under the chest, knees down, hips level. Place the free hand firmly on the lower back — not on the floor. Brace hard against rotation before the descent. Lower the chest toward the floor and press back to full extension. The body should not twist or the hip on the working side should not hike.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 37,
  name: "Knee Push-Up | 2-Finger",
  sidequestKey: null,
  alt: null,
  pathTag: "fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: true },
    { n: "Shoulders", p: true },
    { n: "Forearms",  p: false },
  ],
  tags: ["chest", "triceps", "shoulders", "forearms"],
  diff: 4.2,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 2, fingers: 4, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.22, 0.29],
  desc: "Knee push-up on the index and middle fingers of each hand. Halving the digit count doubles the per-finger compressive and shear load at the PIP joints — even the reduced bodyweight fraction from the knee lever makes this a genuinely elite-tier tendon demand. Only practitioners with substantial long-term finger conditioning history should attempt volume here.",
  cues: "Index and middle finger only, remaining fingers fully off the floor. Knees down. Every rep is deliberate — treat each one as a maximum tendon stimulus. Two to four reps per session is ample; rest the fingers for several days before repeating.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 39,
  name: "Knee Push-Up | One Arm, Fingertip",
  sidequestKey: null,
  alt: null,
  pathTag: "one-arm-fingertip",
  pathNode: true,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Forearms",  p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms", "core"],
  diff: 4.7,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 2, shoulder: 2, neck: 0, lowerBack: 2,
            knee: 2, fingers: 2, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.26, 0.33],
  desc: "One-arm knee push-up performed on all five fingertips of the working hand. The reduced lever from the knee position makes unilateral pressing manageable, but routing the entire press through five fingertips introduces meaningful flexor tendon stress alongside the elevated shoulder and anti-rotation demand. Unilateral load and finger loading compound directly here, on top of the wrist and lower-back stress already carried by the One Arm base.",
  cues: "Knees down, hips square. Working hand on five fingertips only, palm off the floor. Other hand behind the back or resting on the hip. Brace the core before each rep — rotation is the first thing to fail. Lower slowly; the shoulder and fingers both need time under controlled load.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 40,
  name: "Knee Push-Up | One Arm, 4-Finger",
  sidequestKey: null,
  alt: null,
  pathTag: "one-arm-fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Forearms",  p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms", "core"],
  diff: 5.0,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 2, shoulder: 2, neck: 0, lowerBack: 2,
            knee: 2, fingers: 3, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.26, 0.33],
  desc: "One-arm knee push-up on four fingertips with the pinky removed. Removing one digit concentrates the full unilateral pressing load across four fingers, adding a meaningful tendon-load step above the all-fingertip one-arm variant. Anti-rotation demand remains the same; the increase here is almost entirely finger-tendon specific.",
  cues: "Pinky off the floor, four fingertips bearing load. One arm only, other hand away from the ground. Lock in anti-rotation before descending. Reps should be few and deliberate — this is a tendon drill that also happens to be a pressing exercise.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 41,
  name: "Knee Push-Up | One Arm, 3-Finger",
  sidequestKey: null,
  alt: null,
  pathTag: "one-arm-fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Forearms",  p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms", "core"],
  diff: 5.3,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 2, shoulder: 2, neck: 0, lowerBack: 2,
            knee: 2, fingers: 3, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.26, 0.33],
  desc: "One-arm knee push-up on three fingertips — index, middle, and ring. At this combination the per-finger flexor tendon stress is genuinely extreme, even with the knee lever reducing absolute load. This movement sits at the upper edge of practical knee-family work; most trainees capable of this have little reason to remain on knees.",
  cues: "Three fingertips only. One arm. Knees down, hips absolutely square. There is no room for slop here — brace everything before each rep. Treat as maximum-effort tendon work: two or three reps per set at most.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 38,
  name: "Knee Push-Up | 1-Finger",
  sidequestKey: null,
  alt: null,
  pathTag: "fingertip",
  pathNode: true,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: true },
    { n: "Shoulders", p: true },
    { n: "Forearms",  p: false },
  ],
  tags: ["chest", "triceps", "shoulders", "forearms"],
  diff: 5.5,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 2, fingers: 5, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.22, 0.29],
  desc: "Knee push-up with a single index finger per hand bearing the entire pressing load. Even with the knee lever reducing absolute force, routing a bilateral floor press through one digit each is an extraordinary per-finger tendon demand — the knee position is what keeps this outside the true Pantheon. Documented examples are very rare; this requires years of structured finger conditioning, not just strength.",
  cues: "One index finger per hand, pointing straight forward, palms and all other digits completely off the floor. Knees down, hips level. A single controlled rep is sufficient stimulus per set. Do not train this more than once or twice a week — tendon recovery operates on a different timeline than muscle.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 42,
  name: "Knee Push-Up | One Arm, 2-Finger",
  sidequestKey: null,
  alt: null,
  pathTag: "one-arm-fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Forearms",  p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms", "core"],
  diff: 5.8,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 2, shoulder: 2, neck: 0, lowerBack: 2,
            knee: 2, fingers: 4, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 4,
  kcalPerRep: [0.26, 0.33],
  desc: "One-arm knee push-up on two fingertips — index and middle. Two digits of one hand bear the unilateral pressing load; the per-finger compressive and shear force at the proximal interphalangeal joints is at the outer boundary of what connective tissue can safely sustain in a horizontal press, even with the knee lever. Practitioners at this level are extremely rare.",
  cues: "Index and middle finger only, one arm. Knees down, body as square as possible. A single full-range rep with clean control is the training unit. Rest the fingers for multiple days before repeating. Any sharp joint discomfort is a hard stop.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 43,
  name: "Knee Push-Up | One Arm, 1-Finger",
  sidequestKey: null,
  alt: null,
  pathTag: "one-arm-fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Forearms",  p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms", "core"],
  diff: 7.0,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 2, shoulder: 3, neck: 0, lowerBack: 2,
            knee: 2, fingers: 5, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 4,
  kcalPerRep: [0.26, 0.33],
  desc: "One-arm knee push-up on a single index finger. The knee lever is the only reason this sits below the floor-based equivalent — a complete unilateral horizontal press routed through one digit demands exceptional connective tissue integrity regardless of bodyweight fraction. Verifiably achieved by a vanishingly small number of practitioners worldwide.",
  cues: "One index finger centred under the shoulder, all other digits and the palm off the floor. One arm, other hand completely away. Knees down, entire body braced. One clean rep is the standard — do not train this more than once a week and treat any finger joint tenderness as a mandatory rest signal.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

);
