/* pushup-decline.js — extends the global pushups[] declared in pushup-standard.js */

pushups.push(

{
  id: 86,
  name: "Decline Push-Up | Knee, Wide",
  sidequestKey: "Decline Push-Up | Knee",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
  ],
  tags: ["chest", "shoulders", "triceps"],
  diff: 3.4,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.27, 0.34],
  desc: "Decline Knee Push-Up with hands 1.5â€“2Ã— shoulder-width apart. The wider grip adds even more stretch loading to the upper chest and front shoulder on top of the decline's already increased demand at the bottom of each rep.",
  cues: "Feet up on the step or bench, knees down. Spread the hands wider than shoulder-width. Elbows flare outward as you lower â€” control the descent given the added decline load. Press back without letting the elbows collapse inward.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 90,
  name: "Decline Push-Up | Knee, Straddle",
  sidequestKey: "Decline Push-Up | Knee",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
  ],
  tags: ["chest", "shoulders", "triceps"],
  diff: 1.6,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 1, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.24, 0.30],
  desc: "Decline Knee Push-Up with the knees spread wide apart instead of together, widening the base of support. The added stability takes some of the edge off the decline's increased shoulder demand, making this the most accessible variant in the Decline Knee group.",
  cues: "Feet up on the step or bench, knees down and spread wide apart. Hands at standard width. Lower the chest with control â€” the wide knee base helps offset the steeper decline angle. Press back to full extension.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 91,
  name: "Decline Push-Up | Knee, One Leg",
  sidequestKey: "Decline Push-Up | Knee, Diamond",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 2.3,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 1, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.27, 0.35],
  desc: "Decline Knee Push-Up with one knee lifted off the floor, leaving a single knee as the rear contact point while the feet stay up on the step or bench. Removing a contact point under the decline's already-elevated feet position makes the anti-rotation demand meaningfully higher than the floor-level One Leg variant.",
  cues: "Feet elevated, set up on both knees, then lift one knee a few inches off the floor. Brace the core hard and keep the hips level â€” the elevated feet make any tilt more noticeable. Switch the raised knee each set.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 92,
  name: "Decline Push-Up | Knee, Knuckle",
  sidequestKey: "Decline Push-Up | Knee, Fingertip",
  alt: null,
  pathTag: "knuckle",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 2.0,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 0, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.24, 0.32],
  desc: "Decline Knee Push-Up performed on the proximal knuckle row of a loosely closed fist, placing the wrist in a neutral position under the decline's heavier load. Removes wrist extension exactly when it would otherwise be most pronounced, due to the steeper hand angle from the elevated feet.",
  cues: "Feet up on the step or bench. Make a loose fist and place the knuckle row on the floor, wrist straight. Knees down, hips level. Perform the rep exactly as a Decline Push-Up | Knee â€” the only change is the contact surface.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 93,
  name: "Decline Push-Up | Knee, Fist",
  sidequestKey: "Decline Push-Up | Knee, Fingertip",
  alt: null,
  pathTag: "knuckle",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 2.2,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 0, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.26, 0.34],
  desc: "Decline Knee Push-Up on a fully closed fist. The tight grip demands sustained forearm tension to keep the fist stable while the decline angle pushes more load through the shoulder â€” a meaningfully more demanding combination than the floor-level Fist variant.",
  cues: "Feet elevated. Close the fist tightly and press the flat knuckle surface into the floor. Wrist absolutely straight. Knees down. Grip hard throughout the set â€” a loosening fist is the first sign of fatigue.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 94,
  name: "Decline Push-Up | Knee, Archer",
  sidequestKey: "Decline Push-Up | Knee, Typewriter",
  alt: null,
  pathTag: "one-arm",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 2.4,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 3, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.32, 0.42],
  desc: "Decline Knee Push-Up with one arm bending to lower the chest toward that side while the other extends as a lightly loaded guide, feet up on the step or bench. The decline's extra shoulder load makes the bending arm work noticeably harder than it would on the floor-level Archer.",
  cues: "Feet elevated, hands wide, knees down. Shift weight toward one side and bend that elbow to lower the chest â€” the decline angle makes the lean feel steeper. The straight arm guides but barely loads. Press back through the bent arm and alternate sides.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 119,
  name: "Decline Push-Up | Knee, 4-Finger",
  sidequestKey: "Decline Push-Up | Knee, One Arm",
  alt: null,
  pathTag: "fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: true },
    { n: "Shoulders", p: true },
    { n: "Forearms",  p: false },
  ],
  tags: ["chest", "triceps", "shoulders", "forearms"],
  diff: 3.0,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 3, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.28, 0.36],
  desc: "Decline Knee Push-Up on four fingertips with the pinky removed, feet elevated on a step or bench. Removing a digit while the decline routes extra load through the bottom position raises per-finger tendon stress clearly above the floor-level Knee 4-Finger variant.",
  cues: "Feet up. Tuck the pinky away before placing hands. Four fingertips on the floor, palms clear. Lower deliberately â€” tendon tissue adapts more slowly than muscle, so keep volume conservative.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 97,
  name: "Decline Push-Up | Knee, Explosive",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
  ],
  tags: ["chest", "shoulders", "triceps", "power"],
  diff: 2.3,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 2, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.37, 0.47],
  desc: "Decline Knee Push-Up performed with a maximal-speed concentric, hands briefly leaving the floor at the top of each rep, feet elevated on a step or bench. The steeper decline angle increases landing force compared to the floor-level explosive Knee Push-Up, so soft hands and a controlled catch matter more here.",
  cues: "Feet up, knees down, lower under control, then drive upward as explosively as possible so the hands clear the floor. Land with soft, slightly bent elbows â€” the decline angle means more force to absorb on the catch than at floor level.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 98,
  name: "Decline Push-Up | Knee, Clap",
  sidequestKey: "Decline Push-Up | Knee, Explosive",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
  ],
  tags: ["chest", "shoulders", "triceps", "power"],
  diff: 2.6,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 2, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.40, 0.51],
  desc: "Explosive Decline Knee Push-Up with enough airtime to clap the hands together before catching the floor again, feet elevated on a step or bench. The decline's steeper angle and heavier shoulder load demand noticeably more power output than the floor-level Clap variant to achieve the same airtime.",
  cues: "Feet up, knees down, drive off the floor with maximum force. Clap the hands together at chest height while airborne, then return them to the floor before contact. Catch with soft elbows and reset hip position before the next rep.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 99,
  name: "Decline Push-Up | Knee, Negative",
  sidequestKey: "Decline Push-Up | Knee, Explosive",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
  ],
  tags: ["chest", "shoulders", "triceps"],
  diff: 2.7,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.24, 0.31],
  desc: "Decline Knee Push-Up performed with a 3â€“5 second eccentric only, no drive on the concentric, feet up on a step or bench. Extending time under tension on the lowering phase builds eccentric strength specifically under the decline's heavier shoulder load, ahead of the strength needed for the full Decline Negative.",
  cues: "Feet elevated, knees down. Lower the chest over a full 3â€“5 second count, resisting the descent the entire way against the steeper decline angle. Either press back up normally or reset from the top.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 212,
  name: "Decline Push-Up | Knee (Bar)",
  sidequestKey: "Decline Push-Up | Knee, Fingertip",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
  ],
  tags: ["chest", "shoulders", "triceps"],
  diff: 2.0,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 1, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.25, 0.33],
  desc: "Decline Knee Push-Up performed gripping a pair of push-up bars, feet elevated on a step or bench, keeping the wrists in a neutral position instead of full extension. The neutral grip slightly reduces wrist stress versus the flat-floor version, with only a minor effect on the decline's heavier shoulder load.",
  cues: "Set the bars at shoulder-width, knees down on the floor, feet up behind you on a stable surface. Grip neutrally and lower with control â€” the wrists stay straight throughout. Press back to full extension, keeping the same hip line as a standard Decline Knee Push-Up.",
  equipment: "Push-Up Bars",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 213,
  name: "Decline Push-Up | Knee (Parallettes)",
  sidequestKey: "Decline Push-Up | Knee, Fingertip",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
  ],
  tags: ["chest", "shoulders", "triceps"],
  diff: 2.6,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 3, elbow: 1, shoulder: 3, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 2,
  technique: 1,
  kcalPerRep: [0.29, 0.38],
  desc: "Decline Knee Push-Up performed on parallettes, feet elevated on a step or bench, combining a neutral grip with the deepest ROM the decline-and-knee tier allows. As with the floor Knee Push-Up, the deeper stretch on the pecs and shoulders outweighs the wrist-angle benefit, making this slightly harder than the plain Decline Deficit version despite the more comfortable grip.",
  cues: "Set parallettes at shoulder-width, knees down on the floor, feet up behind you. Lower the chest well below hand height, feeling the deep stretch through the pecs and front shoulder. Press back to full extension without letting the hips sag.",
  equipment: "Parallettes",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 215,
  name: "Decline Push-Up | Knee (TRX)",
  sidequestKey: "Decline Push-Up | Knee, Fingertip",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 2.5,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 3, neck: 0, lowerBack: 2,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.28, 0.36],
  desc: "Decline Knee Push-Up performed gripping a pair of suspension trainer handles, feet elevated on a step or bench, adding light instability on top of the decline-and-knee tier load. The straps drift more than a fixed surface but far less than rings, giving a mild stabilization demand suited as a stepping stone before progressing to ring-based decline work.",
  cues: "Set the straps to hover just above floor height with handles level, feet up behind you. Knees down, grip the handles and lower with control, keeping them from swinging side to side. Press back to full extension while resisting any drift in the straps.",
  equipment: "TRX",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 85,
  name: "Decline Push-Up | Knee",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
    pathNode: true,
  diff: 3.5,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.24, 0.32],
  desc: "Knee Push-Up with the feet elevated on a step or bench instead of the hands, shifting load toward the shoulders and upper chest. The knee-based lever keeps it well short of a full toes-elevated Decline Push-Up, but it's a clear step up from the standard Knee Push-Up â€” the natural bridge between the two.",
  cues: "Knees down on the floor, feet up on a stable step or bench behind you. Hands at standard shoulder-width, hips in line with shoulders and ankles. Lower the chest under control and press back to full extension â€” don't let the hips sag.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 87,
  name: "Decline Push-Up | Knee, Narrow",
  sidequestKey: "Decline Push-Up | Knee",
  alt: null,
  muscles: [
    { n: "Triceps",   p: true },
    { n: "Shoulders", p: true },
    { n: "Chest",     p: false },
  ],
  tags: ["triceps", "shoulders", "chest"],
  diff: 3.8,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 2, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.25, 0.33],
  desc: "Decline Knee Push-Up with hands close together beneath the chest. The narrow grip pushes elbow extension demand higher, and combined with the decline's upper-chest emphasis the front shoulder takes on noticeably more work than the floor-level Knee Push-Up | Narrow.",
  cues: "Feet elevated, knees down. Bring the hands in until thumbs are almost touching beneath the chest. Keep elbows tracking back along the ribs rather than flaring out. Lower under control and press to a full lockout.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 88,
  name: "Decline Push-Up | Knee, Diamond",
  sidequestKey: "Diamond Push-Up",
  alt: null,
  muscles: [
    { n: "Triceps",   p: true },
    { n: "Shoulders", p: true },
    { n: "Chest",     p: false },
  ],
  tags: ["triceps", "shoulders", "chest"],
  diff: 4.0,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 2, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.29, 0.37],
  desc: "Decline Knee Push-Up with index fingers and thumbs touching to form a diamond beneath the sternum. The extreme grip narrowing plus the decline's increased upper-body load makes this the hardest of the core hand-placement variants in the group, concentrating heavy work on the triceps and front shoulder.",
  cues: "Feet up on the step or bench. Form a diamond shape with thumbs and index fingers under the chest. Keep elbows tucked close to the ribs as you lower â€” they should brush the sides, not flare. Press through the diamond back to full extension.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 89,
  name: "Decline Push-Up | Knee, Staggered",
  sidequestKey: "Decline Push-Up | Knee",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 3.7,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.27, 0.34],
  desc: "Decline Knee Push-Up with one hand at standard width and the other shifted forward or back, creating an asymmetric load split under the decline's heavier shoulder demand. The offset hand carries a clearly greater share of the work each rep than it would at floor level.",
  cues: "Feet elevated, knees down. Slide one hand forward by a hand-length. Lower evenly â€” both elbows bend, but the rear hand drives most of the press. Switch which hand is forward each set.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 114,
  name: "Decline Push-Up | Knee, T",
  sidequestKey: "Spider-Man Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Biceps",    p: false },
  ],
  tags: ["chest", "shoulders", "biceps"],
  diff: 4.1,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 3, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.30, 0.39],
  desc: "Decline Knee Push-Up with the arms extended out to the sides at shoulder height, forming a T with the torso, feet elevated on a step or bench. The wide, fly-style elbow path combined with the decline's heavier load shifts an even greater share of the work onto the anterior deltoid than the floor-level T variation.",
  cues: "Feet up on the step or bench. Hands wide, arms extended out to the sides at shoulder height â€” body forms a T. Bend the elbows outward as the chest lowers, mimicking a fly motion. Press back by squeezing the pecs together rather than driving the elbows inward.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 95,
  name: "Decline Push-Up | Knee, Typewriter",
  alt: null,
  pathTag: "one-arm",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 4.5,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 3, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.39, 0.50],
  desc: "Decline Knee Push-Up that lowers to one side, then slides laterally across the bottom until the loaded and extended arms switch â€” both hands stay down, feet stay elevated throughout. The decline's heavier shoulder load makes each pass meaningfully harder than the floor-level Typewriter, while the knee lever keeps it short of the full Decline version.",
  cues: "Feet up on the step or bench. Start wide and lower to one side. Without coming back up, slide the body laterally in one fluid motion until the arms invert. Keep the hips level throughout the sweep â€” the elevated feet make any twist obvious.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 118,
  name: "Decline Push-Up | Knee, Fingertip",
  sidequestKey: null,
  alt: null,
  pathTag: "fingertip",
  pathNode: true,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: true },
    { n: "Shoulders", p: true },
    { n: "Forearms",  p: false },
  ],
  tags: ["chest", "triceps", "shoulders", "forearms"],
  diff: 3.9,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 2, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.28, 0.36],
  desc: "Decline Knee Push-Up performed on all five fingertips, feet elevated on a step or bench. The decline's heavier bottom-position load routes meaningfully more force through the fingertips than the floor-level Knee Fingertip variant, while staying short of the full toes-elevated Decline Fingertip line.",
  cues: "Feet up on the step or bench. Spread all five fingertips and lift the palms clear of the floor. Lower with full control; stop immediately if a joint produces sharp pain rather than the expected tendon tension.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 120,
  name: "Decline Push-Up | Knee, 3-Finger",
  sidequestKey: "Decline Push-Up | Fingertip",
  alt: null,
  pathTag: "fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: true },
    { n: "Shoulders", p: true },
    { n: "Forearms",  p: false },
  ],
  tags: ["chest", "triceps", "shoulders", "forearms"],
  diff: 4.2,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: false, eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 3, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.29, 0.37],
  desc: "Decline Knee Push-Up on the index, middle, and ring fingers only, feet elevated on a step or bench. At this combination the decline's added load genuinely stresses the proximal interphalangeal joints â€” frequency should stay low with mandatory rest days between sessions.",
  cues: "Feet up. Index, middle, and ring finger only â€” pinky and little finger tucked. Palms completely off the floor. Lower under full control; this is tendon work first.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 121,
  name: "Decline Push-Up | Knee, 2-Finger",
  sidequestKey: "Decline Push-Up | Fingertip",
  alt: null,
  pathTag: "fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: true },
    { n: "Shoulders", p: true },
    { n: "Forearms",  p: false },
  ],
  tags: ["chest", "triceps", "shoulders", "forearms"],
  diff: 4.5,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 4, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.29, 0.37],
  desc: "Decline Knee Push-Up on the index and middle fingers of each hand, feet elevated on a step or bench. Halving the digit count under the decline's heavier load is a genuinely elite-tier tendon demand â€” only practitioners with substantial long-term finger conditioning should attempt volume here.",
  cues: "Feet up. Index and middle finger only, remaining fingers fully off the floor. Knees down. Treat each rep as a maximum tendon stimulus; two to four reps per session is ample.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 100,
  name: "Decline Push-Up | Knee, Pause",
  sidequestKey: "Decline Push-Up | Knee",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
  ],
  tags: ["chest", "shoulders", "triceps"],
  diff: 3.7,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.24, 0.32],
  desc: "Decline Knee Push-Up with a dead-stop pause at the bottom before pressing back up, feet elevated on a step or bench. Removing the elastic rebound makes the concentric noticeably harder to initiate, building strength out of the weakest point in the range under the decline's added load.",
  cues: "Feet up, lower under control and stop completely at the bottom, chest just off the floor â€” no bounce. Hold for one to two full seconds, staying tight through the core, then press back up from a dead stop.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 211,
  name: "Decline Push-Up | Knee, Deficit",
  sidequestKey: "Decline Push-Up | Knee",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
  ],
  tags: ["chest", "shoulders", "triceps"],
  diff: 3.9,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 3, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 2,
  technique: 1,
  kcalPerRep: [0.27, 0.35],
  desc: "Decline Knee Push-Up with the hands elevated on blocks or low parallettes on the floor, feet up on a step or bench. The deeper hand-side ROM stacks directly on top of the decline's already heavier shoulder load, making this the largest cumulative ROM-plus-load combination in the knee-tier lines while the knee lever still keeps it well short of the full Decline Deficit.",
  cues: "Feet elevated behind you, hands on two stable blocks or low parallettes, shoulder-width apart. Knees down, hips level. Lower the chest below hand height, feeling the deeper stretch through the pecs and front shoulder, then press back to full extension.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 214,
  name: "Decline Push-Up | Knee (Rings)",
  sidequestKey: "Preacher Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 4.4,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 3, elbow: 2, shoulder: 3, neck: 0, lowerBack: 2,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 2,
  technique: 4,
  kcalPerRep: [0.30, 0.39],
  desc: "Decline Knee Push-Up performed gripping a pair of gymnastic rings, feet elevated on a step or bench, adding full three-dimensional rotational instability on top of the decline-and-knee tier load. The rings must be actively stabilized through the entire rep â€” turning out at the bottom and squeezing in at the top â€” a meaningfully harder technical demand than the floor-level Knee Push-Up (Rings) given the decline's added shoulder load.",
  cues: "Set the rings at a height that lets the knees rest on the floor with arms extended, feet up behind you. Grip the rings firmly and turn them out slightly as you lower. Press back to full extension while actively rolling the rings inward to stay stable â€” don't let them swing.",
  equipment: "Rings",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 310,
  name: "Decline Push-Up",
  sidequestKey: "Decline Push-Up | Diamond",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: false },
    { n: "Serratus",  p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "serratus"],
  diff: 3.5,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: true,  eff: 4 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 2, shoulder: 3, neck: 1, lowerBack: 2,
            knee: 0, fingers: 0, thoracic: 1, si: 0, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.27, 0.34],
  desc: "Decline push-up (30cm decline) performed with the feet elevated on a bench, box, or step while the hands remain on the floor. The elevated foot position shifts a larger share of bodyweight onto the upper body and steepens the angle at the shoulder, increasing demand on the anterior/medial deltoids and the upper (clavicular) pec fibers compared to a standard floor push-up. The lower back and core work harder to keep the body rigid against the steeper incline, resisting any sag at the hips.",
  cues: "Place both feet on a stable bench or box roughly knee-to-hip height, hands on the floor at shoulder width. Set the body in a straight line from head to heels â€” don't let the hips sag. Lower the chest toward the floor under control, then press back to full lockout. Use a box low enough to keep full control; greater height increases difficulty.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 311,
  name: "Decline Push-Up | One Leg",
  sidequestKey: "Decline Push-Up | Diamond",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
    { n: "Glutes",    p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "glutes"],
  diff: 3.8,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 2, shoulder: 3, neck: 1, lowerBack: 2,
            knee: 0, fingers: 0, thoracic: 1, si: 1, hip: 2, groin: 0, ankle: 1, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.29, 0.38],
  desc: "Decline push-up performed with one foot lifted off the elevated surface, leaving a single point of foot contact. Removing a foot from the platform creates an unstable, asymmetric base that the obliques and hip stabilizers on the working side must actively resist to prevent pelvic rotation, stacked on top of the already elevated shoulder and upper-chest demand of the base decline position.",
  cues: "Set up in a decline push-up position with both feet on the box, then lift one foot a few inches higher, keeping the hips square. Perform the rep with identical form to a standard decline push-up â€” don't let the hips twist toward the lifted leg. Alternate legs between sets.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 312,
  name: "Decline Push-Up | Staggered",
  sidequestKey: "Decline Push-Up | Diamond",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core"],
  diff: 3.8,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 2, shoulder: 3, neck: 1, lowerBack: 2,
            knee: 0, fingers: 0, thoracic: 1, si: 1, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.29, 0.38],
  desc: "Decline push-up with one hand placed slightly forward and the other slightly back of standard width. The offset hand position shifts a greater proportion of load onto the lead arm while the torso resists lateral rotation throughout the rep, functioning as an accessible bridge toward single-arm decline pushing.",
  cues: "On a decline setup, place one hand a half hand-length ahead, the other a half hand-length behind. Keep the hips square and avoid rotating toward the lead hand. Lower and press with control, then switch the staggered side on the next set.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 313,
  name: "Decline Push-Up | Negative",
  sidequestKey: "Decline Push-Up | Diamond",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core"],
  diff: 3.6,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 2, shoulder: 3, neck: 1, lowerBack: 2,
            knee: 0, fingers: 0, thoracic: 1, si: 0, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.53, 0.68],
  desc: "Decline push-up performed with a slow, controlled 3-5 second eccentric (lowering) phase, then a reset rather than an explosive press. The extended time under tension on the already shoulder- and upper-chest-dominant decline position substantially raises the strength and stability demand versus a standard-tempo rep, even though no extra range of motion is added.",
  cues: "Set up in decline position. Lower yourself over a full 3-5 second count, resisting the descent the entire way down. Once the chest nears the floor, either reset from the knees or use minimal assistance to return to the top â€” the eccentric is the working phase, not the press.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 314,
  name: "Decline Push-Up | Pause",
  sidequestKey: "Preacher Push-Up",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core"],
  diff: 4.4,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 2, shoulder: 3, neck: 1, lowerBack: 2,
            knee: 0, fingers: 0, thoracic: 1, si: 0, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 4,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.40, 0.51],
  desc: "Decline push-up with a dead-stop pause of 1-3 seconds at the bottom position, chest hovering just above the floor. Removing the stretch-reflex bounce out of the bottom forces the chest, shoulders, and triceps to generate force from a static dead position, increasing the strength demand relative to a continuous-tempo decline push-up.",
  cues: "Lower into the decline push-up as normal, but stop with the chest an inch above the floor and hold for 1-3 seconds without resting your weight down. Press steadily back to lockout from the dead stop. Keep the body rigid throughout the pause â€” no sagging hips.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 350,
  name: "Decline Push-Up | (TRX)",
  sidequestKey: "Decline Push-Up | Pseudo Planche",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
  ],
  tags: ["shoulders", "chest", "triceps", "core"],
  diff: 5.0,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 2, shoulder: 3, neck: 1, lowerBack: 2,
            knee: 0, fingers: 0, thoracic: 1, si: 1, hip: 2, groin: 0, ankle: 1, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.31, 0.40],
  desc: "Decline push-up performed with the feet suspended in TRX foot cradles instead of resting on a fixed bench or box. The hands stay on the floor while the suspended feet are free to drift in any direction, forcing the core and hip stabilizers to continuously correct for sway on top of the elevated-foot shoulder and upper-chest loading already present in the decline position. Any asymmetry in the press translates directly into foot-strap movement, making this a meaningfully less stable variant than a fixed-surface decline.",
  cues: "Adjust the TRX foot cradles to roughly knee height and slide both feet into the straps. Walk the hands out to a plank with the body in a straight line. Lower the chest toward the floor while actively resisting any side-to-side or fore-aft drift of the suspended feet. Press back to full lockout. Keep the hips from sagging or piking â€” the straps will amplify any loss of core tension.",
  equipment: "TRX",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 315,
  name: "Decline Push-Up | Fingertip",
  sidequestKey: null,
  pathTag: "decline-fingertip",
  pathNode: true,
  alt: null,
  muscles: [
    { n: "Shoulders",  p: true  },
    { n: "Chest",      p: true  },
    { n: "Triceps",    p: true  },
    { n: "Forearms",   p: false },
    { n: "Core",       p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "forearms", "core"],
  diff: 4.5,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 3, elbow: 2, shoulder: 3, neck: 1, lowerBack: 2,
            knee: 0, fingers: 2, thoracic: 1, si: 0, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.29, 0.37],
  desc: "Decline push-up performed on the fingertips of both hands rather than the full palm. The reduced contact surface concentrates load through the finger flexor tendons and demands continuous balance correction on top of the elevated-foot shoulder and chest loading already present in the decline position.",
  cues: "Set up in decline position with weight on all five fingertips of each hand, knuckles lifted. Keep the fingers spread and rigid as you lower with control. Press back to lockout, maintaining fingertip contact throughout â€” don't let the knuckles drop to the floor.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 316,
  name: "Decline Push-Up | 4-Finger",
  sidequestKey: "Decline Push-Up | Fingertip",
  pathTag: "decline-fingertip",
  alt: null,
  muscles: [
    { n: "Shoulders",  p: true  },
    { n: "Chest",      p: true  },
    { n: "Triceps",    p: true  },
    { n: "Forearms",   p: false },
    { n: "Core",       p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "forearms", "core"],
  diff: 4.8,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 3, elbow: 2, shoulder: 3, neck: 1, lowerBack: 2,
            knee: 0, fingers: 3, thoracic: 1, si: 0, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.29, 0.38],
  desc: "Decline fingertip push-up with the pinky finger lifted off the floor on each hand, distributing load across four digits instead of five. The reduced base further concentrates flexor-tendon stress and demands tighter finger-spread control than the full fingertip version.",
  cues: "From the decline fingertip position, lift the pinky of each hand off the floor, balancing on the remaining four fingertips. Keep the load even across all four digits. Lower and press with the same control as the fingertip version, watching for any finger collapse.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 318,
  name: "Decline Push-Up | Clap",
  sidequestKey: "Push-Up | Clap",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "power"],
  diff: 4.9,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 3, elbow: 3, shoulder: 4, neck: 1, lowerBack: 2,
            knee: 0, fingers: 0, thoracic: 2, si: 0, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 4,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.18, 0.24],
  desc: "Explosive decline push-up in which the press generates enough power to leave the floor entirely, allowing a hand clap before catching and absorbing the landing. The elevated-foot position adds extra loading to an already high-power plyometric movement, demanding rapid force production through the chest, shoulders, and triceps plus a controlled, joint-protective landing.",
  cues: "Set up in decline position. Lower under control, then drive explosively off the floor with maximum force, clapping the hands together at the peak. Spot the floor on the way down and absorb the landing by bending the elbows immediately on contact â€” never land with locked-out arms. Reset the plank before the next rep.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 382,
  name: "Decline Push-Up | Knuckle",
  sidequestKey: "Decline Push-Up | Diamond",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core"],
  diff: 3.6,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 2, shoulder: 3, neck: 1, lowerBack: 2,
            knee: 0, fingers: 1, thoracic: 1, si: 0, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.27, 0.34],
  desc: "Decline push-up performed on the knuckles with the wrists held neutral, removing the wrist-extension stress that the steeper decline angle would otherwise amplify on a flat palm. The elevated-foot loading on the shoulders and upper chest is unchanged; only the contact point and wrist angle differ. Useful for trainees who want decline-level shoulder loading but cannot tolerate loaded wrist extension.",
  cues: "Set feet on a box and place both fists knuckle-down on the floor at shoulder width, wrists stacked straight. Keep the body in a straight line and lower the chest between the fists. Press back to lockout without letting the wrists roll. Use a padded surface for the knuckles.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 381,
  name: "Decline Push-Up | Diamond",
  sidequestKey: "Diamond Push-Up",
  alt: null,
  muscles: [
    { n: "Triceps",   p: true  },
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Core",      p: false },
  ],
  tags: ["triceps", "shoulders", "chest", "core"],
  diff: 3.9,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 3, elbow: 3, shoulder: 3, neck: 1, lowerBack: 2,
            knee: 0, fingers: 0, thoracic: 1, si: 0, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.29, 0.38],
  desc: "Decline push-up with the hands forming a diamond beneath the sternum, combining the elevated-foot shoulder and upper-chest loading with the triceps-dominant near-contact grip of the diamond. The decline angle drives extra load through the triceps at the top of the press while the diamond hand position keeps the elbows tight, raising wrist and elbow stress over both the flat decline and the floor diamond.",
  cues: "Place feet on a box and form a diamond with the hands under the sternum on the floor. Keep the elbows brushing the ribs as you lower the chest to the diamond. Press back to full lockout, resisting elbow flare. Lower the box height if the wrist angle becomes uncomfortable under the steeper load.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 393,
  name: "Decline Push-Up | Spider-Man",
  sidequestKey: "Spider-Man Push-Up",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
    { n: "Obliques",  p: true  },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "obliques"],
  diff: 4.1,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 2, shoulder: 3, neck: 1, lowerBack: 2,
            knee: 0, fingers: 0, thoracic: 1, si: 1, hip: 2, groin: 1, ankle: 1, foot: 0 },
  strength: 3,
  mobility: 2,
  technique: 3,
  kcalPerRep: [0.29, 0.38],
  desc: "Decline push-up with one knee sweeping up toward the same-side elbow on each descent, feet elevated on a box. Combining the decline angle's added shoulder and upper-chest load with the Spiderman knee sweep stacks an oblique and hip-flexor anti-rotation demand on top of an already harder pressing base, while keeping the elevated foot stable on the box as the other leg moves.",
  cues: "Set both feet on a box in a decline plank. As you lower, sweep one knee out and forward toward the elbow, keeping the planted foot steady. Press back while returning the leg, then alternate sides. Keep the hips square against the box â€” don't let the sweep twist the pelvis.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 438,
  name: "Decline Push-Up | Wide",
  sidequestKey: "Decline Push-Up | Diamond",
  alt: null,
  muscles: [
    { n: "Chest",     p: true  },
    { n: "Shoulders", p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 3.5,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: true,  eff: 4 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 2, shoulder: 3, neck: 1, lowerBack: 2,
            knee: 0, fingers: 0, thoracic: 1, si: 0, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.27, 0.34],
  desc: "Decline push-up with the hands placed wider than shoulder width, broadening the base and shifting the stretch onto the outer pec fibers. The wide hand position reduces triceps involvement compared to the standard decline while keeping the elevated-foot shoulder and upper-chest demand fully intact.",
  cues: "Place feet on the box and set hands roughly 1.5â€“2 times shoulder width apart. Lower the chest between the hands under control, keeping the elbows at a moderate angle rather than flaring straight out. Press back to lockout. A wider grip reduces range of motion slightly at the chest â€” use a controlled tempo to maintain stimulus.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 439,
  name: "Decline Push-Up | Narrow",
  sidequestKey: "Decline Push-Up | Diamond",
  alt: null,
  muscles: [
    { n: "Triceps",   p: true  },
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Core",      p: false },
  ],
  tags: ["triceps", "shoulders", "chest", "core"],
  diff: 3.7,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 3, shoulder: 3, neck: 1, lowerBack: 2,
            knee: 0, fingers: 0, thoracic: 1, si: 0, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.28, 0.36],
  desc: "Decline push-up with hands placed inside shoulder width, stacking the elevated-foot shoulder and upper-chest load on top of the increased triceps demand of the narrow grip. The combination produces a high elbow-extensor and anterior-deltoid stimulus in a single movement.",
  cues: "Feet on box, hands roughly 6â€“8 inches apart on the floor, elbows tracking back along the torso as you lower. Avoid letting the elbows flare outward â€” the narrow hand position only works if the elbows stay in. Press back to full lockout. The wrist angle increases under the steeper decline load â€” ease off width if discomfort appears.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 440,
  name: "Decline Push-Up | Fist",
  sidequestKey: "Decline Push-Up | Diamond",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core"],
  diff: 3.7,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 2, shoulder: 3, neck: 1, lowerBack: 2,
            knee: 0, fingers: 1, thoracic: 1, si: 0, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.27, 0.34],
  desc: "Decline push-up performed on closed fists with the wrists held in a neutral position. The decline angle amplifies wrist-extension stress on a flat palm, so moving to a fist removes that demand entirely while keeping the full elevated-foot shoulder and upper-chest loading of the standard decline.",
  cues: "Place feet on the box and close both hands into fists, knuckles down, wrists straight. Set fists at shoulder width with the knuckle ridge parallel to the floor. Lower the chest between the fists under control and press back to lockout. Use a padded or carpeted surface to protect the knuckles.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 441,
  name: "Decline Push-Up | Explosive",
  sidequestKey: "Push-Up | Clap",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core"],
  diff: 4.6,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 3, elbow: 3, shoulder: 4, neck: 1, lowerBack: 3,
            knee: 0, fingers: 0, thoracic: 1, si: 0, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 4,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.35, 0.45],
  desc: "Decline push-up executed with a maximal-speed concentric press so the hands leave the floor. The elevated foot position amplifies upper-chest and deltoid loading on top of the already demanding explosive power requirement, placing significantly higher impact stress on the wrists and shoulders on landing than the floor explosive variant.",
  cues: "Set feet on a box. Lower under control, then press with maximum acceleration so the hands lift clear of the floor. Land with slightly bent elbows to absorb impact and immediately control the descent into the next rep. Quality of the take-off, not height, is the goal. Never land on locked elbows.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 443,
  name: "Decline Push-Up | T-Rotation",
  sidequestKey: "Preacher Push-Up",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
    { n: "Obliques",  p: true  },
    { n: "Serratus",  p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "obliques", "serratus"],
  diff: 4.8,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 2, shoulder: 4, neck: 1, lowerBack: 3,
            knee: 0, fingers: 0, thoracic: 2, si: 1, hip: 2, groin: 1, ankle: 1, foot: 0 },
  strength: 3,
  mobility: 2,
  technique: 3,
  kcalPerRep: [0.30, 0.38],
  desc: "Decline push-up followed by a full thoracic rotation at the top â€” one arm extends toward the ceiling and the body opens into a T. Performing the rotation at decline angles increases the anti-rotation demand through the obliques and serratus compared to the floor version, since the steeply angled bodyweight creates a stronger twisting moment as one arm leaves the floor.",
  cues: "Press to the top of a decline push-up, then rotate one arm toward the ceiling. Feet stay on the box throughout â€” don't let the hip sag downward during the rotation. Hold briefly at the top, return, and alternate sides. The feet-elevated position makes balancing on one arm harder than on the floor.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 452,
  name: "Decline Push-Up | Closed Legs",
  sidequestKey: "Decline Push-Up | Diamond",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
  ],
  tags: ["shoulders", "chest", "triceps", "core"],
  diff: 3.6,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 2, shoulder: 3, neck: 1, lowerBack: 2,
            knee: 0, fingers: 0, thoracic: 1, si: 1, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.28, 0.36],
  desc: "Decline push-up performed with both feet touching together on the elevated surface rather than hip-width apart. The narrowed foot base reduces the lateral support polygon, forcing the obliques and core to resist a stronger tipping and rotation moment throughout the rep on top of the decline's already elevated shoulder and upper-chest demand.",
  cues: "Set feet together on the box â€” ankles touching. Brace the core hard before lowering; the narrow foot stance amplifies any side-to-side instability. Lower and press with the same control as the standard decline. If you can't prevent hip tilt, widen the feet slightly and build toward closed legs over time.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 115,
  name: "Decline Push-Up | Knee, Pseudo Planche",
  sidequestKey: "Pseudo Planche Push-Up",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true },
    { n: "Chest",     p: true },
    { n: "Triceps",   p: false },
    { n: "Serratus",  p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "serratus"],
  diff: 5.5,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 1, shoulder: 3, neck: 0, lowerBack: 1,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 2,
  technique: 2,
  kcalPerRep: [0.32, 0.41],
  desc: "Decline Knee Push-Up with the hands shifted back toward the hips and the torso leaning forward over them, feet elevated on a step or bench, pushing the shoulders past the hands in a planche-like lean. The decline's heavier load combined with the forward lean drives noticeably deeper anterior-deltoid and serratus demand than the floor-level Knee Pseudo Planche.",
  cues: "Feet up on the step or bench. Shift the hands back so they sit roughly beneath the hips, fingers pointing forward or slightly outward. Lean the torso forward until the shoulders pass in front of the hands, knees still down. Lower with control â€” don't let the hips sag or the lower back arch.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 96,
  name: "Decline Push-Up | Knee, One Arm",
  sidequestKey: null,
  alt: null,
  pathTag: "one-arm",
  pathNode: true,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 6.5,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: false, eff: 2 },
  joints: { wrist: 3, elbow: 2, shoulder: 3, neck: 0, lowerBack: 2,
            knee: 2, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.36, 0.46],
  desc: "Push-up with one hand on the floor and the other held behind the back, knees down and feet elevated on a step or bench. The decline's increased load combined with unilateral pressing makes this the hardest entry in the Decline Knee group â€” a direct bridge toward the full one-arm progression once the knee version is solid.",
  cues: "Feet elevated, centre one hand under the chest, knees down, hips level. Place the free hand firmly on the lower back. Brace hard against rotation before the descent â€” the decline angle amplifies any twist. Lower and press to full extension without the hip on the working side hiking.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 116,
  name: "Decline Push-Up | Knee, One Arm, Knuckle",
  sidequestKey: "Decline Push-Up | Knee, One Arm",
  alt: null,
  pathTag: "knuckle",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 6.4,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 0, elbow: 2, shoulder: 3, neck: 0, lowerBack: 2,
            knee: 2, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.34, 0.43],
  desc: "One-arm decline knee push-up performed on the proximal knuckle row, keeping the wrist neutral while the decline's heavier shoulder load runs through unilateral pressing. The narrow contact point adds lateral balance demand directly on top of the decline's already-elevated shoulder and anti-rotation requirement.",
  cues: "Feet up on the step or bench. Loose fist, knuckle row on the floor, wrist straight. One arm only, other hand behind the back. Brace the shoulder hard and keep the fist aligned â€” the decline angle amplifies any lateral wobble.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 117,
  name: "Decline Push-Up | Knee, One Arm, Fist",
  sidequestKey: "Decline Push-Up | Knee, One Arm",
  alt: null,
  pathTag: "knuckle",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 6.4,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 0, elbow: 2, shoulder: 3, neck: 0, lowerBack: 2,
            knee: 2, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.35, 0.44],
  desc: "One-arm decline knee push-up on a fully closed fist. The tight grip demands sustained forearm rigidity while the decline angle pushes additional load through the shoulder during the unilateral press â€” the hardest of the wrist-neutral knee-tier one-arm variants.",
  cues: "Feet elevated. Close the fist tightly before taking the position. Wrist straight. One arm, other hand away. Brace hard against rotation and keep the fist rigid from start to finish â€” the decline load makes any grip loosening obvious immediately.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 122,
  name: "Decline Push-Up | Knee, 1-Finger",
  sidequestKey: "Push-Up | 3-Finger",
  alt: null,
  pathTag: "fingertip",
  pathNode: true,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: true },
    { n: "Shoulders", p: true },
    { n: "Forearms",  p: false },
  ],
  tags: ["chest", "triceps", "shoulders", "forearms"],
  diff: 5.8,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 2, fingers: 5, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.29, 0.37],
  desc: "Decline Knee Push-Up with a single index finger per hand bearing the entire load, feet elevated on a step or bench. Routing the decline's heavier bottom-position force through one digit each is an extraordinary tendon demand â€” documented examples are very rare even among advanced practitioners.",
  cues: "Feet up. One index finger per hand, pointing straight forward, palms and all other digits completely off the floor. Knees down, hips level. A single controlled rep is sufficient stimulus per set.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 123,
  name: "Decline Push-Up | Knee, One Arm, Fingertip",
  sidequestKey: "Decline Push-Up | Knee, One Arm",
  alt: null,
  pathTag: "one-arm-fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Forearms",  p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms", "core"],
  diff: 6.1,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 3, elbow: 2, shoulder: 3, neck: 0, lowerBack: 2,
            knee: 2, fingers: 2, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.36, 0.46],
  desc: "One-arm decline knee push-up performed on all five fingertips of the working hand, feet elevated on a step or bench. The decline's heavier unilateral load compounds directly with the flexor tendon demand of fingertip contact â€” a clear step up from the floor-level Knee One Arm Fingertip variant.",
  cues: "Feet up. Knees down, hips square. Working hand on five fingertips only, palm off the floor. Other hand behind the back. Brace the core hard before each rep â€” the decline angle makes rotation fail faster.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 124,
  name: "Decline Push-Up | Knee, One Arm, 4-Finger",
  sidequestKey: "Decline Push-Up | Knee, One Arm",
  alt: null,
  pathTag: "one-arm-fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Forearms",  p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms", "core"],
  diff: 6.4,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 3, elbow: 2, shoulder: 3, neck: 0, lowerBack: 2,
            knee: 2, fingers: 3, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.37, 0.47],
  desc: "One-arm decline knee push-up on four fingertips with the pinky removed, feet elevated on a step or bench. Concentrating the decline's heavier unilateral load across four fingers adds a meaningful tendon-load step above the all-fingertip version.",
  cues: "Feet up. Pinky off the floor, four fingertips bearing load. One arm only, other hand away. Lock in anti-rotation before descending â€” the decline load makes any twist obvious immediately.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 125,
  name: "Decline Push-Up | Knee, One Arm, 3-Finger",
  sidequestKey: "Decline Push-Up | Knee, One Arm",
  alt: null,
  pathTag: "one-arm-fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Forearms",  p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms", "core"],
  diff: 6.5,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 3, elbow: 2, shoulder: 3, neck: 0, lowerBack: 2,
            knee: 2, fingers: 3, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.37, 0.47],
  desc: "One-arm decline knee push-up on three fingertips â€” index, middle, and ring â€” feet elevated on a step or bench. At this combination the per-finger flexor tendon stress is extreme even relative to the floor-level Knee equivalent; this sits near the top of practical knee-tier work.",
  cues: "Feet up. Three fingertips only. One arm. Knees down, hips absolutely square. Treat as maximum-effort tendon work: two or three reps per set at most.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 126,
  name: "Decline Push-Up | Knee, One Arm, 2-Finger",
  sidequestKey: "Decline Push-Up | Knee, One Arm",
  alt: null,
  pathTag: "one-arm-fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Forearms",  p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms", "core"],
  diff: 6.8,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 3, elbow: 2, shoulder: 3, neck: 0, lowerBack: 2,
            knee: 2, fingers: 4, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 4,
  kcalPerRep: [0.37, 0.47],
  desc: "One-arm decline knee push-up on two fingertips â€” index and middle â€” feet elevated on a step or bench. The decline's heavier unilateral load pushed through two digits sits at the outer boundary of what connective tissue can safely sustain in this family. Practitioners at this level are extremely rare.",
  cues: "Feet up. Index and middle finger only, one arm. Knees down, body as square as possible. A single full-range rep with clean control is the training unit. Rest the fingers for multiple days before repeating.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 127,
  name: "Decline Push-Up | Knee, One Arm, 1-Finger",
  sidequestKey: "Push-Up | 1-Finger",
  alt: null,
  pathTag: "one-arm-fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Forearms",  p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms", "core"],
  diff: 7.5,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 3, elbow: 2, shoulder: 3, neck: 0, lowerBack: 2,
            knee: 2, fingers: 5, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 4,
  kcalPerRep: [0.37, 0.47],
  desc: "One-arm decline knee push-up on a single index finger, feet elevated on a step or bench. The knee lever is the only thing keeping this short of the floor-based equivalent â€” a complete unilateral press through one digit under the decline's heavier load demands exceptional connective tissue integrity. Documented examples are vanishingly rare.",
  cues: "Feet up. One index finger centred under the shoulder, all other digits and the palm off the floor. One arm, other hand completely away. Knees down, entire body braced. One clean rep is the standard â€” do not train this more than once a week.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 317,
  name: "Decline Push-Up | 3-Finger",
  sidequestKey: "Push-Up | 3-Finger",
  pathTag: "decline-fingertip",
  alt: null,
  muscles: [
    { n: "Shoulders",  p: true  },
    { n: "Chest",      p: true  },
    { n: "Triceps",    p: true  },
    { n: "Forearms",   p: false },
    { n: "Core",       p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "forearms", "core"],
  diff: 5.5,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 3, elbow: 3, shoulder: 3, neck: 1, lowerBack: 2,
            knee: 0, fingers: 4, thoracic: 1, si: 0, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 4,
  mobility: 1,
  technique: 4,
  kcalPerRep: [0.31, 0.39],
  desc: "Decline fingertip push-up performed on three fingers per hand â€” typically the thumb, index, and middle. The narrower digit base sharply raises tendon and joint stress at the fingers and wrist, and the smaller contact patch demands much finer balance than the four-finger step.",
  cues: "From the decline fingertip position, lift the ring and pinky fingers of each hand, balancing on three digits. Spread the remaining fingers for the widest stable base possible. Lower under tight control â€” any wobble at this digit count signals you should regress a step.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 319,
  name: "Decline Push-Up | 2-Finger",
  sidequestKey: "Push-Up | 2-Finger",
  pathTag: "decline-fingertip",
  alt: null,
  muscles: [
    { n: "Shoulders",  p: true  },
    { n: "Chest",      p: true  },
    { n: "Triceps",    p: true  },
    { n: "Forearms",   p: true  },
  ],
  tags: ["shoulders", "chest", "triceps", "forearms"],
  diff: 6.8,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 4, elbow: 3, shoulder: 3, neck: 1, lowerBack: 2,
            knee: 0, fingers: 5, thoracic: 1, si: 0, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 4,
  mobility: 1,
  technique: 4,
  kcalPerRep: [0.36, 0.46],
  desc: "Decline fingertip push-up performed on two fingers per hand, typically the thumb and index or thumb and middle. At this digit count the flexor tendons and finger joints take on near-maximal isolated stress, and the contact base is small enough that even minor form breakdown causes a fall.",
  cues: "From the decline fingertip position, drop down to two fingers per hand â€” commonly thumb and index. Keep wrists stacked directly over the contact point. Lower in small, controlled increments rather than a full-depth rep if needed, and stop immediately if you feel sharp finger or wrist pain.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 320,
  name: "Decline Push-Up | One Arm, Straddle",
  sidequestKey: "One Arm Push-Up, Straddle",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
    { n: "Obliques",  p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "obliques"],
  diff: 6.5,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 3, elbow: 3, shoulder: 4, neck: 1, lowerBack: 3,
            knee: 0, fingers: 0, thoracic: 2, si: 1, hip: 2, groin: 0, ankle: 1, foot: 0 },
  strength: 4,
  mobility: 2,
  technique: 4,
  kcalPerRep: [0.43, 0.56],
  desc: "Decline push-up performed on a single arm, with the other arm held behind the back or out to the side for balance. Removing an entire support point while the feet remain elevated combines the decline position's added shoulder and upper-chest load with an extreme anti-rotation demand through the obliques and core, making this one of the hardest realistic single-rep push-up variants.",
  cues: "Set feet on a box as in a standard decline push-up. Place one hand under the center of the chest, slightly wider than a normal single-hand position, and tuck the other arm behind the back. Lower with the working shoulder tracking close to the torso, resisting any twist of the hips or shoulders. Press back to full lockout, then switch arms between sets.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 321,
  name: "Decline Push-Up | 1-Finger",
  sidequestKey: "Push-Up | 1-Finger",
  pathTag: "decline-fingertip",
  alt: null,
  muscles: [
    { n: "Shoulders",  p: true  },
    { n: "Chest",      p: true  },
    { n: "Triceps",    p: true  },
    { n: "Forearms",   p: true  },
    { n: "Core",       p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "forearms", "core"],
  diff: 7.5,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 4, elbow: 3, shoulder: 4, neck: 1, lowerBack: 3,
            knee: 0, fingers: 5, thoracic: 2, si: 0, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 4,
  mobility: 1,
  technique: 5,
  kcalPerRep: [0.45, 0.58],
  desc: "Decline fingertip push-up performed on a single finger per hand â€” almost always the index or middle finger â€” the terminal step of the two-arm finger-reduction chain. The entire bodyweight load, amplified by the decline angle, channels through one digit per side, placing extreme stress on the finger's flexor tendon and the smaller hand and wrist joints.",
  cues: "This is an elite, low-rep finish to the finger-reduction progression â€” only attempt it after the two-finger step is fully controlled. Balance on a single finger per hand, typically the middle finger, with the rest of the hand lifted clear. Lower only a few inches under total control, and stop the set the moment grip or tendon strain feels sharp rather than just challenging.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 442,
  name: "Decline Push-Up | (Rings)",
  sidequestKey: "Decline Push-Up | Pseudo Planche",
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
    { n: "Glutes",    p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "glutes"],
  diff: 5.5,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 2, shoulder: 4, neck: 1, lowerBack: 3,
            knee: 0, fingers: 0, thoracic: 1, si: 1, hip: 2, groin: 0, ankle: 1, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.30, 0.38],
  desc: "Decline push-up performed with both feet in gymnastics rings rather than on a fixed box. The ring suspension creates a rolling instability at the feet â€” they can drift, tip, or rotate â€” forcing the glutes, hip stabilisers, and core to actively resist displacement throughout each rep, stacking instability on top of the elevated-foot shoulder and upper-chest loading of the standard decline.",
  cues: "Thread both feet into rings set at roughly knee-to-hip height. Set hands on the floor as in a standard decline push-up position. Brace the glutes hard before lowering â€” any sag lets the rings swing. Lower the chest to the floor under control, then press back. Increase the challenge by raising the ring height.",
  equipment: "Rings",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 444,
  name: "Decline Push-Up | Pseudo Planche",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: false },
    { n: "Serratus",  p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "serratus"],
  diff: 5.8,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 4, elbow: 3, shoulder: 4, neck: 1, lowerBack: 3,
            knee: 0, fingers: 0, thoracic: 2, si: 0, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 3,
  mobility: 2,
  technique: 3,
  kcalPerRep: [0.32, 0.41],
  desc: "Decline push-up performed with the hands shifted toward the hips so the fingers point back and the shoulders are well forward of the wrists, replicating the partial planche lean. The decline angle already loads the anterior deltoid heavily; shifting the hands back amplifies this further, creating a high anterior-shoulder and wrist demand that bridges decline work toward true planche conditioning.",
  cues: "Set feet on the box and shift hands back so fingers point toward the feet, shoulders clearly in front of the hands. Keep elbows tracking inward â€” flaring outward reduces the planche stimulus. Lower with control; the wrist extension in this position is significant. Ease in gradually over multiple sessions.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 445,
  name: "Decline Push-Up | One Arm, Negative",
  sidequestKey: "One Arm Push-Up, Straddle",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
    { n: "Obliques",  p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "obliques"],
  diff: 6.2,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 3, elbow: 3, shoulder: 5, neck: 1, lowerBack: 3,
            knee: 0, fingers: 0, thoracic: 2, si: 1, hip: 2, groin: 0, ankle: 1, foot: 0 },
  strength: 4,
  mobility: 2,
  technique: 5,
  kcalPerRep: [0.46, 0.60],
  desc: "Decline one-arm push-up performed with a controlled 3â€“5 second lowering phase, with the top half of the press assisted before resetting. The combination of the decline's elevated shoulder load, the extreme anti-rotation demand of the single arm, and the extended eccentric time under tension produces one of the highest-intensity eccentric loading patterns accessible in a bodyweight push-up.",
  cues: "Set feet on a box and perform the standard decline one-arm set-up. Lower extremely slowly over 3â€“5 seconds, resisting the strong tendency to rotate. Use the free arm or both arms to return to the top, then repeat. Prioritise absolute torso control during the descent over rep count.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 446,
  name: "Decline Push-Up | One Arm, Pause",
  sidequestKey: "Decline Push-Up | One Arm",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
    { n: "Obliques",  p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "obliques"],
  diff: 7.5,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 3, elbow: 3, shoulder: 5, neck: 1, lowerBack: 3,
            knee: 0, fingers: 0, thoracic: 2, si: 1, hip: 2, groin: 0, ankle: 1, foot: 0 },
  strength: 5,
  mobility: 2,
  technique: 5,
  kcalPerRep: [0.47, 0.61],
  desc: "Decline one-arm push-up with a dead stop held at the bottom position for 2â€“3 seconds before pressing. Pausing at the point of peak shoulder and chest length eliminates elastic energy storage, requiring the working muscles and connective tissue to generate force entirely from a dead-stretch position under the decline's amplified bodyweight load.",
  cues: "Lower into the bottom of the decline one-arm push-up and hold with the chest near the floor for a full 2â€“3 second count. Maintain the anti-rotation bracing during the entire pause â€” this is the hardest moment. Press back only after the pause is complete. Very low rep counts are appropriate.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 447,
  name: "Decline Push-Up | One Arm, Fingertip",
  sidequestKey: "Decline Push-Up | One Arm, One Leg",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
    { n: "Forearms",  p: true  },
    { n: "Obliques",  p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "forearms", "obliques"],
  diff: 8.0,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 4, elbow: 3, shoulder: 5, neck: 1, lowerBack: 3,
            knee: 0, fingers: 3, thoracic: 2, si: 1, hip: 2, groin: 0, ankle: 1, foot: 0 },
  strength: 5,
  mobility: 2,
  technique: 5,
  kcalPerRep: [0.48, 0.62],
  desc: "Decline one-arm push-up performed on the fingertips of the working hand. The decline angle amplifies the load through the finger flexor tendons on top of the already extreme anti-rotation demand, making this a high-risk, high-reward tendon and pressing strength drill for athletes who have fully exhausted both the decline one-arm and the floor fingertip push-up progressions.",
  cues: "Prerequisite: both the standard decline one-arm push-up and the two-arm decline fingertip push-up done cleanly. Execute with fingertips spread for maximum contact area. Torso bracing must be absolute. Stop at the first sign of sharp tendon discomfort.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 448,
  name: "Decline Push-Up | One Arm, 4-Finger",
  sidequestKey: "Decline Push-Up | One Arm",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
    { n: "Forearms",  p: true  },
    { n: "Obliques",  p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "forearms", "obliques"],
  diff: 7.5,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 4, elbow: 3, shoulder: 5, neck: 1, lowerBack: 3,
            knee: 0, fingers: 4, thoracic: 2, si: 1, hip: 2, groin: 0, ankle: 1, foot: 0 },
  strength: 5,
  mobility: 1,
  technique: 5,
  kcalPerRep: [0.49, 0.63],
  desc: "Decline one-arm push-up on four fingertips with the thumb folded under. This combination places the full decline unilateral load across four digits, pushing finger flexor tendon stress into the extreme range. Appropriate only after all lower steps in both the decline one-arm and two-arm finger reduction chains are fully mastered.",
  cues: "Thumb tucked under the palm, four fingers spread and planted. Execute with total torso control. Any deviation in hip or shoulder rotation multiplies the finger stress. Very low reps â€” one to three â€” per set is standard.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 449,
  name: "Decline Push-Up | One Arm, 3-Finger",
  sidequestKey: "Decline Push-Up | One Arm, One Leg",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
    { n: "Forearms",  p: true  },
    { n: "Obliques",  p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "forearms", "obliques"],
  diff: 8.2,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 4, elbow: 3, shoulder: 5, neck: 1, lowerBack: 3,
            knee: 0, fingers: 5, thoracic: 2, si: 1, hip: 2, groin: 0, ankle: 1, foot: 0 },
  strength: 5,
  mobility: 1,
  technique: 5,
  kcalPerRep: [0.50, 0.64],
  desc: "Decline one-arm push-up on three fingertips â€” index, middle, and ring. With thumb and pinkie lifted, the decline one-arm load concentrates across three digits, placing each individual tendon under a load fraction that exceeds most conventional strength exercises. Reserved for advanced athletes pursuing the outer boundary of finger-strength training.",
  cues: "Three fingers planted, others clear. Absolute anti-rotation throughout. Minimal depth is acceptable â€” tendon loading is the goal, not range. Cease immediately on any finger pain.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 450,
  name: "Decline Push-Up | One Arm, 2-Finger",
  sidequestKey: "Decline Push-Up | One Arm, One Leg",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
    { n: "Forearms",  p: true  },
    { n: "Obliques",  p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "forearms", "obliques"],
  diff: 8.8,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 5, elbow: 4, shoulder: 5, neck: 1, lowerBack: 3,
            knee: 0, fingers: 5, thoracic: 2, si: 1, hip: 2, groin: 0, ankle: 1, foot: 0 },
  strength: 5,
  mobility: 1,
  technique: 5,
  kcalPerRep: [0.50, 0.65],
  desc: "Decline one-arm push-up on two fingertips â€” typically index and middle â€” with three fingers clear. The two-digit distribution of the decline unilateral load is among the highest per-finger mechanical loads achievable in a push-up variant. Injury risk is extremely high; this is a near-limit demonstration of finger flexor tendon strength.",
  cues: "Only after decline one-arm three-finger is fully controlled. Index and middle finger only, others lifted. Minimal range. Complete torso rigidity. Stop on any sharp tendon sensation.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 451,
  name: "Decline Push-Up | One Arm, 1-Finger",
  hof: true,
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
    { n: "Forearms",  p: true  },
    { n: "Obliques",  p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "forearms", "obliques"],
  diff: 9.5,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 5, elbow: 4, shoulder: 5, neck: 1, lowerBack: 3,
            knee: 0, fingers: 5, thoracic: 2, si: 1, hip: 2, groin: 0, ankle: 1, foot: 0 },
  strength: 5,
  mobility: 1,
  technique: 5,
  kcalPerRep: [0.51, 0.66],
  desc: "Decline one-arm push-up balanced on a single finger â€” typically the middle or index finger. The full unilateral decline load flows through one digit, representing the maximum theoretical finger-load density achievable in any standard push-up format. This lies at the absolute outer boundary of documented human finger-strength capacity.",
  cues: "Prerequisite: decline one-arm two-finger controlled across multiple sessions. Single middle or index finger, all others off the surface. Shortest possible range of motion. Stop before any pain â€” this drill is about tendon adaptation, not reps.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 453,
  name: "Decline Push-Up | One Arm, Straddle",
  sidequestKey: "Incline Push-Up | One Arm",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
    { n: "Obliques",  p: true  },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "obliques"],
  diff: 5.5,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 2, shoulder: 4, neck: 1, lowerBack: 2,
            knee: 0, fingers: 0, thoracic: 1, si: 1, hip: 1, groin: 0, ankle: 1, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.32, 0.41],
  desc: "Decline push-up with one hand shifted significantly forward of standard width, placing disproportionate load on the lead arm while the feet remain elevated. The staggered hand position in the decline orientation increases shoulder and upper-chest bias on the forward arm even further than the flat-floor staggered version, making this a practical unilateral bridge step before attempting the full decline one-arm.",
  cues: "Set feet on the box. Place one hand a full hand-length ahead of standard width, the other at standard or slightly behind. The forward hand carries the majority of the work â€” feel that side working harder. Keep hips square and don't rotate toward the lead arm. Switch sides each set.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 454,
  name: "Decline Push-Up | One Arm, Fist",
  sidequestKey: "Decline Push-Up | One Arm",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
    { n: "Obliques",  p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "obliques"],
  diff: 6.7,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 3, shoulder: 5, neck: 1, lowerBack: 3,
            knee: 0, fingers: 1, thoracic: 2, si: 1, hip: 2, groin: 0, ankle: 1, foot: 0 },
  strength: 4,
  mobility: 2,
  technique: 4,
  kcalPerRep: [0.44, 0.57],
  desc: "Decline one-arm push-up performed on a closed fist, keeping the working wrist in a neutral position. The decline angle substantially amplifies wrist-extension stress at high loads, so the fist position removes that joint vulnerability entirely while preserving the full unilateral pressing and anti-rotation demand of the decline one-arm.",
  cues: "Feet on the box. Working hand closed in a firm fist, knuckles down, wrist straight. Free arm behind the back. Lower with the same total-body bracing and rotation control as the standard decline one-arm â€” the only change is the wrist angle. Use a padded surface for the knuckles if needed.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 455,
  name: "Decline Push-Up | One Arm, Knuckle",
  sidequestKey: "Decline Push-Up | One Arm",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
    { n: "Obliques",  p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "obliques"],
  diff: 6.7,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 1, elbow: 3, shoulder: 5, neck: 1, lowerBack: 3,
            knee: 0, fingers: 1, thoracic: 2, si: 1, hip: 2, groin: 0, ankle: 1, foot: 0 },
  strength: 4,
  mobility: 2,
  technique: 4,
  kcalPerRep: [0.44, 0.57],
  desc: "Decline one-arm push-up on the knuckles of the working hand, wrist held neutral and forearm roughly vertical. The steep decline angle makes wrist extension under heavy unilateral load particularly stressful; the knuckle position removes this entirely, allowing athletes with wrist sensitivity to train the decline one-arm pattern without joint compromise.",
  cues: "Feet on the box. Working hand knuckle-down, wrist stacked vertically â€” don't let it flex or extend during the rep. Free arm behind the back. Execute identically to the standard decline one-arm. A padded floor surface under the knuckles reduces discomfort.",
  equipment: "None",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 456,
  name: "Decline Push-Up | One Arm, Closed Legs",
  sidequestKey: "Decline Push-Up | One Arm",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
    { n: "Obliques",  p: true  },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "obliques"],
  diff: 7.8,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 3, elbow: 3, shoulder: 5, neck: 1, lowerBack: 3,
            knee: 0, fingers: 0, thoracic: 2, si: 2, hip: 2, groin: 0, ankle: 1, foot: 0 },
  strength: 5,
  mobility: 2,
  technique: 5,
  kcalPerRep: [0.45, 0.58],
  desc: "Decline one-arm push-up with both feet touching together on the elevated surface. Closing the feet collapses the lateral support base, adding a powerful lateral-tipping moment to the already extreme anti-rotation demand of the decline one-arm position. The combined challenge to the obliques, hip stabilisers, and shoulder places this near the outer limit of two-arm-contact-free decline pressing.",
  cues: "Set feet together on the box â€” ankles touching. Place working hand under the center of the chest, free arm behind the back. Brace obliques and core maximally before lowering â€” the narrow foot base and missing arm create a compound rotation tendency. Any uncontrolled rotation means you need to widen the feet first.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
},

{
  id: 457,
  name: "Decline Push-Up | One Arm, One Leg",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true  },
    { n: "Chest",     p: true  },
    { n: "Triceps",   p: true  },
    { n: "Core",      p: true  },
    { n: "Obliques",  p: true  },
    { n: "Glutes",    p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "core", "obliques", "glutes"],
  diff: 8.0,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 3, elbow: 3, shoulder: 5, neck: 1, lowerBack: 4,
            knee: 0, fingers: 0, thoracic: 2, si: 2, hip: 3, groin: 0, ankle: 1, foot: 0 },
  strength: 5,
  mobility: 2,
  technique: 5,
  kcalPerRep: [0.48, 0.62],
  desc: "Decline one-arm push-up with one foot lifted off the elevated surface, leaving a diagonal two-point base â€” one hand on the floor and the contralateral foot on the box. The removed foot eliminates a major stabilizing contact, forcing the glutes, hip stabilisers, obliques, and spinal erectors to resist both a lateral-tipping and a rotational moment simultaneously on top of the extreme unilateral pressing load of the decline one-arm.",
  cues: "Set feet on the box in a standard decline one-arm setup, then lift the same-side foot as the working arm â€” support runs diagonally. Brace absolutely against the compound tendency to tip and rotate before you lower. Minimal rep depth is acceptable; control is the priority. Work both diagonals equally. This is an elite demonstration drill.",
  equipment: "Elevated Surface",
  position: "Prone",
  youtube: "LINK_TODO"
}

);
