/* pushup-wall.js — extends the global pushups[] declared in pushup-standard.js */

pushups.push(

{
  id: 1,
  name: "Wall Push-Up | High",
  sidequestKey: "Wall Push-Up",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true },
    { n: "Chest",     p: false },
    { n: "Triceps",   p: false },
  ],
  tags: ["shoulders", "chest", "triceps"],
  diff: 0.1,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 1 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.09, 0.12],
  desc: "Hands placed above shoulder height on a wall with the body nearly vertical. Load is negligible â€” the anterior deltoid is the primary driver due to the elevated hand position. Suited to post-surgical rehab, elderly populations, or anyone for whom the standard wall push-up is still too demanding.",
  cues: "Stand close to the wall. Place hands above head, elbows soft. Shift chest toward the wall by bending the elbows, then press back. Keep hips under you â€” no arching.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 3,
  name: "Wall Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
  ],
  tags: ["chest", "shoulders", "triceps"],
  diff: 0.3,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.14, 0.18],
  desc: "Hands at shoulder height and width on a wall, body at a slight forward lean. The bodyweight fraction is very small, making joint stress minimal across the board. A.K.A. Standing Push-Up. The standard starting point before progressing to incline or floor variations.",
  cues: "Stand an arm's length from the wall. Hands at shoulder height, fingers pointing up. Lower chest toward the wall by bending the elbows, then press back to full extension. Body stays straight throughout.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 4,
  name: "Wall Push-Up | Wide",
  sidequestKey: "Wall Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: false },
    { n: "Triceps",   p: false },
  ],
  tags: ["chest", "shoulders", "triceps"],
  diff: 0.35,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.14, 0.18],
  desc: "Hands placed 1.5â€“2Ã— shoulder-width apart on the wall at shoulder height. The wider grip shifts emphasis toward the sternal head of the pectoralis major and increases the stretch at the bottom position. Elbow path flares outward, reducing tricep contribution.",
  cues: "Spread hands wider than standard â€” roughly as wide as a wide push-up on the floor. Elbows track outward as you lower. Control the chest tap and press back without letting the elbows collapse inward.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 5,
  name: "Wall Push-Up | Narrow",
  sidequestKey: "Wall Push-Up",
  alt: null,
  muscles: [
    { n: "Triceps",   p: true },
    { n: "Chest",     p: false },
    { n: "Shoulders", p: false },
  ],
  tags: ["triceps", "chest", "shoulders"],
  diff: 0.4,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.14, 0.18],
  desc: "Hands placed close together at shoulder height â€” thumbs nearly touching. The narrow grip shortens the moment arm at the shoulder and maximises tricep involvement through elbow extension.",
  cues: "Bring hands in until thumbs are almost touching beneath chest height. Elbows track back along the body as you lower â€” they should not flare out. Press to full lockout.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 62,
  name: "Wall Push-Up | Diamond",
  sidequestKey: null,
  alt: null,
  muscles: [
    { n: "Triceps",   p: true },
    { n: "Chest",     p: true },
    { n: "Shoulders", p: false },
  ],
  tags: ["triceps", "chest", "shoulders"],
  diff: 0.55,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.15, 0.19],
  desc: "Wall push-up with the index fingers and thumbs touching to form a diamond beneath the chest. The extreme grip narrowing pushes elbow extension demand and wrist loading past the standard narrow variation, concentrating the work almost entirely on the triceps even at wall-level load.",
  cues: "Form a diamond shape with thumbs and index fingers at chest height on the wall. Keep elbows tucked close to the ribs as you lower â€” they should brush the sides, not flare. Press through the diamond back to full extension.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 6,
  name: "Wall Push-Up | One Leg",
  sidequestKey: "Wall Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 0.45,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 1, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.14, 0.18],
  desc: "Standard wall push-up performed with one foot raised off the floor. Removing a contact point forces the core and hip stabilisers to work against rotation and lateral tilt throughout the set. Press mechanics are unchanged â€” the challenge is purely postural.",
  cues: "Set up as a standard wall push-up. Lift one foot a few inches off the floor before starting. Brace core, keep hips level, and don't allow the pelvis to rotate. Switch the raised leg each set.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 63,
  name: "Wall Push-Up | Straddle",
  sidequestKey: "Wall Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: true },
    { n: "Shoulders", p: false },
  ],
  tags: ["chest", "triceps", "shoulders"],
  diff: 0.25,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.13, 0.17],
  desc: "Standard wall push-up performed with the feet spread wide apart instead of together, widening the base of support. The broader stance lowers the anti-rotation demand on the core compared to the standard feet-together setup, making this the most stable stance in the wall family.",
  cues: "Feet spread wide apart, hands at standard shoulder-width on the wall. Lower the chest with control â€” the wide stance should feel notably more stable than feet together. Press back to full extension.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 8,
  name: "Wall Push-Up | Staggered",
  sidequestKey: "Wall Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 0.48,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.14, 0.18],
  desc: "One hand placed at standard shoulder height, the other 15â€“20 cm higher on the wall, creating an asymmetric pressing position. The lower hand operates at a steeper body angle, shifting proportionally more load to that side's pec and tricep. The mild unilateral bias accumulates across a set â€” alternate stagger direction each set.",
  cues: "Set up with hands shoulder-width apart, then slide one hand up and one down by a hand-length. Lower chest evenly toward the wall â€” both elbows bend, but the lower-hand elbow drives the majority of the press. Switch which hand is higher each set.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 7,
  name: "Wall Push-Up | Fingertip",
  sidequestKey: "Wall Push-Up | Diamond",
  alt: null,
  pathTag: "fingertip",
  pathNode: true,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
    { n: "Forearms",  p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms"],
  diff: 0.5,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 2, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.14, 0.18],
  desc: "Standard wall push-up performed on all five fingertips rather than a flat palm. The wall's vertical surface keeps absolute load low, making this the safest entry point for building finger and flexor tendon resilience. First step in the fingertip push-up progression.",
  cues: "Place all five fingertips on the wall â€” no palm contact. Fingers spread slightly, tips bearing full load. Press reps smoothly; stop if any finger joint feels sharp pain rather than normal tendon tension.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 9,
  name: "Wall Push-Up | T",
  sidequestKey: "Wall Push-Up | Diamond",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Biceps",    p: false },
  ],
  tags: ["chest", "shoulders", "biceps"],
  diff: 0.75,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 1, elbow: 1, shoulder: 2, neck: 0, lowerBack: 0,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.16, 0.21],
  desc: "Arms extended straight out to the sides at shoulder height, forming a T with the body. Elbows bend outward as the chest approaches the wall, mimicking a horizontal fly pattern. The pecs are loaded at a maximally lengthened position â€” shoulder joint demand is higher than standard.",
  cues: "Place hands on the wall with arms fully extended to each side at shoulder height â€” body forms a T shape. Bend elbows outward and lower until chest touches. Press back by squeezing the pecs, not by throwing the elbows inward.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 10,
  name: "Wall Push-Up | Low",
  sidequestKey: "Wall Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
  ],
  tags: ["chest", "shoulders", "triceps"],
  diff: 0.6,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.16, 0.21],
  desc: "Hands placed at chest height or lower on the wall with a more pronounced body lean than the standard variation. The steeper angle shifts a greater fraction of bodyweight into the press, meaningfully increasing pec and tricep demand while remaining a standing movement.",
  cues: "Step further from the wall than usual. Place hands at chest height, slightly wider than shoulders. Lean into the wall and lower under control â€” hips stay in line with shoulders, not sagging. Press back smoothly.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 11,
  name: "Wall Push-Up | 4-Finger",
  sidequestKey: "Wall Push-Up | Diamond",
  alt: null,
  pathTag: "fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
    { n: "Forearms",  p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms"],
  diff: 0.65,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 2, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.14, 0.18],
  desc: "Wall push-up on four fingertips, with the pinky removed from contact. Removing the weakest digit begins concentrating load across fewer tendons and joints. The absolute pressing load remains minimal; the training stimulus is almost entirely finger conditioning.",
  cues: "Tuck the pinky away and press on the remaining four fingertips. Keep fingers spread and tips firmly planted. Rep tempo should be slow and controlled â€” tendons adapt slower than muscle.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 12,
  name: "Wall Push-Up | Explosive",
  sidequestKey: "Wall Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
  ],
  tags: ["chest", "shoulders", "triceps", "power"],
  diff: 0.7,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.18, 0.24],
  desc: "Standard wall push-up performed with a maximal-speed concentric â€” the hands briefly leave the wall at the top. Trains rate of force development with near-zero injury risk due to the small load fraction. Entry-level plyometric push-up for those not yet ready for floor-based explosive variants.",
  cues: "Lower at a controlled pace, then drive off the wall as fast as possible. Let hands leave the surface. Catch the wall with soft elbows and flow into the next rep. Keep the body rigid â€” no hip pop on the drive.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 2,
  name: "Wall Push-Up | Pseudo Planche",
  sidequestKey: "Wall Push-Up | Diamond",
  alt: null,
  muscles: [
    { n: "Shoulders", p: true },
    { n: "Chest",     p: true },
    { n: "Triceps",   p: false },
    { n: "Serratus",  p: false },
  ],
  tags: ["shoulders", "chest", "triceps", "serratus"],
  diff: 1.3,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 2,
  technique: 2,
  kcalPerRep: [0.16, 0.21],
  desc: "Hands placed at hip height or below on the wall with fingers pointing downward or outward and a steep body lean. The depressed hand position shifts the shoulder into a planche-like orientation, loading the anterior deltoid and serratus anterior through a mechanically novel angle. The wall surface keeps the load manageable enough to drill the position without the wrist and shoulder demands of floor planche work.",
  cues: "Place hands well below shoulder height â€” roughly hip level â€” fingers angled downward. Lean into the wall until the body is at a steep diagonal. Lower with control; the sensation should be front-of-shoulder, not chest. Don't let the lower back arch.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 14,
  name: "Wall Push-Up | 3-Finger",
  sidequestKey: "Wall Push-Up | Diamond",
  alt: null,
  pathTag: "fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
    { n: "Forearms",  p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms"],
  diff: 0.8,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 1 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 3, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.14, 0.18],
  desc: "Wall push-up on the index, middle, and ring fingers only. Each removed digit meaningfully increases per-finger loading and flexor tendon stress. The wall surface keeps the pressing load manageable â€” this is still a tendon-conditioning drill, not a strength test.",
  cues: "Tuck both the pinky and one additional finger. Three fingertips only on the wall. Slow deliberate reps. Never push through joint pain.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 15,
  name: "Wall Push-Up | Clap",
  sidequestKey: "Wall Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
  ],
  tags: ["chest", "shoulders", "triceps", "power"],
  diff: 0.9,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.20, 0.26],
  desc: "Explosive wall push-up where the push generates enough airtime for a hand clap before catching the wall. Requires meaningfully more power output than the non-clap explosive variant â€” both hands must clear simultaneously and the catch timing must be controlled.",
  cues: "Drive off the wall with maximum force. Clap hands together at chest level while airborne, then return them to the wall before contact. Catch with slightly bent elbows â€” never locked â€” to absorb impact.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 64,
  name: "Wall Push-Up | Pause",
  sidequestKey: "Wall Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: false },
    { n: "Shoulders", p: false },
  ],
  tags: ["chest", "triceps", "shoulders"],
  diff: 0.32,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.13, 0.17],
  desc: "Standard wall push-up with a dead-stop pause closest to the wall before pressing back out, removing the elastic rebound of the standard tempo. The momentary hold makes the press noticeably harder to initiate despite the minimal wall-level load, building strength out of the weakest point in the range.",
  cues: "Lower under control and stop completely closest to the wall â€” no bounce off the surface. Hold for one to two full seconds, staying tight through the core, then press back out from a dead stop. Reset fully on every rep.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 200,
  name: "Wall Push-Up | Negative",
  sidequestKey: "Wall Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: false },
    { n: "Shoulders", p: false },
  ],
  tags: ["chest", "triceps", "shoulders"],
  diff: 0.25,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.11, 0.15],
  desc: "Standard wall push-up performed with a 3â€“5 second eccentric only, no drive on the concentric â€” reset at arm's length between reps. Extending time under tension on the lowering phase builds control ahead of standard tempo, without adding any meaningful new load given how small the wall-level fraction already is.",
  cues: "Lower toward the wall over a full 3â€“5 second count, resisting the descent the entire way. Either press back out normally or reset from the wall â€” the eccentric is the trained portion. Keep the tempo consistent rep to rep rather than rushing the final inches.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 16,
  name: "Wall Push-Up | Archer",
  sidequestKey: "Wall Push-Up | Diamond",
  alt: null,
  pathTag: "one-arm",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 1.0,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.20, 0.26],
  desc: "One arm bends to bring the chest toward the wall while the other arm extends straight to the side, acting as a guide rail with minimal load. The bending arm handles the majority of the press, making this an asymmetric loading drill. Alternate arms each rep or set. A direct stepping stone toward one-arm wall push-ups.",
  cues: "Hands wide on the wall. Shift weight to one side and bend that elbow â€” the other arm stays nearly straight, just touching the wall for balance. Lower, press back through the bent arm, and shift to the other side.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 13,
  name: "Wall Push-Up | Typewriter",
  sidequestKey: "Wall Push-Up | Diamond",
  alt: null,
  pathTag: "one-arm",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 1.2,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.20, 0.26],
  desc: "Hands placed wide on the wall. Lower to one side by bending one elbow fully while the other arm stays extended, then slide the body laterally across until the bent elbow is fully extended and the other arm is now bent â€” hands remain on the wall throughout. Each pass loads the pressing-side shoulder close to one-arm intensity at the end range, while demanding continuous scapular control across the sweep.",
  cues: "Start wide. Lower to one side first, then slide laterally in one fluid motion without returning to centre. Maintain contact with the wall the entire time â€” this is a sliding press, not an alternating Archer. Keep the hips level and core braced throughout the sweep.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 17,
  name: "Wall Push-Up | 2-Finger",
  sidequestKey: "Wall Push-Up | Diamond",
  alt: null,
  pathTag: "fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
    { n: "Forearms",  p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms"],
  diff: 1.1,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 1 },
  end:  { suit: true,  eff: 1 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 4, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.16, 0.21],
  desc: "Wall push-up on the index and middle fingers only. Two fingers per hand bear the full pressing load, placing substantial stress on the flexor tendons and proximal interphalangeal joints. Progress here should be slow and conservative â€” tissue adaptation lags well behind strength.",
  cues: "Index and middle finger only on the wall, remaining fingers curled away. Reps must be deliberate â€” no bouncing. Train this infrequently and never to form breakdown. Stop at first sign of joint discomfort.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 19,
  name: "Wall Push-Up | 1-Finger",
  sidequestKey: "Wall Push-Up | Diamond",
  alt: null,
  pathTag: "fingertip",
  pathNode: true,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
    { n: "Forearms",  p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms"],
  diff: 1.6,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 5, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.16, 0.21],
  desc: "Wall push-up on a single index finger per hand. The entire pressing load routes through one digit â€” despite the minimal pressing resistance of a wall push-up, the per-finger tendon load is elite-level. Wall surface is the only viable way to train this safely in a pressing pattern.",
  cues: "Index finger only, pointing straight up the wall. All other fingers and the palm clear the surface entirely. Even a few reps per session is sufficient. Treat this as tendon work, not conditioning â€” rest is part of the stimulus.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 20,
  name: "Wall Push-Up | One Arm",
  alt: null,
  pathTag: "one-arm",
  pathNode: true,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 1.5,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.20, 0.26],
  desc: "One hand centred on the wall at shoulder height, the other held behind the back or at the side. Removing bilateral assistance doubles the unilateral pressing demand and introduces substantial anti-rotation load through the shoulder girdle and core. A practical stepping stone before one-arm floor work.",
  cues: "Stand at arm's length. Place one hand at the centre of the wall at shoulder height. Brace the core firmly against rotation before each rep. Lower slowly and press back â€” the torso should not twist.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 21,
  name: "Wall Push-Up | One Arm, Low",
  sidequestKey: "Wall Push-Up | One Arm",
  alt: null,
  pathTag: "one-arm",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 1.8,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 2, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.22, 0.29],
  desc: "One-arm wall push-up with the hand placed at chest height rather than shoulder height, forcing a more pronounced body lean. The steeper angle increases the loaded fraction of bodyweight substantially â€” this sits at the top of the wall push-up family and is a genuine bridge to incline one-arm floor work.",
  cues: "Step back further than the standard one-arm variant. Hand at chest height, body at a steep lean. Anti-rotation demand is high â€” brace hard before each rep. Control the lower; don't let the hip hike or shoulder drop.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 22,
  name: "Wall Push-Up | One Arm, Fingertip",
  alt: null,
  pathTag: "one-arm-fingertip",
  pathNode: true,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Forearms",  p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms", "core"],
  diff: 2.0,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 2, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.20, 0.26],
  desc: "One-arm wall push-up performed on all five fingertips. Combines unilateral pressing demand with full finger loading â€” the two independent skill axes compound. The wall surface remains the only viable context in which this combination is safe to train with any volume.",
  cues: "One hand on the wall, fingertips only, palm clear. Other hand behind the back. Brace hard against rotation. Reps are slow and deliberate â€” this is simultaneously a shoulder, core, and tendon training drill.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 23,
  name: "Wall Push-Up | One Arm, 4-Finger",
  sidequestKey: "Wall Push-Up | One Arm, Fingertip",
  alt: null,
  pathTag: "one-arm-fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Forearms",  p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms", "core"],
  diff: 2.2,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 2, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.20, 0.26],
  desc: "One-arm wall push-up on four fingertips, pinky removed. The unilateral load now routes through four digits on one hand, compounding pressing and tendon stress. A niche but legitimate progression step between one-arm fingertip and three-finger variants.",
  cues: "Pinky off the wall, four fingertips bearing load. One arm, other hand behind back. Anti-rotation brace is mandatory before each rep. Volume should be low â€” 3â€“5 reps maximum per session.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 24,
  name: "Wall Push-Up | One Arm, 3-Finger",
  sidequestKey: "Wall Push-Up | One Arm, Fingertip",
  alt: null,
  pathTag: "one-arm-fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Forearms",  p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms", "core"],
  diff: 2.6,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 3, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.20, 0.26],
  desc: "One-arm wall push-up on three fingertips. Each rep concentrates the full unilateral press through three digits, placing extreme flexor tendon stress despite the wall's reduced load. A highly specialised drill â€” this exists almost entirely as a finger strength protocol.",
  cues: "Three fingertips only â€” index, middle, ring. One arm, palm clear, other hand away. Brace the entire body before each rep. This is not a conditioning exercise â€” treat each rep as a maximum-effort tendon stimulus.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 25,
  name: "Wall Push-Up | One Arm, 2-Finger",
  sidequestKey: "Wall Push-Up | One Arm, 1-Finger",
  alt: null,
  pathTag: "one-arm-fingertip",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Forearms",  p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms", "core"],
  diff: 3.1,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 4, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.20, 0.26],
  desc: "One-arm wall push-up on two fingertips â€” index and middle finger of one hand. The per-digit tendon load at this point is genuinely extreme, even on a wall. Very few practitioners can sustain any volume here without a significant long-term conditioning base.",
  cues: "Index and middle fingertip only. All remaining digits and palm clear of the wall. Other hand behind back. One or two reps per set maximum. Rest several days between sessions targeting this movement.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 26,
  name: "Wall Push-Up | One Arm, 1-Finger",
  alt: null,
  pathTag: "one-arm-fingertip",
  pathNode: true,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Forearms",  p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "forearms", "core"],
  diff: 3.1,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 5, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.22, 0.29],
  desc: "One-arm wall push-up on a single index finger. The theoretical ceiling of standing push-up variations â€” even on a wall, concentrating a unilateral press through one digit demands extraordinary tendon integrity. Documented examples are extraordinarily rare.",
  cues: "One index fingertip centred on the wall. Every other contact point removed. Other hand behind back. A single rep with full control is the standard. Years of progressive tendon conditioning are the prerequisite â€” not strength.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 201,
  name: "Wall Push-Up | Knuckle",
  sidequestKey: "Wall Push-Up | Diamond",
  alt: null,
  pathTag: "knuckle",
  pathNode: true,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: false },
    { n: "Shoulders", p: false },
  ],
  tags: ["chest", "triceps", "shoulders"],
  diff: 0.39,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 0, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.14, 0.18],
  desc: "Standard wall push-up performed on the proximal knuckle row of a loosely closed fist instead of a flat palm, placing the wrist in a neutral position. Eliminating wrist extension makes this a common rehab and wrist-pain alternative â€” the pressing pattern and load are otherwise identical to the standard Wall Push-Up.",
  cues: "Make a loose fist and press the knuckle row into the wall, wrist straight. Perform the rep exactly as a standard Wall Push-Up â€” the only change is the contact surface. Keep the fist consistently aligned; don't let the wrist roll inward.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 202,
  name: "Wall Push-Up | Fist",
  sidequestKey: "Wall Push-Up | Diamond",
  alt: null,
  pathTag: "knuckle",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Triceps",   p: false },
    { n: "Shoulders", p: false },
  ],
  tags: ["chest", "triceps", "shoulders"],
  diff: 0.45,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 0, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.14, 0.18],
  desc: "Wall push-up on a fully closed fist, contacting the wall with the flat of the knuckles and the side of the index finger metacarpal. The tightly closed grip demands sustained forearm tension to keep the fist stable, adding a low-level grip conditioning stimulus absent in the knuckle variant. Wrist remains fully neutral â€” the more stable of the two closed-hand variations.",
  cues: "Close the fist tightly and press the flat knuckle surface into the wall. Wrist absolutely straight â€” no bend in either direction. Grip hard throughout the set; a loosening fist is the first sign of fatigue. Otherwise identical to the standard Wall Push-Up.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 203,
  name: "Wall Push-Up | One Arm, Knuckle",
  sidequestKey: "Wall Push-Up | One Arm",
  alt: null,
  pathTag: "knuckle",
  pathNode: true,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 1.9,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 0, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.20, 0.26],
  desc: "One-arm wall push-up performed on the proximal knuckle row, keeping the wrist neutral under unilateral load. The narrower contact point than a flat palm adds a small lateral balance demand on top of the anti-rotation requirement already present in the one-arm wall variant.",
  cues: "Loose fist, knuckle row on the wall, wrist straight. One arm only, other hand behind the back. Brace the core firmly against rotation before each rep. Don't let the wrist angle in or out under load.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 204,
  name: "Wall Push-Up | One Arm, Fist",
  sidequestKey: "Wall Push-Up | One Arm, Fingertip",
  alt: null,
  pathTag: "knuckle",
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 2.0,
  str:  { suit: true,  eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 0, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.20, 0.26],
  desc: "One-arm wall push-up on a fully closed fist. The tight grip demands sustained forearm co-contraction to maintain fist rigidity while simultaneously managing anti-rotation under unilateral load â€” two concurrent stabilisation tasks. Slightly harder than the knuckle variant because fist integrity must be actively maintained throughout every rep.",
  cues: "Close the fist tightly before taking the position â€” grip should be pre-set, not adjusted mid-rep. Wrist straight. One arm, other hand away. Brace the core against rotation and keep the fist rigid from start to finish.",
  equipment: "None",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 65,
  name: "Wall Push-Up | (Bar)",
  sidequestKey: "Wall Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
  ],
  tags: ["chest", "shoulders", "triceps"],
  diff: 0.28,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.13, 0.17],
  desc: "Wall push-up performed gripping a pair of push-up bars mounted or held against the wall, keeping the wrists in a neutral position instead of full extension. The neutral grip slightly reduces wrist stress versus the flat-wall version, with no real change to the minimal pressing difficulty.",
  cues: "Hold the bars at shoulder-width against the wall. Grip neutrally and lower with control â€” the wrists stay straight throughout. Press back to full extension, keeping the same body angle as a standard Wall Push-Up.",
  equipment: "Push-Up Bars",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 66,
  name: "Wall Push-Up | (Parallettes)",
  sidequestKey: "Wall Push-Up | Diamond",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
  ],
  tags: ["chest", "shoulders", "triceps"],
  diff: 0.5,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 2,
  technique: 1,
  kcalPerRep: [0.15, 0.19],
  desc: "Wall push-up performed gripping a pair of parallettes braced against the wall, combining a neutral grip with a deeper chest path toward the wall than the flat-hand version allows. As with the floor Push-Up, the added stretch on the pecs and front shoulder outweighs the wrist-angle benefit, making this slightly harder than the standard Wall Push-Up despite the more comfortable grip.",
  cues: "Brace the parallettes against the wall at shoulder-width. Lower the chest further toward the wall than a flat-hand rep allows, feeling the deeper stretch through the pecs and front shoulder. Press back to full extension without letting the hips sag.",
  equipment: "Parallettes",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 67,
  name: "Wall Push-Up | (Rings)",
  sidequestKey: "Wall Push-Up | Diamond",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: true },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 1.05,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 1, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.16, 0.21],
  desc: "Wall push-up performed gripping a pair of gymnastic rings anchored at wall height, adding full three-dimensional rotational instability on top of the minimal wall-level load. The rings must be actively stabilized through the entire rep â€” turning out at the bottom and squeezing in at the top â€” which adds meaningful technical demand even though the raw pressing load stays low.",
  cues: "Anchor the rings at chest height against the wall. Grip firmly and turn the rings out slightly as you lower toward the wall. Press back to full extension while actively rolling the rings inward to stay stable â€” don't let them swing.",
  equipment: "Rings",
  position: "Standing",
  youtube: "LINK_TODO"
},

{
  id: 205,
  name: "Wall Push-Up | (TRX)",
  sidequestKey: "Wall Push-Up",
  alt: null,
  muscles: [
    { n: "Chest",     p: true },
    { n: "Shoulders", p: true },
    { n: "Triceps",   p: false },
    { n: "Core",      p: false },
  ],
  tags: ["chest", "shoulders", "triceps", "core"],
  diff: 0.65,
  str:  { suit: true,  eff: 1 },
  vol:  { suit: true,  eff: 2 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.16, 0.21],
  desc: "Wall push-up performed gripping a pair of suspension trainer handles anchored at wall height, adding light instability on top of the minimal wall-level load. The straps drift more than a fixed surface but far less than rings, giving a mild stabilization demand suited as a stepping stone before progressing to ring-based wall work.",
  cues: "Set the straps to hover at chest height against the wall, handles level. Grip and lower with control, keeping them from swinging side to side. Press back to full extension while resisting any drift in the straps.",
  equipment: "TRX",
  position: "Standing",
  youtube: "LINK_TODO"
},

);
