/* ─────────────────────────────────────────────────────────────────────────
 * NAMING RULE
 * Format: [modifier] [family] | [extra modifier] (equipment)
 *
 * - Modifiers always go before the family name.
 * - Base variation: use "Standard" or "Strict".
 * - Omit equipment if it's the default (floor for push-ups, bar for pull-ups).
 *   Only include it when non-default.
 *
 * ✓ One Arm Push-Up | Fingertips (bar)
 * ✗ Push-Up | One Arm
 *
 * ─────────────────────────────────────────────────────────────────────────
 *
 * DIFFICULTY REFERENCE (scale 1–10)
 * 1. Standard Push-Up     — 3.0
 * 2. Archer Push-Up       — 6.3
 * 3. Tuck Planche         — 6.0
 * 4. Chin-Up              — 3.8
 * 5. Archer Pull-Up       — 6.5
 * 6. Straddle Planche     — 8.5
 *
 * ─────────────────────────────────────────────────────────────────────────
 *
 * HALL OF FAME (HoF)
 * Do not mark any move as HoF unless it is fully achieved.
 * If uncertain, ask before tagging.
 * ───────────────────────────────────────────────────────────────────────── */

const chinupData = [
{
  id: 1,
  name: "Chin-Up | (Band)",
  alt: null,
  pathTag: "one-arm-chin",
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Rear Delts", p: false },
  ],
  tags: ["chin-up", "back", "biceps", "shoulders"],
  diff: 2.5,
  str:  { suit: false, eff: 2 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: true,  eff: 4 },
  joints: { wrist: 0, elbow: 0, shoulder: 0, neck: 0, lowerBack: 0,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.10, 0.18],
  desc: "A chin-up performed with a supinated (underhand, palms-toward-you) grip, with a resistance band looped over the bar and placed under the feet or knees to reduce the effective load. The band provides the most assistance at the bottom of the pull — exactly where most beginners are weakest — making it the preferred entry point for athletes who cannot yet complete a single unassisted chin-up. The supinated position keeps the biceps in their strongest mechanical line of pull throughout.",
  cues: "Loop the band over the bar and step or kneel into it before gripping the bar shoulder-width with palms facing toward you. Depress the scapulae before the first pull. Use the lightest band that still allows clean form through the full range, and progress to lighter bands over time.",
  equipment: "Pull-up bar + resistance band",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 29,
  name: "Jumping Chin-Up",
  alt: null,
  pathTag: "one-arm-chin",
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Rear Delts", p: false },
  ],
  tags: ["chin-up", "back", "biceps", "shoulders"],
  diff: 1.2,
  str:  { suit: false, eff: 1 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: true,  eff: 4 },
  joints: { wrist: 0, elbow: 0, shoulder: 0, neck: 0, lowerBack: 0,
            knee: 1, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 1, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.12, 0.22],
  desc: "A chin-up performed with a supinated (underhand, palms-toward-you) grip in which a small bend-and-extend of the legs supplies a continuous upward assist on every single rep, rather than the constant assistance a band provides. The equipment-free alternative to the Chin-Up | (Band) — useful when no band is available — though the assistance is less consistent rep to rep, since it depends on jump timing rather than a fixed elastic curve. The grip and pulling pattern are otherwise identical to a standard chin-up.",
  cues: "Stand under the bar, grip shoulder-width with palms facing toward you. Bend the knees slightly, then extend through the legs at the same moment you begin the pull, timing the jump to assist — not replace — the pull. Land softly between reps. As pulling strength improves, reduce the jump until the rep becomes a true unassisted chin-up.",
  equipment: "Pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 3,
  name: "Scapular Chin-Up",
  alt: null,
  muscles: [
    { n: "Lats",        p: true  },
    { n: "Rear Delts",  p: false },
    { n: "Rhomboids",   p: false },
  ],
  tags: ["chin-up", "back", "shoulders"],
  diff: 2,
  str:  { suit: false, eff: 1 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 0, elbow: 0, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.05, 0.09],
  desc: "From a full supinated (underhand) dead hang, the body is elevated 5–8 cm by depressing and retracting the scapulae only — the elbows remain completely straight throughout. This isolates the scapular initiation that every well-performed chin-up rep should begin with. Beginners who skip this initiating movement tend to pull with the arms alone, losing lat activation and placing excess load on the biceps tendon. A.K.A. Scapular Pull-Up, Supinated Scapular Retraction.",
  cues: "Hang at full arm extension, palms facing toward you. Without bending the elbows, draw the shoulder blades down and back as if pulling them into your back pockets — the body rises a few centimetres. Slowly return to the dead hang. If the elbows bend at any point, it has converted into the start of a chin-up.",
  equipment: "Pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 4,
  name: "Slow Negative Chin-Up",
  sidequestKey: "Chin-Up",
  alt: null,
  pathTag: "one-arm-chin",
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Rear Delts", p: false },
  ],
  tags: ["chin-up", "back", "biceps"],
  diff: 3.5,
  str:  { suit: true,  eff: 3 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: false, eff: 2 },
  joints: { wrist: 0, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 0, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.15, 0.27],
  desc: "Step or jump to the chin-over-bar top position using a supinated (underhand, palms-toward-you) grip, then lower under full control to a dead hang as slowly as possible. Muscles are significantly stronger in the eccentric phase than the concentric, so athletes who cannot yet pull up can still train meaningful tension with this method. The supinated forearm places the biceps in a mechanically advantageous eccentric position throughout the descent. Target 5–8 seconds per rep. A key regression before full chin-ups are achievable.",
  cues: "Use a box to reach the top — do not exhaust yourself in the jump. Grip the bar with palms facing toward you. Release the box and resist the descent the entire way down, keeping the palms-toward-you position locked throughout. Do not allow the grip to rotate mid-descent. Control to a full dead hang, then step back up.",
  equipment: "Pull-up bar + box or jump to reach top",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 31,
  name: "One-Arm Scapular Pull",
  sidequestKey: "One-Arm Australian Pull-Up | (Low Bar)",
  alt: null,
  pathTag: "one-arm-chin",
  muscles: [
    { n: "Lats",       p: true  },
    { n: "Rear Delts", p: false },
    { n: "Rhomboids",  p: false },
    { n: "Core",       p: false },
  ],
  tags: ["chin-up", "back", "shoulders", "core"],
  diff: 4.8,
  str:  { suit: false, eff: 2 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 0, elbow: 0, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 1, thoracic: 0, si: 1, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 1,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.08, 0.14],
  desc: "The single-arm version of the Scapular Pull-Up: from a one-arm dead hang in a supinated (palms-toward-you) grip, the body is raised a few centimetres by depressing and retracting the scapula alone — the elbow stays completely straight throughout. Loading the full bodyweight through one shoulder roughly doubles the relative demand on that side compared to the bilateral version, and the free arm must actively resist the torso's tendency to rotate or swing toward the working side. Considered an essential prerequisite before any unilateral pulling work, since it builds the scapular stability the shoulder needs to handle one-arm loading safely.",
  cues: "Hang from one arm, palm facing toward you, the other arm relaxed or resting on the chest. Without bending the elbow, draw the shoulder blade down and back to lift the body a few centimetres. Actively resist any rotation of the torso toward the working side. Lower under control back to the one-arm dead hang. Train each side independently before progressing to One-Arm Lock-Offs.",
  equipment: "Pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

// ── FAMILY: HORIZONTAL ──
// Supinated inverted row variants performed under a low bar. Body is horizontal
// or near-horizontal, heels on the floor, pulling the chest up to the bar.
// Load is scaled by body angle — more horizontal = harder.

// ── FAMILY: STANDARD ──
// The core bilateral supinated pull-up variants — standard, close, and wide
// grip widths. All use a supinated (underhand, palms-toward-you) grip on a
// fixed overhead bar and pull from a dead hang to chin-over-bar.

{
  id: 6,
  name: "Chin-Up",
  alt: null,
  pathTag: "one-arm-chin",
  pathNode: true,
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Rear Delts", p: false },
    { n: "Core",       p: false },
  ],
  tags: ["chin-up", "back", "biceps", "shoulders"],
  diff: 3.8,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: true,  eff: 4 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 0, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.21, 0.38],
  desc: "A vertical pulling movement performed with a supinated (underhand, palms-toward-you) grip at shoulder width. The supinated forearm places the biceps in their mechanically optimal line of pull, making this the most accessible vertical pull-up variant for most people and the standard entry point before progressing to pronated pull-ups. Lat recruitment is nearly identical to the pronated pull-up despite the different grip. Pull from a complete dead hang until the chin clears the bar — no partial reps.",
  cues: "Grip the bar shoulder-width with palms facing toward you. Initiate by depressing the scapulae before bending the elbows. Pull the elbows down and back — not just down. Reach full elbow extension at the bottom of every rep and bring the chin clearly over the bar at the top.",
  equipment: "Pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 7,
  name: "Close Chin-Up",
  sidequestKey: "Chin-Up",
  alt: null,
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: false },
    { n: "Brachialis", p: false },
  ],
  tags: ["chin-up", "back", "biceps"],
  diff: 3.6,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: true,  eff: 4 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 0, elbow: 2, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 1,
  kcalPerRep: [0.20, 0.36],
  desc: "A chin-up performed with the hands placed close together — thumbs nearly touching — in a supinated (underhand, palms-toward-you) grip. The narrow supinated position puts the biceps in their most mechanically advantageous alignment: fully supinated forearm, elbow directly under the bar, maximising peak contraction at the top. This produces the highest bicep activation of any pull-up variation and is the closest bodyweight analogue to a barbell curl. Elbow loading is elevated versus standard width due to the more direct line of pull. A.K.A. Narrow Chin-Up.",
  cues: "Bring the hands in until thumbs are almost touching beneath the bar. Grip with palms facing toward you. Initiate with a scapular depression, then drive the elbows straight back and keep them close to the torso throughout the pull. Squeeze hard at the top — the close grip makes a full peak bicep contraction accessible. Lower to full dead hang each rep.",
  equipment: "Pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 8,
  name: "Wide Chin-Up",
  sidequestKey: null,
  alt: null,
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Brachialis", p: false },
    { n: "Rear Delts", p: false },
  ],
  tags: ["chin-up", "back", "biceps", "shoulders"],
  diff: 4.2,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: true,  eff: 4 },
  end:  { suit: true,  eff: 2 },
  joints: { wrist: 0, elbow: 1, shoulder: 2, neck: 0, lowerBack: 0,
            knee: 0, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.23, 0.41],
  desc: "A chin-up performed with the hands placed wider than shoulder-width in a supinated (underhand, palms-toward-you) grip on a wide bar. The wider stance reduces the mechanical advantage of the biceps compared to standard-width, increasing the relative lat demand while still benefiting from the supinated pull line. Front deltoid and brachialis activation are elevated versus the standard chin-up. The wider grip means the forearm is less perfectly aligned with the line of pull, making this marginally harder than the standard chin-up.",
  cues: "Spread hands to roughly 1.5× shoulder width on a wide bar, palms facing toward you. The elbows will track further out than in a standard chin-up — resist the urge to let them fully flare forward. Drive the elbows down and back. Lower to a full dead hang each rep.",
  equipment: "Wide pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 22,
  name: "Paused Chin-Up",
  sidequestKey: "Wide Chin-Up",
  alt: null,
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Rear Delts", p: false },
    { n: "Core",       p: false },
  ],
  tags: ["chin-up", "back", "biceps", "shoulders"],
  diff: 4.3,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: true,  eff: 5 },
  end:  { suit: false, eff: 2 },
  joints: { wrist: 0, elbow: 2, shoulder: 2, neck: 0, lowerBack: 0,
            knee: 0, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 2,
  kcalPerRep: [0.24, 0.43],
  desc: "A standard supinated (underhand, palms-toward-you) chin-up with a deliberate 1–3 second dead-stop pause held with the chin clearly over the bar on every single rep, before lowering under control. Removing the stretch-reflex and momentum carryover at the top forces the biceps and lats to control the hardest portion of the range purely under tension, increasing strength and hypertrophy stimulus relative to a touch-and-go rep at the same load. Distinct from the Flex Hang, which is a single sustained hold reached by jumping or stepping up rather than a rep-based pattern with a pause inserted between full concentric and eccentric phases.",
  cues: "Pull to a full chin-over-bar position as in a standard chin-up. At the top, hold completely still — no bouncing, no momentum — for a full 1 to 3 seconds before beginning the descent. Keep the scapulae depressed throughout the pause; do not let the shoulders creep up toward the ears. Lower under full control to a dead hang each rep.",
  equipment: "Pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

// ── FAMILY: ADVANCED ──
// Bilateral supinated pull-up variants that add equipment instability, leg
// position demands, mixed grip orientation, or a lateral power component.
// All harder than the standard Chin-Up family but do not yet require
// unilateral pulling strength.

{
  id: 9,
  name: "Chin-Up | (Rings)",
  sidequestKey: "Wide Chin-Up",
  alt: null,
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Core",       p: false },
    { n: "Rear Delts", p: false },
  ],
  tags: ["chin-up", "back", "biceps", "shoulders", "core"],
  diff: 4.8,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: true,  eff: 4 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 1, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.24, 0.43],
  desc: "A chin-up performed on gymnastic rings held in a strict supinated (underhand, palms-toward-you) grip throughout the entire movement, without allowing the rings to rotate. The rings will want to rotate toward a neutral position — resisting this throughout the set adds a forearm and wrist stability component absent in fixed-bar chin-ups. The rings +0.7 equipment bonus reflects this added stabilisation demand. Distinct from the neutral or auto-rotating ring pull-up.",
  cues: "Grip the rings with palms firmly facing toward you before the first rep and resist any rotation throughout every rep. Depress the scapulae, then pull the elbows down and back. If the rings rotate freely, actively work the forearms to hold the supinated lock. Lower to a full hang each rep.",
  equipment: "Gymnastic rings",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 23,
  name: "Towel Chin-Up",
  alt: null,
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Forearms",   p: true  },
    { n: "Rear Delts", p: false },
  ],
  tags: ["chin-up", "back", "biceps", "shoulders", "grip"],
  diff: 5,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: true,  eff: 4 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 2, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 4, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.25, 0.45],
  desc: "A chin-up performed gripping a towel (or two separate towels) draped over the bar instead of the bar itself, hands held in a supinated-equivalent palms-toward-you orientation around the fabric. The compliant, rounded grip removes any rigid purchase point and demands continuous crushing grip and forearm activation to prevent slipping, on top of the normal supinated pulling demand. The thicker effective grip diameter and lack of a fixed hand position also adds a forearm-stability component absent from a bar or ring chin-up. Best trained once standard chin-ups are comfortable for multiple reps.",
  cues: "Drape one long towel or two shorter towels over the bar, leaving even lengths on each side. Grip the fabric firmly with a crushing grip, palms facing each other or toward you. Initiate with a scapular depression as in a standard chin-up, then pull the elbows down and back, actively resisting any rotation or slipping of the towel in your hands. Lower under control to a full hang each rep — do not let grip fatigue turn the descent into a drop.",
  equipment: "Pull-up bar + hanging band / towel loop",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 10,
  name: "Commando Chin-Up",
  sidequestKey: "Wide Chin-Up",
  alt: null,
  muscles: [
    { n: "Lats",       p: true  },
    { n: "Biceps",     p: true  },
    { n: "Core",       p: false },
    { n: "Rear Delts", p: false },
  ],
  tags: ["chin-up", "back", "biceps", "core"],
  diff: 4.8,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: true,  eff: 3 },
  joints: { wrist: 1, elbow: 2, shoulder: 1, neck: 0, lowerBack: 1,
            knee: 0, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.26, 0.47],
  desc: "Performed with the hands side by side on the bar, running lengthwise — bar parallel to the face — with the forward hand in a supinated (underhand) grip and the rear hand in a pronated (overhand) grip. The supinated leading hand increases bicep involvement and shifts the pulling line, creating asymmetric muscle demand across the two arms. The torso must resist the rotational pull produced by the offset grip throughout every rep. Alternate which hand leads each set to prevent bilateral asymmetry.",
  cues: "Grip the bar from the side, hands side by side, forward hand supinated and rear hand pronated. Pull until the chin clears the bar to the side of the hands, alternating which side each rep or each set. Keep the core braced — the offset grip creates a rotation that must be resisted. Lower to full arm extension.",
  equipment: "Pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 11,
  name: "One-Arm Australian Pull-Up | (Low Bar)",
  alt: null,
  pathTag: "one-arm-chin",
  muscles: [
    { n: "Lats",       p: true  },
    { n: "Rear Delts", p: true  },
    { n: "Biceps",     p: true  },
    { n: "Core",       p: true  },
  ],
  tags: ["back", "biceps", "shoulders", "core"],
  diff: 4.3,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: false, eff: 2 },
  joints: { wrist: 0, elbow: 2, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 0, thoracic: 0, si: 1, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.18, 0.32],
  desc: "An Australian Pull-Up performed with one arm in a supinated (underhand) grip — the working hand grips the bar while the other arm is held across the chest or behind the back. The unilateral horizontal row places the full pulling demand on a single side, training the same lat and rear deltoid recruitment as the Archer Chin-Up but from a horizontal rather than vertical pulling angle. Load is easily adjusted by changing body angle: more upright is easier, more horizontal is harder. The most accessible unilateral pulling progression and a direct bridge toward the Archer Chin-Up.",
  cues: "Set the bar at roughly hip height. Grip with the working hand supinated, palms toward you. Keep the body rigid from head to heel — do not let the hips drop or rotate toward the working arm. Drive the elbow back toward the hip. Train each arm independently for equal sets.",
  equipment: "Low bar",
  position: "Supine",
  youtube: "LINK_TODO"
},

{
  id: 25,
  name: "Fingertip Chin-Up",
  alt: null,
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Forearms",   p: true  },
    { n: "Rear Delts", p: false },
  ],
  tags: ["chin-up", "back", "biceps", "shoulders", "grip"],
  diff: 5,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: false, eff: 2 },
  joints: { wrist: 2, elbow: 1, shoulder: 1, neck: 0, lowerBack: 0,
            knee: 0, fingers: 5, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 4,
  kcalPerRep: [0.27, 0.49],
  desc: "A chin-up performed gripping the bar with only the fingers and the first knuckle joint — no palm contact, no thumb wrap — in a supinated (palms-toward-you) orientation. Removing the palm and thumb from the hold isolates the flexor tendons of the fingers as the sole contact point, producing climbing-specific finger strength demand far beyond a standard or even a towel grip. The reduced contact area also removes the mechanical leverage a full grip provides, so even strong chin-up performers will find their finger flexors fail well before their biceps or lats. Build up via dead hangs and negatives before attempting full reps.",
  cues: "Curl the fingers over the bar at the first knuckle only — no palm or thumb contact with the bar. Keep the wrists neutral, not flexed, to protect the finger joints. Pull smoothly with no jerking; any sudden load spike on a fingertip grip risks a finger flexor strain. Lower under control and stop the set immediately if grip begins to fail rather than fighting through a slip.",
  equipment: "Pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 27,
  name: "False Grip Chin-Up",
  sidequestKey: "Fingertip Chin-Up",
  alt: null,
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Forearms",   p: true  },
    { n: "Rear Delts", p: false },
  ],
  tags: ["chin-up", "back", "biceps", "shoulders", "grip"],
  diff: 5.5,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: false, eff: 2 },
  joints: { wrist: 4, elbow: 2, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 3, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 4,
  kcalPerRep: [0.28, 0.50],
  desc: "A chin-up performed with the wrist flexed forward over the top of the bar — palm rolled around so the heel of the hand, not the underside of the wrist, takes the load — in a supinated (palms-toward-you) orientation throughout. Unlike a standard grip, the false grip shortens the effective range needed to bring the body to bar height and trains the specific wrist-flexed position required to transition cleanly into a strict muscle-up. Because the bar is a fixed, non-rotating diameter, the wrist is forced into and held at a more extreme flexed angle than the equivalent false grip on rings, making the bar version the harder of the two on the wrist joint. A direct prerequisite for the strict (non-kipping) muscle-up.",
  cues: "Before the first rep, roll the wrist forward over the bar so the wrist crease — not the underside of the forearm — rests on top of the bar; the palm wraps down and around. Keep the wrist locked in this flexed position for the entire set; if it slips back to a standard grip mid-rep, reset before continuing. Depress the scapulae, then pull as in a standard chin-up. Apply chalk to the wrist and palm to manage the added skin friction. Stop the set the moment the false grip position breaks down rather than finishing reps on a standard grip.",
  equipment: "Pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 32,
  name: "Vertical Rope Chin-Up",
  sidequestKey: "Towel Chin-Up",
  alt: null,
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Forearms",   p: true  },
    { n: "Rear Delts", p: false },
  ],
  tags: ["chin-up", "back", "biceps", "shoulders", "grip"],
  diff: 5.5,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: false, eff: 2 },
  joints: { wrist: 3, elbow: 2, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 5, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 4,
  kcalPerRep: [0.29, 0.52],
  desc: "A thick rope (1.5–2 inches in diameter) is tossed over the bar so two free ends hang down, and a chin-up is performed gripping one rope end in each hand in a supinated, palms-facing orientation. Unlike a towel, where both hands share a single piece of flat fabric draped over a fixed bar, each hand here must independently stabilise its own free-hanging, cylindrical rope with no shared rigid anchor at all — the ropes can twist, swing, and shift mid-rep in ways a towel or bar cannot. The thick diameter alone demands a substantially larger crush grip than a standard bar. A.K.A. Brookfield Rope Chin-Up.",
  cues: "Toss a thick rope over the bar so both ends hang evenly. Grip one end firmly in each hand, palms facing each other or toward you, arms fully extended. Initiate with a scapular depression, then pull the elbows down and back, actively resisting any twist or swing in the ropes. Lower under control to a full hang each rep — do not let grip fatigue turn the descent into a drop.",
  equipment: "Pull-up bar + hanging band / towel loop",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 12,
  name: "Plyo Chin-Up",
  sidequestKey: "Wide Chin-Up",
  alt: null,
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Rear Delts", p: false },
    { n: "Core",       p: false },
  ],
  tags: ["chin-up", "back", "biceps", "power"],
  diff: 4.8,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 0, elbow: 3, shoulder: 2, neck: 0, lowerBack: 0,
            knee: 0, fingers: 1, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 3,
  kcalPerRep: [0.32, 0.58],
  desc: "A chin-up performed with a supinated (underhand, palms-toward-you) grip where the concentric phase is executed explosively — the body is propelled upward with enough force to briefly release the bar at the top. The hands return to the bar before the descent begins. The explosive supinated pull places high peak demand on the biceps tendon and elbow joint at the catch, earning the elevated elbow score. Serves as the power development entry point in the chin-up family. A.K.A. Explosive Chin-Up.",
  cues: "From a dead hang, generate maximum acceleration on the pull — the aim is to drive the chest past the bar. Release the bar at the apex, then re-grip immediately before descending. Never catch the bar with locked elbows. Lower under control to a full dead hang before the next rep.",
  equipment: "Pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 13,
  name: "L-Sit Chin-Up",
  alt: null,
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Core",       p: true  },
    { n: "Hip Flexors",p: true  },
  ],
  tags: ["chin-up", "back", "biceps", "core"],
  diff: 6,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 0, elbow: 2, shoulder: 2, neck: 0, lowerBack: 0,
            knee: 0, fingers: 1, thoracic: 0, si: 0, hip: 2, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 3,
  technique: 4,
  kcalPerRep: [0.28, 0.50],
  desc: "A chin-up performed with a supinated (underhand, palms-toward-you) grip while maintaining an L-sit position throughout — legs held parallel to the floor with knees straight. The L-position adds full hip flexor and anterior core isometric demand on top of the standard pulling load. The supinated grip marginally reduces the pulling difficulty versus the pronated L-sit pull-up, which is useful for athletes limited more by lat strength than core strength. The L must be fully established before the first pull — any leg drop terminates the set.",
  cues: "Hang at full arm extension, palms toward you. Compress the abs and drive the legs to parallel before the first pull. Maintain the L throughout every rep — if the legs drop, the set is over. Depress the scapulae and pull the elbows down and back while keeping the legs locked forward.",
  equipment: "Pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 28,
  name: "False Grip Chin-Up | (Rings)",
  sidequestKey: "L-Sit Chin-Up",
  alt: null,
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Forearms",   p: true  },
    { n: "Core",       p: false },
  ],
  tags: ["chin-up", "back", "biceps", "shoulders", "grip", "core"],
  diff: 6.5,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: true,  eff: 3 },
  end:  { suit: false, eff: 2 },
  joints: { wrist: 3, elbow: 2, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 3, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 2,
  mobility: 1,
  technique: 4,
  kcalPerRep: [0.30, 0.54],
  desc: "A chin-up performed on gymnastic rings with the wrists flexed forward over the rings in a false grip, held in a supinated (palms-toward-you) orientation throughout. The rings can rotate to partially accommodate the flexed wrist position, making this fractionally kinder on the wrist than the equivalent False Grip Chin-Up on a fixed bar — but the rings simultaneously demand active resistance against unwanted rotation, replacing one stress with another. This is the single most direct strength-and-skill prerequisite for the strict ring muscle-up. The false grip should be set before the first pull and actively maintained through the entire set.",
  cues: "Set the false grip on both rings before beginning — wrist creases rolled forward over the rings, palms wrapped down and around. Depress the scapulae, then pull as in a standard ring chin-up, resisting ring rotation throughout. Keep the false grip locked through the full rep; do not let it slip into a standard grip mid-set. Apply chalk to the wrists for skin protection. Build up via false grip ring hangs and rows before attempting full reps.",
  equipment: "Gymnastic rings",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 24,
  name: "Sternum Chin-Up",
  sidequestKey: "Fingertip Chin-Up",
  alt: null,
  muscles: [
    { n: "Lats",       p: true  },
    { n: "Rhomboids",  p: true  },
    { n: "Biceps",     p: false },
    { n: "Rear Delts", p: false },
  ],
  tags: ["chin-up", "back", "biceps", "shoulders"],
  diff: 5.5,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: true,  eff: 4 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 0, elbow: 1, shoulder: 3, neck: 1, lowerBack: 2,
            knee: 0, fingers: 1, thoracic: 2, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 2,
  technique: 4,
  kcalPerRep: [0.31, 0.56],
  desc: "A supinated (underhand, palms-toward-you) chin-up in which the head and upper back lean back and the chest drives forward through the pull, finishing with the sternum — not the chin — at bar height and the shoulder blades fully retracted. Devised by Vince Gironda, the extended thoracic arch and rearward head position add a full-range scapular retraction component on top of the standard pull, recruiting the rhomboids and lower trapezius far more directly than a standard chin-up. Most people who believe they are already doing this are still performing a standard chin-up with a slight lean; the rep only counts once the sternum, not the collarbones, reaches the bar. A.K.A. Gironda Chin-Up.",
  cues: "Hang at full arm extension, palms toward you. Begin the pull by depressing the scapulae, then drive the elbows down and back while leaning the head back and arching the upper back — picture aiming your sternum, not your chin, at the bar. Finish with the shoulder blades fully pinned together at bar height. Lower under control back to a dead hang, re-establishing full extension each rep.",
  equipment: "Pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 33,
  name: "One-Arm Ring Row",
  sidequestKey: "Fingertip Chin-Up",
  alt: null,
  pathTag: "one-arm-chin",
  muscles: [
    { n: "Lats",       p: true  },
    { n: "Rear Delts", p: true  },
    { n: "Biceps",     p: true  },
    { n: "Core",       p: true  },
  ],
  tags: ["back", "biceps", "shoulders", "core"],
  diff: 5,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: false, eff: 2 },
  joints: { wrist: 1, elbow: 2, shoulder: 2, neck: 0, lowerBack: 1,
            knee: 0, fingers: 1, thoracic: 0, si: 1, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 2,
  technique: 3,
  kcalPer3SecHold: [0.20, 0.36],
  desc: "The One-Arm Australian Pull-Up performed on a single gymnastic ring in a supinated (palms-toward-you) orientation instead of a fixed low bar. Because the ring hangs freely and rotates, the body does not need to stay perfectly parallel to the floor as it does on a bar — the working shoulder can drop lower at the bottom and rise higher at the top, giving a noticeably greater range of motion than the bar version, at the cost of a far less stable base to pull against. Load is adjusted the same way as the bar version, via body angle, with the ring's freedom of rotation adding an independent stabilisation demand throughout. A more advanced bridge toward the Archer Chin-Up than its low-bar counterpart.",
  cues: "Set the ring to roughly hip height. Grip with the working hand supinated, palm toward you, and lean back until the arm is straight. Let the non-working shoulder drop slightly at the bottom and rise above the ring at the top to use the full available range. Keep the body rigid through the torso — do not let the hips sag or rotate toward the working arm. Train each arm independently for equal sets.",
  equipment: "Gymnastic rings",
  position: "Supine",
  youtube: "LINK_TODO"
},

{
  id: 34,
  name: "L-Sit Chin-Up | (Rings)",
  sidequestKey: "One-Arm Chin-Up | Lock-Off",
  alt: null,
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Core",       p: true  },
    { n: "Hip Flexors",p: true  },
  ],
  tags: ["chin-up", "back", "biceps", "core"],
  diff: 7,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 1, elbow: 2, shoulder: 2, neck: 0, lowerBack: 0,
            knee: 0, fingers: 1, thoracic: 0, si: 0, hip: 2, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 3,
  technique: 4,
  kcalPerRep: [0.31, 0.56],
  desc: "The L-Sit Chin-Up performed on gymnastic rings instead of a fixed bar, legs held parallel to the floor with knees straight for the entire set. The rings will want to rotate and drift outward under the combined pulling and L-sit demand, forcing the forearms and shoulders to actively stabilise the path of the pull on top of the hip flexor and anterior core isometric load already present in the bar version. The ring's natural rotation does allow the wrists to settle into a slightly more comfortable angle at the top than a fixed bar, partially offsetting the added stabilisation cost. Master the bar version before progressing here.",
  cues: "Grip the rings firmly, palms toward you. Compress the abs and drive the legs to parallel before the first pull, and resist any ring rotation as you establish the position. Maintain the L throughout every rep — if the legs drop, the set is over. Depress the scapulae and pull the elbows down and back while actively controlling ring drift.",
  equipment: "Gymnastic rings",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 35,
  name: "Plyo Chin-Up | (Rings)",
  sidequestKey: "Towel Chin-Up",
  alt: null,
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Rear Delts", p: false },
    { n: "Core",       p: false },
  ],
  tags: ["chin-up", "back", "biceps", "power"],
  diff: 5.5,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 1, elbow: 3, shoulder: 3, neck: 0, lowerBack: 0,
            knee: 0, fingers: 2, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 4,
  kcalPerRep: [0.36, 0.65],
  desc: "The Plyo Chin-Up performed on gymnastic rings: the body is explosively propelled upward with enough force to briefly release the rings at the top before re-gripping and lowering under control. Catching a freely-rotating ring after an explosive release is significantly less forgiving than catching a fixed bar, since the rings can be mid-rotation or drifting apart at the moment of re-grip, demanding much sharper hand-eye timing and a faster, more secure catch. A direct power-and-timing precursor to the ring muscle-up, more specific to that skill than the bar version.",
  cues: "From a dead hang on the rings, generate maximum acceleration on the pull, driving the chest well past ring height. Release both rings at the apex, snapping the hands back to the rings the instant they begin to separate or rotate away from the grip path. Never catch with locked elbows. Lower under full control to a dead hang before the next rep.",
  equipment: "Gymnastic rings",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 14,
  name: "Typewriter Chin-Up",
  alt: null,
  muscles: [
    { n: "Lats",       p: true  },
    { n: "Biceps",     p: true  },
    { n: "Rear Delts", p: true  },
    { n: "Core",       p: false },
  ],
  tags: ["chin-up", "back", "biceps", "shoulders"],
  diff: 7.5,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 0, elbow: 3, shoulder: 2, neck: 0, lowerBack: 0,
            knee: 0, fingers: 2, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 4,
  mobility: 2,
  technique: 3,
  kcalPerRep: [0.35, 0.63],
  desc: "Pull to bar height in a wide supinated (underhand, palms-toward-you) grip, then sweep laterally from side to side at constant height before descending. Each side of the sweep approaches the unilateral loading of an Archer Chin-Up as the body shifts to one arm. The supinated grip increases bicep involvement throughout each lateral traverse while retaining the same unilateral lat and rear deltoid challenge at the extremes. Fractionally more accessible than the pronated Typewriter Pull-Up for athletes with proportionally greater bicep than lat strength.",
  cues: "Pull to bar height before initiating the lateral shift — never start the sweep from below the bar. Keep constant height throughout the full traverse. Control the sweep speed; momentum through the midpoint reduces the training stimulus. Return to centre before descending to a full dead hang.",
  equipment: "Wide pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 15,
  name: "Around The World Chin-Up",
  hof: true,
  alt: null,
  muscles: [
    { n: "Lats",       p: true  },
    { n: "Rear Delts", p: true  },
    { n: "Biceps",     p: true  },
    { n: "Core",       p: true  },
  ],
  tags: ["chin-up", "back", "biceps", "shoulders", "core"],
  diff: 7,
  str:  { suit: true,  eff: 4 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 0, elbow: 3, shoulder: 3, neck: 0, lowerBack: 0,
            knee: 0, fingers: 2, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 4,
  mobility: 2,
  technique: 5,
  kcalPerRep: [0.40, 0.72],
  desc: "Pull to bar height in a wide supinated (underhand, palms-toward-you) grip, then trace a full lateral arc — sweeping from one side all the way to the other at constant height — before descending. The arc must be maintained at bar height throughout; any sag mid-traverse indicates insufficient base strength. The extreme ends of each sweep approach archer chin-up loading, and the technique demand is the highest of any bilateral chin-up variant. Master the Typewriter Chin-Up first.",
  cues: "Pull to bar height before starting the arc — height must stay constant for the entire sweep. Drive each side of the arc by shifting the weight actively toward that arm, not by dipping. Reverse direction smoothly without pause at the extremes. Lower to a full dead hang after completing the full arc.",
  equipment: "Wide pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

// ── FAMILY: UNILATERAL ──
// One-arm supinated pulling progressions, ordered from bilateral-assisted
// entry tools toward the full One-Arm Chin-Up. Each entry places increasing
// unilateral demand on the working arm. Train each side independently.

{
  id: 16,
  name: "One-Arm Chin-Up | Lock-Off",
  alt: null,
  pathTag: "one-arm-chin",
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Core",       p: true  },
    { n: "Rear Delts", p: false },
  ],
  tags: ["chin-up", "back", "biceps", "core"],
  diff: 7,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 0, elbow: 3, shoulder: 3, neck: 0, lowerBack: 1,
            knee: 0, fingers: 2, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 3,
  mobility: 1,
  technique: 3,
  kcalPer3SecHold: [0.10, 0.18],
  desc: "Pull to the top position using a bilateral supinated (underhand) chin-up, then release one hand and hold the chin-over-bar position on a single supinated arm for as long as possible. Only the isometric hold is performed unilaterally — the concentric phase remains bilateral. The supinated grip places the biceps in their strongest line of pull at the top position, making this fractionally more accessible than the pronated One-Arm Lock-Off. Trains the specific single-arm holding strength required for the One-Arm Chin-Up and serves as a direct precursor to the One-Arm Negative Chin-Up. A.K.A. One-Arm Flex Hang. Train each side independently.",
  cues: "Perform a full bilateral chin-up, then release the free hand cleanly at the top — do not shift weight gradually. Keep the working elbow close to the torso and forearm supinated throughout the hold. Resist lateral torso lean toward the working side. Progress by increasing hold duration before advancing to One-Arm Negative Chin-Ups.",
  equipment: "Pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 17,
  name: "Uneven Chin-Up",
  sidequestKey: "Towel Chin-Up",
  alt: null,
  pathTag: "one-arm-chin",
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Core",       p: false },
    { n: "Rear Delts", p: false },
  ],
  tags: ["chin-up", "back", "biceps", "core"],
  diff: 5.9,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 1, elbow: 4, shoulder: 3, neck: 0, lowerBack: 1,
            knee: 0, fingers: 3, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 4,
  mobility: 1,
  technique: 4,
  kcalPerRep: [0.30, 0.54],
  desc: "One hand grips the bar in a supinated (underhand, chin-up) position at standard height while the other hand grips a lower attachment — a hanging band, towel loop, or the opposite wrist — at a reduced height. The height differential shifts the majority of load onto the top supinated arm, creating a loading gradient between a bilateral chin-up and a full One-Arm Chin-Up. The supinated top-arm position places the biceps at peak mechanical advantage, making this fractionally more accessible than the pronated Uneven Pull-Up. The lower the assisting attachment point, the greater the unilateral demand. Train each side independently.",
  cues: "Grip the bar supinated with the working hand, and grip the lower attachment (band or towel loop) with the assisting hand. Gradually lower the assisting hand's attachment point over weeks as the top arm strengthens. Keep the torso vertical — do not allow lateral lean toward the working arm.",
  equipment: "Pull-up bar + hanging band / towel loop",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 18,
  name: "Archer Chin-Up",
  alt: null,
  pathTag: "one-arm-chin",
  pathNode: true,
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Core",       p: false },
    { n: "Rear Delts", p: false },
  ],
  tags: ["chin-up", "back", "biceps", "core"],
  diff: 6.5,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 2 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 0, elbow: 3, shoulder: 3, neck: 0, lowerBack: 1,
            knee: 0, fingers: 2, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 4,
  mobility: 2,
  technique: 4,
  kcalPerRep: [0.33, 0.59],
  desc: "An archer pull performed with the working arm supinated (underhand grip) rather than pronated. The working hand grips the bar in a standard chin-up position while the extended (assisting) arm reaches out to the side near-straight, providing only minimal stabilising contact. The supinated working arm places the biceps in a mechanically superior pulling line, making the Archer Chin-Up fractionally more accessible than the pronated Archer Pull-Up. Each side must be trained independently and the assisting arm's contribution actively reduced over time. The primary progression toward the One-Arm Chin-Up.",
  cues: "Take a wide grip on the bar, working hand supinated, extended arm pronated and near-straight. Initiate by pulling toward the working side — not straight up. The straight arm is a guide, not a passenger: maintain tension through it and reduce its assistance progressively over weeks. Train each side for equal sets.",
  equipment: "Wide pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 19,
  name: "One-Arm Chin-Up | Negative",
  sidequestKey: "One-Arm Chin-Up | Lock-Off",
  alt: null,
  pathTag: "one-arm-chin",
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Core",       p: true  },
    { n: "Rear Delts", p: false },
  ],
  tags: ["chin-up", "back", "biceps", "core"],
  diff: 7.5,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 1, elbow: 5, shoulder: 4, neck: 0, lowerBack: 2,
            knee: 0, fingers: 3, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 4,
  mobility: 1,
  technique: 4,
  kcalPerRep: [0.27, 0.48],
  desc: "Jump or press with both arms to reach the top position — chin over bar in a supinated grip — then release one hand and lower as slowly as possible on a single supinated arm to a full dead hang. The supinated position places the biceps at maximum mechanical advantage during the eccentric, making this fractionally more manageable than the pronated One-Arm Negative Pull-Up for most athletes. The elbow loading at the bottom of the single-arm eccentric is extreme. The key bridge between bilateral chin-up work and the One-Arm Chin-Up. Target 5–8 seconds lowering per rep. Train each side independently.",
  cues: "Jump or use a box to reach the top — do not exhaust yourself getting there. Release the assisting hand cleanly at the top — do not gradually shift load mid-descent. Keep the lowering arm's elbow close to the body and forearm supinated throughout. Control the descent to a full dead hang. Do not attempt if elbow pain is present.",
  equipment: "Pull-up bar + box or jump to reach top",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 20,
  name: "Wrist-Assisted One-Arm Chin-Up",
  sidequestKey: "One-Arm Chin-Up | Lock-Off",
  alt: null,
  pathTag: "one-arm-chin",
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Core",       p: true  },
    { n: "Rear Delts", p: false },
  ],
  tags: ["chin-up", "back", "biceps", "core"],
  diff: 7,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 5, shoulder: 4, neck: 0, lowerBack: 2,
            knee: 0, fingers: 4, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 4,
  mobility: 1,
  technique: 4,
  kcalPerRep: [0.33, 0.59],
  desc: "One hand grips the bar with a supinated (underhand, chin-up) grip while the free hand wraps around the wrist or lower forearm of the working arm at bar height, providing direct self-assistance through the working limb. The supinated position places the biceps at peak mechanical advantage, making this fractionally more accessible than the pronated Wrist-Assisted One-Arm Pull-Up and the preferred entry point for most athletes approaching their first One-Arm Chin-Up. The level of wrist assistance is self-modulated — as unilateral strength builds, grip pressure from the free hand naturally decreases toward zero. The anti-rotation core demand is identical to the strict One-Arm Chin-Up. Train each side independently.",
  cues: "Grip the wrist — not the bar — with the free hand, keeping both fists at bar height. Reduce the pressure from the assisting hand progressively over training sessions rather than in single jumps. Brace the obliques hard from the first rep — the anti-rotation demand is identical to the full One-Arm Chin-Up.",
  equipment: "Pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 26,
  name: "Finger-Assisted One-Arm Chin-Up",
  sidequestKey: "One-Arm Chin-Up | Lock-Off",
  alt: null,
  pathTag: "one-arm-chin",
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Core",       p: true  },
    { n: "Rear Delts", p: false },
  ],
  tags: ["chin-up", "back", "biceps", "core", "grip"],
  diff: 7,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 5, shoulder: 4, neck: 0, lowerBack: 2,
            knee: 0, fingers: 5, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 4,
  mobility: 1,
  technique: 5,
  kcalPerRep: [0.34, 0.61],
  desc: "The working hand grips the bar in a full supinated (underhand, chin-up) grip while the assisting hand grips the bar beside it using only a small, fixed number of fingers — typically starting at four and reduced by one finger at a time as unilateral strength improves, down to a single finger immediately before the unassisted One-Arm Chin-Up. Because the assisting fingers sit on the bar itself rather than wrapping the working wrist, the amount of usable leverage is far more finely and objectively gradable than Wrist-Assisted variants, making this the preferred final-stage progression for athletes who want a measurable, repeatable assistance ladder. Reduce assisting fingers only once 5–10 clean reps are achieved at the current count. Train each side independently.",
  cues: "Place the working hand on the bar in a full supinated grip. Place only the agreed number of fingers from the assisting hand on the bar immediately beside it, keeping the rest of that hand open and uninvolved. Pull primarily through the working arm — the assisting fingers should feel like a light touch, not a second hand truly pulling. Once 5–10 reps are clean at a given finger count, drop to one fewer finger next session.",
  equipment: "Pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

{
  id: 21,
  name: "One-Arm Chin-Up",
  hof: true,
  alt: null,
  pathTag: "one-arm-chin",
  pathNode: true,
  muscles: [
    { n: "Biceps",     p: true  },
    { n: "Lats",       p: true  },
    { n: "Core",       p: true  },
    { n: "Rear Delts", p: false },
  ],
  tags: ["chin-up", "back", "biceps", "core"],
  diff: 8.9,
  str:  { suit: true,  eff: 5 },
  vol:  { suit: false, eff: 1 },
  end:  { suit: false, eff: 1 },
  joints: { wrist: 2, elbow: 5, shoulder: 5, neck: 0, lowerBack: 3,
            knee: 0, fingers: 4, thoracic: 0, si: 0, hip: 0, groin: 0, ankle: 0, foot: 0 },
  strength: 5,
  mobility: 2,
  technique: 5,
  kcalPerRep: [0.37, 0.66],
  desc: "A full one-arm pull performed with a supinated (underhand, palms-toward-you) grip — from a single-arm dead hang to chin over bar and back, under full control, with no assistance from the free hand. The supinated forearm places the biceps in their mechanically optimal line of pull, making this fractionally more accessible than the pronated One-Arm Pull-Up for most people — though both sit at the extreme end of pulling strength. The shoulder mechanics differ slightly at the top position due to forearm rotation, and the elbow and biceps tendon loading is extreme. A universally recognised benchmark in calisthenics. Train each side independently.",
  cues: "Begin from a dead hang on a single supinated arm. Initiate with scapular depression, then pull the elbow down and back. Keep the free hand completely clear of the bar — touching it, even briefly, disqualifies the rep. Pull the chin clearly over the bar. Lower under full control to a dead hang — do not drop. Rest fully between sides.",
  equipment: "Pull-up bar",
  position: "Hanging",
  youtube: "LINK_TODO"
},

];

const chinupKnownVariants = [
  "Chin-Up",
  "Close Chin-Up",
  "Wide Chin-Up",
  "Chin-Up | Paused",
  "Ring Chin-Up",
  "Towel Chin-Up",
  "Fingertip Chin-Up",
  "False Grip Chin-Up",
  "Vertical Rope Chin-Up",
  "L-Sit Chin-Up",
  "Commando Chin-Up",
  "Sternum Chin-Up",
  "One-Arm Ring Row",
  "Typewriter Chin-Up",
  "Around The World Chin-Up",
  "Jumping Chin-Up",
  "Chin-Up | Slow Negative",
  "Chin-Up | Flex Hang",
  "Chin-Up | Scapular",
  "One-Arm Dead Hang",
  "One-Arm Scapular Pull",
  "Plyo Chin-Up",
  "Australian Pull-Up",
  "One-Arm Australian Pull-Up",
  "Archer Chin-Up",
  "Uneven Chin-Up",
  "One-Arm Chin-Up | Lock-Off",
  "One-Arm Chin-Up | Negative",
  "Wrist-Assisted One-Arm Chin-Up",
  "Finger-Assisted One-Arm Chin-Up",
  "One-Arm Chin-Up",
];

window.chinupData = chinupData;
window.chinupKnownVariants = chinupKnownVariants;
